### ISSUE TITLE
Updater deprecation

### ISSUE THREAD

**Issue by Rbroughton007** [home-assistant/home-assistant.github.io#22046] opened 2022-03-16 18:52 UTC
### Feedback

Wording on https://www.home-assistant.io/integrations/updater/ - should include a link to both the blog at (https://github.com/home-assistant/home-assistant.io/issues/22018) and a link to Version (https://www.home-assistant.io/integrations/version/)

### URL

https://www.home-assistant.io/integrations/updater/ 

### Additional information

I know Frenck says to just 'Read the Release notes', but it is easier for the typical user if he included the links to how to fix it and the discussion as opposed to just telling people to read the documents. As this page being listed is the documents, the changes of adding links would fix it. Not everyone is an in-depth programmer with lots of time trying to track down every Release note breaking change.

**Comment by frenck** [comment] 2022-03-16 19:05
There is no need to create duplicates. Closing as duplicate of #22018

**Closed as completed by frenck** 2022-03-16 19:05 UTC
Labels: integration: updater, integration: version
