### ISSUE TITLE
Google Actions has changed significantly since these instructions were written

### ISSUE THREAD

**Issue by red-yfronts** [home-assistant/home-assistant.github.io#17360] opened 2021-04-09 12:55 UTC
### Feedback

It is impossible to achieve the desired outcome using these out of date instructions.

I

### URL

https://www.home-assistant.io/integrations/google_assistant/

### Version

2021.4.1

**Comment by frenck** [comment] 2021-04-10 09:34
Duplicate of #17281

**Closed as completed by frenck** 2021-04-10 09:34 UTC
Labels: integration: google_assistant
