### ISSUE TITLE
mqtt.publish has misleading information and missing examples

### ISSUE THREAD

**Issue by sn3ak** [home-assistant/home-assistant.github.io#25182] opened 2022-12-07 21:46 UTC
### Feedback

The documentation states that "payload must be a string. If you want to send JSON then you need to format/escape it properly."
This appears to be inaccurate or doesn't have proper examples. home assistant will happily adjust your code from a single line like:
```
payload: '{\"device_class\": \"temperature\", \"name\": \"Acurite-986-1R-51778-T\", \"unit_of_measurement\": \"\\u00b0C\", \"value_template\": \"{{ value|float }}\", \"state_topic\": \"rtl_433/rtl433/devices/Acurite-986/1R/51778/temperature_C\", \"unique_id\": \"Acurite-986-1R-51778-T\", \"device\": {\"identifiers\": \"Acurite-986-1R-51778\", \"name\": \"Acurite-986-1R-51778\", \"model\": \"Acurite-986\", \"manufacturer\": \"rtl_433\"}}'
```
into something like:
```
  payload: >-
    {\"device_class\": \"temperature\", \"name\": \"Acurite-986-1R-51778-T\",
    \"unit_of_measurement\": \"\\u00b0C\", \"value_template\": \"{{ value|float
    }}\", \"state_topic\":
    \"rtl_433/rtl433/devices/Acurite-986/1R/51778/temperature_C\",
    \"unique_id\": \"Acurite-986-1R-51778-T\", \"device\": {\"identifiers\":
    \"Acurite-986-1R-51778\", \"name\": \"Acurite-986-1R-51778\", \"model\":
    \"Acurite-986\", \"manufacturer\": \"rtl_433\"}}
```
For me at least, this shows up in the MQTT server escaped. Removing the escaping published the correct information.

Missing from Documentation. How to include templates in the payload. See the above examples which result in an error:
`Failed to call service script/autodiscovery. Error rendering data template: UndefinedError: 'value' is undefined`

Please include an example that shows how to do so. After hours of searching and trying multiple different things I learned that 
`"value_template": "{{ float(value|int) * 99 + 1 }}",` needed to become `"value_template": "{{ "{{ float(value|int) * 99 + 1 }}" }}",`

### URL

https://www.home-assistant.io/integrations/mqtt/#publish--dump-services

### Version

2022.11.5

### Additional information

See [this forum link](https://community.home-assistant.io/t/error-rendering-data-template-undefinederror-value-is-undefined/499446/3) for more details

**Comment by jbouwh** [comment] 2022-12-08 09:33
I am not seeing any incorrect information in the current documentation. BTW This is just the part for the publishing service. When I try the examples that are given, they all work as expected.
Mind: The `payload` value cannot be used as a variable for `payload_template`. If a `payload_template` is specified, a specified `payload` is ignored. The question is if having payload available as `value` would be useful.

For Templating with value_templates and command_templates in general (for use on the MQTT platforms) there is additional documentation here:
https://www.home-assistant.io/docs/configuration/templating/#using-templates-with-the-mqtt-integration

**Comment by sn3ak** [comment] 2022-12-08 18:05
perhaps I didn't explain the issue well. I wasn't trying to use payload_template. I was using payload. The problem isn't that I was trying to use a template within home assistant, but that home assistant is trying to parse the template I was sending as a JSON string through the mqtt.publish service.

The error on value shouldn't occur, because I am not trying to get HA to replace it with a value, I'm sending it as a string to be published in the MQTT server. If I take the example from the documentation and format/escape the string, 'value' is still trying to be rendered by home assistant.

Thus I feel the documentation is incomplete. An example using "{{ "{{  value }}" }}" should be given to prevent people from pulling their hair out.

--------------------------------------------------------------------------------------------------------------------------------------------

As far as the inaccuracy in the documentation, it uses this example:
```
topic: home-assistant/light/1/state
payload: "{\"Status\":\"off\", \"Data\":\"something\"}"
```

If you use that exact example from services with mqtt.publish:
![HA-mqtt publish-service](https://user-images.githubusercontent.com/1995550/206530428-277fbc60-2e71-48fb-b0bb-551ab3e1dff1.png)


the following is what is published to the MQTT Server:
![HA-mqtt publish-example](https://user-images.githubusercontent.com/1995550/206526173-c39ec628-0cdb-48cf-8259-0e4401e8d737.png)

I already had home-assistant/light/1/state set, so I changed 1 to 2 and that is the only change I made to the code above.

**Comment by jbouwh** [comment] 2022-12-08 21:47
The example shows the YAML syntax. In that case it is correct to escape the quotes.

**Comment by jbouwh** [comment] 2022-12-11 16:17
Did some further testing, something strange happens when the string contains a template pattern. It seems the string is parsed as template. This is not caused by the MQTT integration though.

**Comment by jbouwh** [comment] 2022-12-11 19:24
I have committed a PR that should clarify how to use the MQTT publish function when there are templates used.
It is not very common to use the developer tools for that. An alternative could be using the publish function at the MQTT configuration entry. I hope to enrich this publish function with `QoS` and `retain` support as it now only does support QoS 0.

**Closed as completed** 2022-12-12 11:23 UTC
Labels: integration: mqtt

**Comment by sn3ak** [comment] 2022-12-27 20:01
Thank you @jbouwh! I hope this change helps others as it was hard for me to find the solution.
