### ISSUE TITLE
Efergy not integrated with new energy from grid used by home assistant

### ISSUE THREAD

**Issue by mgcm72** [home-assistant/home-assistant.github.io#19085] opened 2021-08-26 04:52 UTC
### Feedback

The new functionality implemented by home assistant ( the energy consumption panel) is not possible with efergy 
Please see here ( as home assistant recommend)
https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

### URL

https://www.home-assistant.io/integrations/efergy/

### Version

2021.8.8

**Comment by frenck** [comment] 2021-08-26 08:58
duplicate of https://github.com/home-assistant/core/issues/54219

**Closed as completed by frenck** 2021-08-26 08:58 UTC
Labels: integration: efergy
