### ISSUE TITLE
Tuya has cuted back on "free trail"

### ISSUE THREAD

**Issue by flemming64** [home-assistant/home-assistant.github.io#25092] opened 2022-11-29 14:58 UTC
### Feedback

Tuya has cuted back on "free trail". It is now (15. oct 2022) 30 days without renewle 

### URL

https://www.home-assistant.io/integrations/tuya

**Comment by frenck** [comment] 2022-11-29 15:46
This has been the case for quite some time now. You can request to extend the trial after the first ended by six months increments.

**Comment by jjlauer** [comment] 2023-01-09 03:50
I'm sorry, there is no easy way to extend this anymore and the documentation is out of date.

I'm also really pissed that I ever bought any Tuya devices where all my home automation stops working because they have a time limit on my account.  I can't wait for matter devices to be released and I can dump these pieces of junk.

**Comment by flemming64** [comment] 2023-01-09 07:08
I allready gave up and has started selling the rest of my Tuya.

**Comment by frenck** [comment] 2023-01-09 11:31
We've reached out to Tuya they have confirmed nothing changed, so did we confirm it as well.
The procedures are the same as before.

Therefore, closing this issue for now.

../Frenck

**Closed as not planned by frenck** 2023-01-09 11:31 UTC
Labels: integration: tuya
