### ISSUE TITLE
Where is the raspbery pi image file???

### ISSUE THREAD

**Issue by titchy** [home-assistant/home-assistant.github.io#34107] opened 2024-08-03 10:30 UTC
### Feedback

I just want the image file, I do not want to install the raspberry pi image writer or anything else. Just the HAOS image, why is there not a link at the beginning of the article?

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2024.7.4

**Comment by mdisabato** [comment] 2024-08-03 15:11
Confirmed. I just looked at https://www.home-assistant.io/installation/raspberrypi and the entire section on using Balena Etcher has been removed. This had the link to the current version. For those of us choosing or required to use Etcher, this section is critical. 

Thank you.

Michael

**Comment by cogneato** [comment] 2024-08-05 21:53
@titchy In regard to your question, all of the image files are all available at https://github.com/home-assistant/operating-system/releases under Assets for each release.  They do not have their own Raspberry Pi page to link to. The RPi imager downloads the one for the model you specify.

@mdisabato If you are using etcher the link above would be the same to use to grab the image that you need.

**Comment by c0ffeeca7** [comment] 2024-08-12 13:46
Closing this as a duplicate of #33997

**Closed as completed by c0ffeeca7** 2024-08-12 13:46 UTC
Labels: installation
