### ISSUE TITLE
Minor WSL install script errors

### ISSUE THREAD

**Issue by pachallis** [home-assistant/home-assistant.github.io#29775] opened 2023-11-09 17:22 UTC
### Feedback

In the "install dependencies" libtiff6 is not required in ubuntu 22.04

In the "install core" it states "pip3 install homeassistant==2023.11.1" - latest supported version is 2023.7.3

Sorry if this known already - first attempt at installing Home Assistant + first use of WSL under Windows 11

### URL

https://www.home-assistant.io/installation/windows/

### Version

2023.11.1

**Comment by jterrace** [comment] 2023-12-13 03:41
I had this on WSL as well. It's because python is 3.10. Newer home assistant packages require 3.11. I followed https://rothoma2.com/2023/06/03/how-to-install-python-3-11-on-ubuntu-wsl/ to install the `python3.11`, `python3.11-dev`, and `python3.11-venv` packages. Then use `python3.11 -m venv .` instead of `python3 -m venv .` when creating the virtualenv. That let me get the ` homeassistant==2023.12.1` package installed. I have hass up and running on WSL now.

**Comment by frenck** [comment] 2024-05-23 17:32
Thanks for the feedback, this is caused by the Python environment indeed, which is up to you to maintain/setup.

Closing this suggestion on this end, as this is out of scope for our documentation.

../Frenck

**Closed as not planned by frenck** 2024-05-23 17:32 UTC
Labels: installation
