### ISSUE TITLE
Home Assistant Failed update

### ISSUE THREAD

**Issue by JosephRDawson** [home-assistant/home-assistant.github.io#35701] opened 2024-11-11 13:06 UTC
### Feedback

The link provided did not provide enough information to usefully debug the problem.  It just showed me many ways to get the same error.

### URL

https://www.home-assistant.io/more-info/unhealthy/supervisor/

### Version

2024.11.1

### Additional information

![Settings-–-Home-Assistant(2)](https://github.com/user-attachments/assets/3167cb56-ef5a-4b29-9af2-7fece8f46a5a)
This is the error I am getting.

**Comment by klaasnicolaas** [comment] 2024-11-11 13:18
Duplicate of: https://github.com/home-assistant/supervisor/issues/5405

**Closed as not planned by klaasnicolaas** 2024-11-11 13:18 UTC
Labels: more-info
