### ISSUE TITLE
Setup Instructions do not Match ui

### ISSUE THREAD

**Issue by sweavo** [home-assistant/home-assistant.github.io#31663] opened 2024-02-28 18:25 UTC
### Feedback

Instructions say I will need my user code, which I can find in the tuya smart app, but when I go to set up the integration, I see IoT Access ID and IoT Access Secret, not user code.

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2024.2.5

**Comment by hargcore** [comment] 2024-02-29 22:00
Same here!

**Comment by CraigHutchinson** [comment] 2024-03-05 14:44
Here too, where do I get Tuya IoT Access ID and Access Secret?
EDIT: Found Tuya docs https://developer.tuya.com/en/docs/iot/Home-assistant-tuya-intergration?id=Kb0eqjig0utdd

**Comment by PotatoMill** [comment] 2024-03-11 20:40
According to the link it seems it's only possible if you have set up a cloud project, hovewer it is only possible to view the Access Secret for the cloud project if you can verify you are chinese with an chinese id

**Comment by dirkesquire** [comment] 2024-04-24 15:49
Me too. Why does the Help say "enter the code shown on the User Code field. " when the HomeAssistant screen is actually asking for Access ID, Access Secret, Account password? It doesn't match. The text on the Tuya integration and the Tuya Integration help seem completely out of date

**Comment by jtegtmeier** [comment] 2024-08-07 19:27
Same issue here, docs to not match reality. From my recollection of this integration over the years, the "User Code" is a new way to auth with Tuya? I may still have access to an old Tuya IoT cloud account that did work with this integration (still waiting on renewal), but must request access every 6 months when it expires.

The amount of confusion on this is astounding, looks like we have some duplicates:
#32243 #33565 #33603 #33650 #32589 #32477 ...

Edit: It does look like the exiting auth method still works using the console on https://us.platform.tuya.com/cloud. Still hoping for a better way that does not expire every 6 months.

Edit edit: looks like the answer is likely here for me, essentially update HA:
https://github.com/home-assistant/home-assistant.io/issues/32009#issuecomment-2016437127

@frenck These instructions should likely be added to the docs to help folks avoid this issue. Thanks for your work on this!

**Comment by frenck** [comment] 2024-08-12 20:44
> Here too, where do I get Tuya IoT Access ID and Access Secret?

This integration doesn't use that; the old or custom integration does. The integration provided by Home Assistant has the correct description.

>  I may still have access to an old Tuya IoT cloud account

Cool, but... not use by Home Assistant or this integration anymore.

Closing this issue, as the reported issues is either with an old Home Assistant version, or caused by using a custom integration that isn't supported or provided by the Home Assistant project.

../Frenck

**Closed as not planned by frenck** 2024-08-12 20:44 UTC
Labels: integration: tuya
