### ISSUE TITLE
Database Documentation is outdated

### ISSUE THREAD

**Issue by Sirs0ri** [home-assistant/home-assistant.github.io#28048] opened 2023-07-03 15:16 UTC
### Feedback

The code examples on the Database Documentation page are quite outdated.

For example, for states related tables, they only list the table `states` in the example schema, not `state_attributes`, or `states_meta`.

The statistics-relatated tables are missing completely from the docs.

### URL

https://www.home-assistant.io/docs/backend/database/

### Version

2023.6.3

**Comment by frenck** [comment] 2023-07-03 15:23
duplicate of #27699

You can find more information in our data portal: https://data.home-assistant.io

../Frenck

**Closed as not planned by frenck** 2023-07-03 15:23 UTC
