### ISSUE TITLE
Prompt error: 1106: permission deny

### ISSUE THREAD

**Issue by WeR-Best** [home-assistant/home-assistant.github.io#20146] opened 2021-11-04 10:18 UTC
### Feedback

Could not establish connection
Prompt error: 1106: permission deny

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.11.0

### Additional information

The account information and region are confirmed to be correct, there is no problem logging in to tuya.com

**Comment by frenck** [comment] 2021-11-04 10:20
duplicate of https://github.com/home-assistant/core/issues/58145

**Closed as completed by frenck** 2021-11-04 10:20 UTC
Labels: integration: tuya

**Comment by Gferretta** [comment] 2021-11-04 12:58
Hello
The exact same thing has happened to me for last 4 hours.
The new Tuya integration was correctly configured in HA.
I did the update to 2021.11.0 yesterday and it worked fine.
Today in the morning it stopped working without explanation, so I uninstalled the integration and now when trying to add it I receive the error 1106, but all the login  data are totally correct.
I'm from Argentina
Thanks
