### ISSUE TITLE
Honeywell Total Connect integration is only importing one of my thermostats

### ISSUE THREAD

**Issue by mat1583** [home-assistant/home-assistant.github.io#18756] opened 2021-08-04 22:00 UTC
### Feedback

Before upgrading to 2021.8.0 I had the Honeywell total connect setup in my configuration yaml. I have both an upstairs and a downstairs thermostat that are connected via the Redlink gateway. It myTotalConnectComfort, it shows up as two thermostats in one home. Once HA was upgraded, the new integration only shows 1 entity, and my upstairs thermostat is now completely gone from HA. It is not even a disabled entity - just gone. 

I have tried disabling, deleting, and re-adding the integration, but it still only adds the one thermostat. 

As an aside, this direct integration also does not offer the ability to set the polling rate limit, which was a huge factor in reducing the number of errors seen coming back from Honeywell. 

### URL

https://www.home-assistant.io/integrations/honeywell

### Version

2021.8.0

### Additional information

![honeywell_thermostats_in_home](https://user-images.githubusercontent.com/80060060/128260875-0bc9c629-6746-4bdb-b5ab-c820292221ac.png)
![honeywell_ha](https://user-images.githubusercontent.com/80060060/128260876-14c27d39-0c03-4e1d-8283-471e416b3b17.png)

**Comment by zimbab66** [comment] 2021-08-05 12:08
Same issue here. Upper level and downstairs worked fine before update to this new integration.

**Comment by acrprod** [comment] 2021-08-05 13:12
Same issue for me!

**Comment by mat1583** [comment] 2021-08-05 13:19
It looks like async_setup_entry and the HoneywellService are both only using the first entry in the devices list:

    devices = []

    for location in client.locations_by_id.values():
        for device in location.devices_by_id.values():
            if (not loc_id or location.locationid == loc_id) and (
                not dev_id or device.deviceid == dev_id
            ):
                devices.append(device)

    if len(devices) == 0:
        _LOGGER.debug("No devices found")
        return False

    data = HoneywellService(hass, client, username, password, devices[0])

and...

    def __init__(self, hass, client, username, password, device):
        """Initialize the data object."""
        self._hass = hass
        self._client = client
        self._username = username
        self._password = password
        self.device = device

**Comment by rdfurman** [comment] 2021-08-05 13:43
Dupe of https://github.com/home-assistant/core/issues/53981.

**Comment by rdfurman** [comment] 2021-08-05 13:45
> It looks like async_setup_entry and the HoneywellService are both only using the first entry in the devices list:
> 
> ```
> devices = []
> 
> for location in client.locations_by_id.values():
>     for device in location.devices_by_id.values():
>         if (not loc_id or location.locationid == loc_id) and (
>             not dev_id or device.deviceid == dev_id
>         ):
>             devices.append(device)
> 
> if len(devices) == 0:
>     _LOGGER.debug("No devices found")
>     return False
> 
> data = HoneywellService(hass, client, username, password, devices[0])
> ```
> 
> and...
> 
> ```
> def __init__(self, hass, client, username, password, device):
>     """Initialize the data object."""
>     self._hass = hass
>     self._client = client
>     self._username = username
>     self._password = password
>     self.device = device
> ```

Those position 0 references were copied from the old code. The difference is in how the old code was a platform configured (for each sensor) in the config.yaml vs how it is now implemented with config flow (which can only be done once). 

Please see the PR I referenced above.

**Comment by mat1583** [comment] 2021-08-05 13:51
Thanks, I'll try to check it out a little later today. Busy with actual work at the moment. :)

**Comment by frenck** [comment] 2021-08-09 14:30
Duplicate of https://github.com/home-assistant/core/issues/53981

**Closed as completed by frenck** 2021-08-09 14:30 UTC
Labels: integration: honeywell
