### ISSUE TITLE
Tado Smart AC Control V3+ cannot be set to heat/cool/fan

### ISSUE THREAD

**Issue by flosoft** [home-assistant/home-assistant.github.io#21831] opened 2022-02-27 10:57 UTC
### Feedback

Tado Smart AC Control V3+ cannot be set to heat/cool/fan. The only command that works is turning the AC off.

### URL

https://www.home-assistant.io/integrations/tado/

### Version

2022.2.9

### Additional information

https://community.home-assistant.io/t/tado-smart-ac-control-v3-cannot-be-set-to-heat-cool-fan/390689

**Comment by smnmgn** [comment] 2022-04-28 12:11
Hi,
the issue is still present in version 2022.4.7
thank you

**Comment by MacrosorcH** [comment] 2022-05-06 14:11
Hello,
The issue is still present in version 2022.5.1

**Comment by klaasnicolaas** [comment] 2022-05-08 17:03
An issue about this has already been created in core, so I'm closing it here.

**Closed as completed by klaasnicolaas** 2022-05-08 17:03 UTC
Labels: integration: tado
