### ISSUE TITLE
for me is not working

### ISSUE THREAD

**Issue by VITO1973** [home-assistant/home-assistant.github.io#27074] opened 2023-04-20 12:18 UTC
### Feedback

for me is not working this integration ;( is possible  than something has been changed in API?

### URL

https://www.home-assistant.io/integrations/renault/

### Version

2023.4.5

**Comment by epenet** [comment] 2023-04-20 12:29
Duplicate of https://github.com/home-assistant/core/issues/91593

**Closed as completed by epenet** 2023-04-20 12:29 UTC
Labels: integration: renault
