### ISSUE TITLE
Ring docs page not updated to reflect the new 2FA update

### ISSUE THREAD

**Issue by fortepc** [home-assistant/home-assistant.github.io#11603] opened 2020-01-02 14:30 UTC
I know the ring component was broken because Ring updated their API, and also added 2FA, but now that it's working again, the documentation hasn't been updated to reflect whether or not this component works if you have 2FA enabled on your account.

**Comment by fortepc** [comment] 2020-01-02 14:35
I'd update it and submit the PR myself, but I don't know for sure what's going on with the ring component yet. I'm assuming it works but only if you don't have 2FA installed. If someone can confirm that for me I'll make the edit and pr for this page's update.

**Comment by JLCode-tech** [comment] 2020-01-09 22:12
Yes I can confirm it only works without 2FA installed.

**Comment by frenck** [comment] 2020-01-10 08:31
For the 0.104, the integration will work differently, including 2FA support.

I'm suggesting on closing this issue for now since the documentation for the next release has been updated.

**Closed as completed by frenck** 2020-01-10 08:31 UTC
