### ISSUE TITLE
Useless

### ISSUE THREAD

**Issue by gene-vigelis** [home-assistant/home-assistant.github.io#22813] opened 2022-05-19 14:57 UTC
### Feedback

There are absolutely no actual instructions for how to configure SSL without using DuckDNS. Why would you force people to use a service they don't want or need??????

### URL

https://www.home-assistant.io/docs/configuration/securing/

### Version

2022.5.5

### Additional information

Please provide actual instructions for securing HA with SSL

**Comment by yuvalabou** [comment] 2022-05-20 15:20
Feel free to add those instructions. Nobody is forcing you to do anything

**Comment by gene-vigelis** [comment] 2022-05-21 03:30
If I had even bad instructions I would but there i absolutely nothing out
there.

Gene Vigelis

**Comment by frenck** [comment] 2022-05-23 09:42
> There are absolutely no actual instructions for how to configure SSL without using DuckDNS.

That is correct, we used to have quite a few instructions (and growing). The problem is that they become outdated and there is a lot more out there (not just DuckDNS). Creating instructions for every provider on the internet is simply not doable.

Therefore, we provide basic advice and hints on this matter and consider the exact details on setting it up out of scope.

There is a lot of community guides available for many different set ups on our community forums.

> Why would you force people to use a service they don't want or need??????

We don't force anybody, not anywhere, not ever. 


Thanks 👍 

../Frenck

**Closed as completed by frenck** 2022-05-23 09:42 UTC
Labels: configuration
