### ISSUE TITLE
two thermostats

### ISSUE THREAD

**Issue by warren1201** [home-assistant/home-assistant.github.io#18773] opened 2021-08-05 14:15 UTC
### Feedback

I have two Honeywell thermostats.  the integration seems to show to entities but only one is exposed.

### URL

https://www.home-assistant.io/integrations/honeywell/

### Version

2021.8.0

**Comment by rdfurman** [comment] 2021-08-05 14:33
Dupe of https://github.com/home-assistant/core/issues/53981

**Comment by frenck** [comment] 2021-08-09 14:27
Closing as dupe

**Closed as completed by frenck** 2021-08-09 14:27 UTC
Labels: integration: honeywell
