### ISSUE TITLE
Flux Led Configuration 

### ISSUE THREAD

**Issue by LauritsenEnterprises** [home-assistant/home-assistant.github.io#16590] opened 2021-02-15 16:06 UTC
**Feedback**

Documentation says to add flux_LED via the configuration —> integrations page. However it does not show up on the search.

**URL**

https://www.home-assistant.io/integrations/flux_led/

**Version**

2021.2.3

**Comment by frenck** [comment] 2021-02-15 17:25
Duplicate of #16497

**Closed as completed by frenck** 2021-02-15 17:25 UTC
Labels: integration: flux_led
