### ISSUE TITLE
Never asks for wifi setup after install

### ISSUE THREAD

**Issue by btreinders** [home-assistant/home-assistant.github.io#33102] opened 2024-06-05 23:14 UTC
### Feedback

This is completely broken.  I have two ESP32-S3_BOX-3s and after install it never asks to setup wifi after selecting next.  It just goes back to logs and install.  Many people in the forums are seeing this as well.  Please help or fix.

### URL

https://www.home-assistant.io/voice_control/s3_box_voice_assistant/

### Version

2024.6.0

**Comment by c0ffeeca7** [comment] 2024-06-06 05:27
Thank you for your feedback, @btreinders :+1: 
I'm going to close this as a duplicate of #33039

**Closed as completed by c0ffeeca7** 2024-06-06 05:27 UTC
