### ISSUE TITLE
How does one use this integration - docs are empty?

### ISSUE THREAD

**Issue by glyndon** [home-assistant/home-assistant.github.io#28145] opened 2023-07-09 10:43 UTC
### Feedback

Subject says it.
I've been unable to find a way to put this to use in place of my local_file cameras.

### URL

https://www.home-assistant.io/integrations/image/

### Version

2023.7.1

**Comment by klaasnicolaas** [comment] 2023-07-09 14:33
Duplicate of #28103

Maybe you want to use: https://www.home-assistant.io/integrations/template/#image

**Closed as not planned by klaasnicolaas** 2023-07-09 14:33 UTC
Labels: integration: image
