### ISSUE TITLE
On Windows PC install is not working, on Mac install working as intended

### ISSUE THREAD

**Issue by mkennel** [home-assistant/home-assistant.github.io#33084] opened 2024-06-04 20:48 UTC
### Feedback

When attempting to install as described using a windows pc the installer finishes but does not ever prompt user for a wifi network or password using edge or chrome.  When attempting on a mac the installer works as intended. 

### URL

https://www.home-assistant.io/voice_control/s3_box_voice_assistant/

### Version

2024.5.5

**Comment by c0ffeeca7** [comment] 2024-06-06 08:29
Thank you for your feedback, @mkennel :+1: 

However, I'm going to close this as a duplicate of #33039

**Closed as completed by c0ffeeca7** 2024-06-06 08:29 UTC
