### ISSUE TITLE
'Unable to connect to the Litter-Robt API'

### ISSUE THREAD

**Issue by craigccfl** [home-assistant/home-assistant.github.io#18777] opened 2021-08-05 17:00 UTC
### Feedback

On my system (Hassio) RP4, latest Core update 2021.8.0 & 2021.8.1 seems to break the Litter Robot integration. Tried changing pwd. Robot is online with a good connection, Android app working well. 

### URL

https://www.home-assistant.io/integrations/litterrobot/

### Version

2021.8.0

**Comment by natekspencer** [comment] 2021-08-05 17:09
This is a duplicate of https://github.com/home-assistant/core/issues/53983

**Comment by natekspencer** [comment] 2021-08-06 15:45
This is fixed in HA 2021.8.2

**Closed as completed** 2021-08-09 13:36 UTC
Labels: integration: litterrobot
