### ISSUE TITLE
Growatt doesn't allow for integration to HA energy feature now in HA

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#19114] opened 2021-08-28 14:10 UTC
### Feedback

The energy option in HA where you can choose consumption and return to grid show that there are no statistics available to select when Growatt supplied these figures.

It would be awesome to allow Growatt to be able to populate these figures and keep track of usage directly in HA.

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2021.8.8

**Comment by ludeeus** [comment] 2021-08-28 14:12
Duplicate of https://github.com/home-assistant/core/issues/53963

**Closed as completed by ludeeus** 2021-08-28 14:12 UTC
Labels: integration: growatt_server
