### ISSUE TITLE
Add clarification on what unit of measurement Distance is

### ISSUE THREAD

**Issue by miked1313** [home-assistant/home-assistant.github.io#31597] opened 2024-02-24 15:24 UTC
### Feedback

Please add clarification on what unit of measurement Distance uses and if it can be changed as it would help set the tolerance distance value in the Proximity integration configuration.  Thank you.

I am located in the United States and when I view the distance sensors that Proximity created, they are in feet.  My preference would be miles.  If I changed the sensor's unit of measurement to display in miles, the existing data is an integer feet which is then displayed as 35,000 miles for example.

### URL

https://www.home-assistant.io/integrations/proximity/

### Version

2024.2.3

**Comment by mib1185** [comment] 2024-02-29 18:44
- duplicate of #31312

**Closed as completed by mib1185** 2024-02-29 18:44 UTC
Labels: integration: proximity
