### ISSUE TITLE
howto add new climate devices

### ISSUE THREAD

**Issue by pilot1981** [home-assistant/home-assistant.github.io#35854] opened 2024-11-20 17:00 UTC
### Feedback

after login on FGLAIR, what I have to do to add new climate device? it get all devices already added in FGLAIR app?

### URL

https://www.home-assistant.io/integrations/fujitsu_fglair/

### Version

2024.11.2

**Comment by crevetor** [comment] 2024-11-22 00:03
Duplicate of [131053 ](https://github.com/home-assistant/core/issues/131053) closing.

@home-assistant close

**Closed as not planned** 2024-11-22 00:23 UTC
Labels: integration: fujitsu_fglair
