### ISSUE TITLE
Growatt no entities

### ISSUE THREAD

**Issue by szemod** [home-assistant/home-assistant.github.io#19290] opened 2021-09-10 18:02 UTC
### Feedback

After using this integration since a year, suddenly all my growatt entities got disconnected in Home Assistant (44 entities)
After deleted the integration and add again, the integration process and login to server.growatt.com was successful but the integration has no entity at all.
If I restore a working state from snapshot, first looks like all fine , but the Growatt entities are not updated and not updating, after certain time shows disconnected in configuration/entities.
A tired several times to add Growatt_server integration , even into a fresh Home Assistant instance with no success.
If I login to growatt portal everything fine, all inverter available, user name and password accepted.

Would yu pls look into this issue, in case need further information contact to me (szemod@gmail.com)

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2021.9.5

**Comment by muppet3000** [comment] 2021-09-10 18:04
Duplicate of:
https://github.com/home-assistant/core/issues/56044

**Comment by Didou30** [comment] 2021-09-12 16:00
Bonjour,

Avez vous modifiez l'intégration car moi je peut me connecter mais aucune entité n'est remontée !!

Merci de votre aide.

Didier

**Closed as completed** 2021-09-12 16:00 UTC
Labels: integration: growatt_server
