### ISSUE TITLE
hass.io contribution-documentation should mention listening address

### ISSUE THREAD

**Issue by danielperna84** [home-assistant/home-assistant.github.io#1517] opened 2016-11-29 14:28 UTC
The documentation at [https://home-assistant.io/developers/website/](https://home-assistant.io/developers/website/) explains how to setup the environment to work on home-assistant-io. What it lacks though are the parameters with which it's possible to run the server somewhere else than 127.0.0.1:4000, which is essential if you are not working on a local machine (like me, I'm working on a VM).

Since I don't know much about the internals of ruby wtc., I just fiddled around with the Rakefile and hardcoded it to use another IP suitable for my environment. But it would be much easier if we could do `rake preview --listen 1.2.3.4:1234`or something similar. I believe that's already possible, but none of the syntaxes I have tried started the server somewhere else than localhost.

If this is a limitation in the Rakefile, then it should be modified to accept such parameters, and if it's already possbile, what's the correct syntax?

**Comment by Landrash** [comment] 2016-11-30 09:47
This one came up in the chat once and I can't find the answer. As far as I remember Jekyll is limited by design to prevent i being used for hosting. I haven't found a way around this and I personally use ssh tunnels to access Jekyll on a another server. 

Example I use:
```
ssh abc@def -L 4000:localhost:4000
```

**Comment by danielperna84** [comment] 2016-11-30 10:34
Even if it should only listen on localhost by design, it is possible to make it listening on `0.0.0.0` by modifying line 84 in [Rakefile](https://github.com/home-assistant/home-assistant.github.io/blob/next/Rakefile#L81).

Looks like this by default:
```bash
desc "preview the site in a web browser"
task :preview, :listen do |t, args|
  listen_addr = args[:listen] || '127.0.0.1'
```

I don't know which language this is, but the `args` part let's it seem as if it should generally be possible to provide arguments, specifically a `listen` argument in this case. I just don't know how to invoke it as a parameter on the commandline, which I see as a result of not knowing what language this as.

**Comment by andrey-git** [comment] 2017-02-18 14:54
I added a note to the page stating that:

Site generated by rake is only available locally. If you are developing on a headless machine use port forwarding: `ssh -L 4000:localhost:4000 user_on_headless_machine@ip_of_headless_machine`

Is this good enough?

**Comment by danielperna84** [comment] 2017-02-18 18:35
If it's really the case it can't be done differently using arguments (my snippet above looks like it could be done), then yes, mentioning the port forwarding seems valid.

**Comment by Landrash** [comment] 2017-02-19 21:33
Closing with @andrey-git 's solution.

**Closed by Landrash** 2017-02-19 21:33 UTC
Labels: Enhancement
