### ISSUE TITLE
Growatt Integration not working since 6weeks

### ISSUE THREAD

**Issue by rtax56** [home-assistant/home-assistant.github.io#29240] opened 2023-10-08 12:51 UTC
### Feedback

Hello all,
my HA Installation has a not working Growatt Installation .... i has been working wit this server ---> https://server.growatt.com/ ! But i doesnt wprk since 8 weeks or so what was wrong? If i try to reinstall the Growatt Integration ... when i been treated to enter my id and passwd i see this server --> https://server-api.growatt.com ... WHY
what is wrong ....???
When i try to get connected with this server address i https://server-api.growatt.com/index in my browser i got blocked with a 405 code .... who can solve this problem ??
thanks in advance rtax

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2023.10.1

**Comment by muppet3000** [comment] 2023-10-08 18:52
Duplicate of #100874

**Comment by muppet3000** [comment] 2023-10-08 18:53
@home-assistant close

**Closed as completed by muppet3000** 2023-10-08 18:53 UTC
Labels: integration: growatt_server

**Comment by rtax56** [comment] 2023-10-09 11:28
Hello,

Tell me ,why is this issue closed .. please advice

Thanks in advance

Reiner

**Comment by klaasnicolaas** [comment] 2023-10-09 12:00
Please do not use the email function of GitHub, as this will cause you to miss information 😉 

Your issue is in the wrong repository, you have now created an issue for documentation feedback and you have a problem with an integration, which belongs in the core repository. @muppet3000 indicates that your issue is a duplicate of: https://github.com/home-assistant/core/issues/100874

./Klaas
