### ISSUE TITLE
Netatmo Thermostat Issue

### ISSUE THREAD

**Issue by davidfigueiras20** [home-assistant/home-assistant.github.io#19754] opened 2021-10-13 19:26 UTC
### Feedback

The thermostat says that it is not available after a few hours of turning on the server at first everything works fine

### URL

https://www.home-assistant.io/integrations/netatmo/

### Version

2021.10.4

### Additional information

Error doing job: Task exception was never retrieved
12:04:07 – (ERROR) components/netatmo/data_handler.py - el mensaje se produjo por primera vez a las 11:32:07 y aparece 6 veces
Error doing job: Task exception was never retrieved
10:01:08 – (ERROR) components/netatmo/data_handler.py

**Comment by cgtobi** [comment] 2021-10-13 20:30
Duplicate of https://github.com/home-assistant/core/issues/55757

**Closed as completed** 2021-10-13 20:32 UTC
Labels: integration: netatmo
