### ISSUE TITLE
Insteon Hub restore after reset

### ISSUE THREAD

**Issue by smrtlyio** [home-assistant/home-assistant.github.io#22481] opened 2022-04-22 22:03 UTC
### Feedback

This does not appear to work:

Log into Home Assistant and add the Insteon integration. Select Insteon Hub v2 if you have a 2245-xxx or Hub V1 if you have a 2242-xxx.
Follow the instructions on screen to add the integration.

You will need the IP address of the Hub which you should be able to find on your network router. See the documentation for your specific router for instructions.

If you have a Hub v2 you will need the default username and password which are printed on the bottom of the Hub

Add devices to the Hub using the instructions for [Adding Devices to the INSTEON Integration](https://www.home-assistant.io/integrations/insteon/#adding-devices-to-the-insteon-integration)

Once your devices are linked to the Hub again they will appear in Home Assistant automatically.

### URL

https://www.home-assistant.io/integrations/insteon/

### Version

2022.4.6

**Comment by soloyolk** [comment] 2022-04-23 15:06
Are you also getting a "Failed to connect" after entering the insteon hub IP and credentials?

**Comment by soloyolk** [comment] 2022-04-23 15:06
> 



> ### Feedback
> This does not appear to work:
> 
> Log into Home Assistant and add the Insteon integration. Select Insteon Hub v2 if you have a 2245-xxx or Hub V1 if you have a 2242-xxx. Follow the instructions on screen to add the integration.
> 
> You will need the IP address of the Hub which you should be able to find on your network router. See the documentation for your specific router for instructions.
> 
> If you have a Hub v2 you will need the default username and password which are printed on the bottom of the Hub
> 
> Add devices to the Hub using the instructions for [Adding Devices to the INSTEON Integration](https://www.home-assistant.io/integrations/insteon/#adding-devices-to-the-insteon-integration)
> 
> Once your devices are linked to the Hub again they will appear in Home Assistant automatically.
> 
> ### URL
> https://www.home-assistant.io/integrations/insteon/
> 
> ### Version
> 2022.4.6
> 
> ### Additional information
> _No response_

Are you also getting a "Failed to connect" after entering the insteon hub IP and credentials?

**Comment by klaasnicolaas** [comment] 2022-04-23 15:25
Closing it because duplicate of #22460

**Closed as completed by klaasnicolaas** 2022-04-23 15:25 UTC
Labels: integration: insteon
