### ISSUE TITLE
Dead end on getting energy to work

### ISSUE THREAD

**Issue by rhemkes** [home-assistant/home-assistant.github.io#19509] opened 2021-09-28 08:17 UTC
### Feedback

"Open an issue with the author of the integration and link them to" - but how? For a normal user, this is not a feasible solution. With all the fanfare around the energy dashboard, would it not have been great to inform energy integration authors beforehand, or at least provide us with an easy way to contact them?

### URL

https://www.home-assistant.io/more-info/statistics/

### Version

2021.9.7

**Comment by frenck** [comment] 2021-09-28 08:29
> "Open an issue with the author of the integration and link them to" - but how? For a normal user, this is not a feasible solution.

I'm sorry to hear you find that cumbersome, however, looking at the hundreds of issues created each week, I think we are doing fine.

> With all the fanfare around the energy dashboard, would it not have been great to inform energy integration authors

We did.

Anyways, You have submitted documentation feedback, and it is clear that this is not documentation feedback. Therefore I'm going to close this up.

If you need guidance on where to go, see:

<https://www.home-assistant.io/help>

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck

**Closed as completed by frenck** 2021-09-28 08:29 UTC
Labels: more-info

**Comment by rhemkes** [comment] 2021-09-28 08:44
Hi Frenck, thanks for your reply, but it would have been nice to be able to respond to you before you closed my question. I still feel the documentation could be a bit more eleborative on _how_ I would be able to contact the developer of the integration (Toon in my case). The fact that a lot of people created an issue does in my opinion not invalidate my experience that this is not straightforward to find from the documentation page that Home Assistant takes you to.
Regards, Roel

**Comment by frenck** [comment] 2021-09-28 08:58
Closing an issue does not limit responding. The issue is closed as we do not consider this a documentation issue.

One doesn't contact the author of an integration. See the help page on where to report an issue with Home Assistant.

In this case you'd need to report an issues in the Home Assistant core issue tracker (it will show a nice user friendly form to fill out).
