### ISSUE TITLE
ssh library error

### ISSUE THREAD

**Issue by evanworth** [home-assistant/home-assistant.github.io#1579] opened 2016-12-10 18:25 UTC
I have received this error as well as numerous others when running the AIO on a Rpi3. Here is a [link ](https://community.home-assistant.io/t/one-timer-installer-fails-on-raspberry-pi-3/7470)to others with this error. 

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fabric/network.py", line 24, in <module>
    import paramiko as ssh
  File "/usr/local/lib/python2.7/dist-packages/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 33, in <module>
    from cryptography.hazmat.backends import default_backend
ImportError: No module named cryptography.hazmat.backends

There was a problem importing our SSH library (see traceback above).
Please make sure all dependencies are installed and importable.

**Comment by fabaff** [comment] 2016-12-10 22:45
This is the issue tracker for the documentation. please report your issue at https://github.com/home-assistant/fabric-home-assistant/issues

BTW, could be a duplicate of https://github.com/home-assistant/fabric-home-assistant/issues/25

**Closed by fabaff** 2016-12-10 22:45 UTC
