### ISSUE TITLE
Why is password rule in HA reolink integration tighter then in Reolink itself?

### ISSUE THREAD

**Issue by manrot05** [home-assistant/home-assistant.github.io#34347] opened 2024-08-18 08:42 UTC
### Feedback

Hi I use the same password within the reolink app and web interface, but now since latest update to 2024.8.1 I need another password.
Password contains incompatible special character, only these characters are allowed: a-z, A-Z, 0-9 or @$*~_-+=!?.,:;'()[]

![Screenshot_20240818_103718_Home Assistant](https://github.com/user-attachments/assets/95013def-1988-4b1f-b6a8-cb79a665e07c)

WHY?

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

2024.8.2

**Comment by starkillerOG** [comment] 2024-08-20 08:40
Duplicate of https://github.com/home-assistant/home-assistant.io/issues/34199 and https://github.com/home-assistant/core/issues/123302 and a few others

See my explination here: https://github.com/home-assistant/core/issues/123302#issuecomment-2274337355

Sorry for the inconveniance of having to make a new user/change the password.

**Closed as completed by starkillerOG** 2024-08-20 08:40 UTC
Labels: integration: reolink
