### ISSUE TITLE
Tibber Sensors stops working

### ISSUE THREAD

**Issue by Velferd** [home-assistant/home-assistant.github.io#24853] opened 2022-11-07 10:07 UTC
### Feedback

I've recently installed HA on a Rasberry PI 4. The problem i'm facing is that the Tibber power sensors stops logging data usually after a day or two, the price sensor is still running. I also tried to install HA on a VMware ESXi server to monitor if the same problem occurs, and if it happens on the same time. I'm having the same issues on VMware, but not at the same timeline. I have attached screen shot from the two different platforms. 
What can I do to improve stability? 
![Screenshot from 2022-11-07 11-01-56](https://user-images.githubusercontent.com/117639081/200282603-d32f6430-1d44-465a-922b-333dc6847915.png)

![Screenshot from 2022-11-07 11-02-26](https://user-images.githubusercontent.com/117639081/200282614-1bbfebab-5e0a-44d0-ada5-47eb0011de92.png)

### URL

https://www.home-assistant.io/integrations/tibber/

### Version

2022.11.1

**Comment by Danielhiversen** [comment] 2022-11-07 13:21
Duplicate of https://github.com/home-assistant/core/issues/81037

**Closed as completed by Danielhiversen** 2022-11-07 13:21 UTC
Labels: integration: tibber
