### ISSUE TITLE
growatt integration not working

### ISSUE THREAD

**Issue by justnils** [home-assistant/home-assistant.github.io#25458] opened 2022-12-29 23:45 UTC
### Feedback

moved to other hardware with latest HAS OS Hardware.

Not able to install Growatt again.... unknown error after filling in Login Credentials.
Old Version works fine on my other system.

### URL

https://www.home-assistant.io/integrations/growatt_server

### Version

latest

**Comment by muppet3000** [comment] 2022-12-30 14:02
Duplicate of https://github.com/home-assistant/core/issues/84600 and this is the place to log errors in the documentation, not the integration itself.

**Comment by muppet3000** [comment] 2022-12-30 14:03
@home-assistant close

**Closed as completed by muppet3000** 2022-12-30 14:03 UTC
Labels: integration: growatt_server
