### ISSUE TITLE
Home Assistant:  Expected Data Source not being listed in new energy monitoring feature

### ISSUE THREAD

**Issue by matthyne** [home-assistant/home-assistant.github.io#19247] opened 2021-09-07 12:10 UTC
### Feedback

When using the SolarEdge integration with Home Assistant and trying to configure energy monitoring/dashboard most of the SolarEdge statistics entities/sources cannot be used/selected because of incorrect configuration in the SolarEdge integration

Only the sensor.solaredge_lifetime_energy entity appears to be correctly configured (not that it is particularly useful).

![image](https://user-images.githubusercontent.com/17772672/132341610-814418ee-0458-404c-954b-bb46a52131ec.png)

**See here for a description of the issue from the Home Assistant team: 

https://www.home-assistant.io/more-info/statistics/
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics**

### URL

https://www.home-assistant.io/integrations/solaredge/

### Version

2021.9.4

### Additional information

These are the sensors we would like to be able to use: 
![image](https://user-images.githubusercontent.com/17772672/132341966-ab105e21-0bb8-47e3-a7e7-d0012de11a72.png)

Screenshots of the problem(s):

![image](https://user-images.githubusercontent.com/17772672/132341230-18b14e71-86c6-443d-87a5-b98df214f554.png)
![image](https://user-images.githubusercontent.com/17772672/132341297-129e54c2-9f01-4280-97cf-54d011d308a1.png)

**Comment by ludeeus** [comment] 2021-09-07 12:11
Duplicate of https://github.com/home-assistant/core/issues/54017

**Closed as completed by ludeeus** 2021-09-07 12:11 UTC
Labels: more-info, integration: solaredge
