### ISSUE TITLE
growatt server url https://server.growatt. com not reachabkle in the integration

### ISSUE THREAD

**Issue by rtax56** [home-assistant/home-assistant.github.io#29670] opened 2023-11-02 14:53 UTC
### Feedback

growatt server url https://server.growatt. com not reachabkle in the integration

who can help ???

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2023.11.0

### Additional information

growatt server url--->  https://server.growatt. com not reachabke in the integration

there are only three other urls displayed, butnothing works for me ....

**Comment by muppet3000** [comment] 2023-11-02 15:19
This is the wrong repo to log bugs with the integrations, this is the documentation github.
That said, in the interests of assisting as much as possible: this is a duplicate of #100874.
To see the specific resolution/planned resolution look at this comment: https://github.com/home-assistant/core/issues/100874#issuecomment-1789626484

**Comment by muppet3000** [comment] 2023-11-02 15:20
@home-assistant close

**Closed as completed by muppet3000** 2023-11-02 15:20 UTC
Labels: integration: growatt_server

**Comment by rtax56** [comment] 2023-11-03 02:30
Oh! Sorry , think i did something wrong , sorry i cant code ... only cobol and 370 Assembler . WHO can help to get the Growatt Integration run , Like Beförderung ??Please advice , i am not so familiär with github , i am more or less a user only ..Regards RtaxVon meinem iPad gesendetAm 02.11.2023 um 16:20 schrieb home-assistant[bot] ***@***.***>:﻿
Closed #29670 as completed.

**Comment by rtax56** [comment] 2023-11-03 03:13
Thank you it is working fine now I followed the hoot …. Thanks a lot ;)
Rtax
