### ISSUE TITLE
Lightwave integration guide assumes too much knowledge of the reader

### ISSUE THREAD

**Issue by paulstimpson** [home-assistant/home-assistant.github.io#20685] opened 2021-12-14 00:07 UTC
### Feedback

I'm new to Home Assistant and I'm finding this particular document very frustrating. It doesn't tell me how to install the integration (It's not present in the UI) or link to a guide on how to install such integrations. It also tells me I need to put in the device numbers (e.g. R2D1) for my devices but doesn't tell me how to find the values of those device numbers and relate them to the device names

### URL

https://www.home-assistant.io/integrations/lightwave/

### Version

2021.12.1

**Comment by marcelveldt** [comment] 2021-12-14 12:47
This is one of the older (and less used) integrations that have no way yet to be setup through the UI.
You can only set it up by manually editing the yaml configuration file, which is indeed a bit more of a technical task.

Good news is that more and more integrations are available to setup with the UI.
Maybe at some point this one will follow too if the author (or any other contributor) has interest (and time) in adding UI support.

See here for some help in editing the configuration file:
https://www.home-assistant.io/docs/configuration/

I'm going to close this issue as this is not a bug in the software.
For help I'd advice you to seek support on our discord channels or the forums: https://www.home-assistant.io/help/

Good luck!

BTW: If you do manage to find out what input is needed for all configuration options, you can contribute yourself to help others [by editing the documenation](https://github.com/home-assistant/home-assistant.github.io/tree/current/source/_integrations/lightwave.markdown)

**Closed as completed by marcelveldt** 2021-12-14 12:47 UTC
Labels: integration: lightwave
