### ISSUE TITLE
Vera Controller URL Possibly Incorrect

### ISSUE THREAD

**Issue by netpoetica** [home-assistant/home-assistant.github.io#587] opened 2016-06-27 01:09 UTC
I was working through the Vera controller setup, and I noticed the provided URI in this documentation _may_ be out of date, or that it might be there is a different URL for the Vera plus. I have a Vera Plus, and the URI to access it locally on my system is `http://192.168.1.158/cmh`, whereas [the documentation](https://github.com/home-assistant/home-assistant.io/blob/master/source/_components/vera.markdown) show it as `http://192.168.1.161:3480/`

Can anyone confirm whether this documentation is up to date or needs that URL rewritten? I don't mind updating the docs, but I would hope that I am not missing something (maybe another Vera controller uses a different URI?)

If I try to use specified URI with Vera plus, I will get a barrage of issues:

```
ERROR:homeassistant.components.vera:Error communicating with Vera API
Traceback (most recent call last):
  File "/Users/KeithOMB/.pyenv/versions/3.4.4/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/KeithOMB/.pyenv/versions/3.4.4/lib/python3.4/site-packages/requests/packages/urllib3/util/connection.py", line 91, in create_connection
    raise err
  File "/Users/KeithOMB/.pyenv/versions/3.4.4/lib/python3.4/site-packages/requests/packages/urllib3/util/connection.py", line 81, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/KeithOMB/.pyenv/versions/3.4.4/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/Users/KeithOMB/.pyenv/versions/3.4.4/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 362, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/KeithOMB/.pyenv/versions/3.4.4/lib/python3.4/http/client.py", line 1137, in request
    self._send_request(method, url, body, headers)
  File "/Users/KeithOMB/.pyenv/versions/3.4.4/lib/python3.4/http/client.py", line 1182, in _send_request
    self.endheaders(body)
  File "/Users/KeithOMB/.pyenv/versions/3.4.4/lib/python3.4/http/client.py", line 1133, in endheaders
    self._send_output(message_body)
  File "/Users/KeithOMB/.pyenv/versions/3.4.4/lib/python3.4/http/client.py", line 963, in _send_output
    self.send(msg)
  File "/Users/KeithOMB/.pyenv/versions/3.4.4/lib/python3.4/http/client.py", line 898, in send
    self.connect()
  File "/Users/KeithOMB/.pyenv/versions/3.4.4/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 167, in connect
    conn = self._new_conn()
  File "/Users/KeithOMB/.pyenv/versions/3.4.4/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 151, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x10f00d438>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/KeithOMB/.pyenv/versions/3.4.4/lib/python3.4/site-packages/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/Users/KeithOMB/.pyenv/versions/3.4.4/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 623, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/KeithOMB/.pyenv/versions/3.4.4/lib/python3.4/site-packages/requests/packages/urllib3/util/retry.py", line 281, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.1.161', port=3480): Max retries exceeded with url: //data_request?id=sdata (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10f00d438>: Failed to establish a new connection: [Errno 61] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/KeithOMB/.pyenv/versions/3.4.4/lib/python3.4/site-packages/homeassistant/components/vera.py", line 68, in setup
    list(DEVICE_CATEGORIES.keys()))
  File "/Users/KeithOMB/.homeassistant/deps/pyvera/__init__.py", line 88, in get_devices
    self.get_simple_devices_info()
  File "/Users/KeithOMB/.homeassistant/deps/pyvera/__init__.py", line 63, in get_simple_devices_info
    j = requests.get(simple_request_url).json()
  File "/Users/KeithOMB/.pyenv/versions/3.4.4/lib/python3.4/site-packages/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/KeithOMB/.pyenv/versions/3.4.4/lib/python3.4/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/KeithOMB/.pyenv/versions/3.4.4/lib/python3.4/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/KeithOMB/.pyenv/versions/3.4.4/lib/python3.4/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/Users/KeithOMB/.pyenv/versions/3.4.4/lib/python3.4/site-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.161', port=3480): Max retries exceeded with url: //data_request?id=sdata (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10f00d438>: Failed to establish a new connection: [Errno 61] Connection refused',))
ERROR:homeassistant.bootstrap:component vera failed to initialize
```

Which appears to say that it could not connect to Vera or initialize. I do get other errors when using the /cmh URI but I believe that issue would be for another repo, not the .io website.

**Comment by balloob** [comment] 2016-06-27 04:56
CC @pavoni @rhooper

**Comment by rhooper** [comment] 2016-06-27 05:05
I have a Vera Lite and the URI for the API is indeed on port 3480.  Vera UI 7, Version 1.7.760.  I can't comment on other hardware versions or firmware versions.

When I access the UI, I go to :80/cmh, though.

I can't find any settings to enable/disable port 3480, so you might want to go google at the vera forums http://forum.micasaverde.com/

**Comment by pavoni** [comment] 2016-06-27 09:18
I think the API and UI are on different ports, so I'd expect your API to be on `http://192.168.1.158:3480`

Did you try that?

**Comment by netpoetica** [comment] 2016-07-08 02:53
@pavoni I can confirm that the UI does live at `/cmh`, however I cannot confirm that there is any RESTful API running at port 3480. Do you have a `curl` I could use that will confirm the API is running? Maybe the API is not turned on by default? It's interesting, in the Vera support pages I can't find a single article that even discusses the API's existence. The only [article](http://support.getvera.com/customer/en/portal/articles/1840699-to-veraedge-from-ui5-on-veralite-vera-2-or-vera-3?b_id=712) I found that even makes note of this API at port 3480 is in regards to an old system monitor plugin.

**Comment by fabaff** [comment] 2016-09-09 08:16
Do we need to adjust the documentation? Or the code? Or can we close this?

**Comment by netpoetica** [comment] 2016-09-09 12:23
@fabaff I have been gone for a month away from home, but I do plan on trying this again very soon. Give me a couple of days before closing, I will aim to get results this weekend. Thanks!

**Comment by technicalpickles** [comment] 2016-09-22 02:53
I recently got a Vera Plus. I can confirm the documentation works as is accessing port 3480. I remember being a bit confused initially with what the host should be, until I realized 3480 was a magic port.

Maybe instead of having a full URL, it'd be a lot simpler for users to just specify a hostname/IP, and assume the port is 3480?

**Comment by Landrash** [comment] 2016-11-23 13:30
Closing this since documentation seems to be correct and if not it can be reopened.

**Closed by Landrash** 2016-11-23 13:30 UTC
Labels: question

**Comment by djrobx** [comment] 2017-03-04 20:48
If I recall there's a "secure my Vera" setting that blocks LAN access to the API.   You'll want to turn that off.  Your security is fine as long as your LAN is secure.
