### ISSUE TITLE
Add category tag "Energy" to the GreenEye Monitor (GEM) integration

### ISSUE THREAD

**Issue by robot256** [home-assistant/home-assistant.github.io#18741] opened 2021-08-04 18:02 UTC
### Feedback

The GreenEye Monitor is primarily a 32-channel AC power measurement device, that has some temperature and pulse inputs as well.  Since it is used to measure home electrical energy use (similar to Sense and TED5000), it would be helpful to include it in the "Energy" category.

### URL

https://www.home-assistant.io/integrations/greeneye_monitor/

### Version

2021.8.0

**Comment by evandepol** [comment] 2021-08-11 13:28
I have two of these in my home and would love to get this to work. Is anybody already working on adding this?

**Comment by robot256** [comment] 2021-08-11 13:43
Oh, is the reason the Energy tag isn't applied because the GEM integration doesn't work with the new HASS "Energy" functionality? I'm new to the ecosystem and still learning all the terms.

**Comment by frenck** [comment] 2021-08-11 13:46
@evandepol This is an documentation issue, not related to any functionality. Thanks 👍 

@robot256 No, categories are not related to features provided by Home Assistant. This suggestion is valid.

**Comment by jkeljo** [comment] 2021-08-11 16:57
@evandepol to add to what @frenck says, the GEM support in homeassistant is fully functional and should work for multiple monitors. (I only have one in my home, though, so if you encounter any problems feel free to open an issue in the main homeassistant repo.)

@robot256 the commit you created looks reasonable to me, want to close this issue and make a pull request of it so @frenck or another maintainer can merge it in?

**Comment by evandepol** [comment] 2021-08-11 17:30
Hi @jkeljo thanks for the response. Both monitors are working fine with HA (they are forwarded from a "dashbox" device, same packet format as the RS323 connect - Net-32-Bin), and i am seeing power (W) and voltage readings in HA. I must be missing something then on how to have them show up in the new Energy feature of HA. I have tried setting up the Riemann Integration ("platform:integration") sensor from this, but so far isn't working for me.

So yea, this could very well be just a documentation issue, or me being stupid, or both. Do you have this working with the new Energy dashboard? If so, then the problem is clearly somewhere on my end (and it would be helpful to know that for triage). Can you confirm it works well for you with the Energy dash?

**Comment by robot256** [comment] 2021-08-11 17:52
@evandepol I'd suggest moving this to a new issue (and I'll probably jump in as soon as I get my HA set up).  The GEM includes internal integration and can report both Watts and Watt-Hours.  Are they both ingested by HA, or do you only get access to Watts?  It would be more accurate to feed the Watt-Hours into the Energy feature, like it were a regular utility meter.  Hopefully the built-in system can account for when the GEM integrated meter rolls over (this happened to mine after a year or two).

**Comment by evandepol** [comment] 2021-08-11 18:12
> @evandepol I'd suggest moving this to a new issue 

Agree, i didn't mean to hijack this issue (i misunderstood what was meant by "tag" -- it's documentation). I will do some more digging in the meantime.

**Comment by jkeljo** [comment] 2021-08-11 18:13
Yeah, I agree on a new issue (and in the homeassistant repo; this repo is just the docs). I haven’t upgraded my installation in a while, so I don’t know about the new energy stuff.

**Comment by klaasnicolaas** [comment] 2021-08-11 22:25
Closing this issue, PR is merged 😉

**Closed as completed by klaasnicolaas** 2021-08-11 22:25 UTC
Labels: integration: greeneye_monitor
