### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by ivanhgg** [home-assistant/home-assistant.github.io#20202] opened 2021-11-07 20:04 UTC
### Feedback

No data is being received from this integration.

### URL

https://www.home-assistant.io/integrations/pvpc_hourly_pricing/

### Version

2021.11.1

**Comment by azogue** [comment] 2021-11-08 07:58
Hi there @ivanhgg  👋

Seems like you wanted to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please submit issues with Home Assistant integrations in the issue tracker here:

https://github.com/home-assistant/core/issues

Thanks! 👍

BTW, this one looks like a duplicate of #20126 (also misplaced here), and it was already registered (and fixed) in HA Core (issue: https://github.com/home-assistant/core/issues/58986, PR with fix: https://github.com/home-assistant/core/pull/59008), so **it should work in v2021.11.1** (but not in v2021.11.0). 

If it is not working for you in 2021.11.1, please submit a new issue in https://github.com/home-assistant/core/issues with a little more detail than 'broken' 😜

**Closed as completed by azogue** 2021-11-08 07:58 UTC
Labels: integration: pvpc_hourly_pricing
