### ISSUE TITLE
Growatt integration not working anymore?

### ISSUE THREAD

**Issue by OleMadsen1971** [home-assistant/home-assistant.github.io#23105] opened 2022-06-14 22:16 UTC
### Feedback

Suddenly today Growatt interface stopped working.
I have remove Growatt integration and tried to add it again with no luck.

 When I enter the "Enter your Growatt information", with the right username and password it just returns "Unknown error occurred".

I can log into http://server.growatt.com/ with no problems and see my data.
Anyone have the same problems?

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2022.6.5

**Comment by muppet3000** [comment] 2022-06-14 22:19
Duplicate of: https://github.com/home-assistant/core/issues/71577

Please follow the status there and no more posts here.

**Closed as completed** 2022-06-15 08:57 UTC
Labels: integration: growatt_server
