### ISSUE TITLE
where to add the txt record?

### ISSUE THREAD

**Issue by sevorl** [home-assistant/home-assistant.github.io#17509] opened 2021-04-18 10:29 UTC
### Feedback

I got stuck here:
https://www.home-assistant.io/integrations/html5/#verify-your-domain - DuckDNS
3. Add the TXT record to your DNS. If you use DuckDNS, use the format:

Where do I need to add this? I have no idea 

### URL

https://www.home-assistant.io/integrations/html5/#verify-your-domain

### Version

2021.4.4

**Comment by milanmeu** [comment] 2021-04-18 14:32
Open the provided URL in the browser and fill in your details.
```
https://www.duckdns.org/update?domains={your Duck DNS subdomain (the part before .duckdns.org)}&token={your Duck DNS token}&txt={google-site-verification record}
```

Example:
```
https://www.duckdns.org/update?domains=my-hass&token=23hbdk8jdsjd-2b3b-4e57-9jdof4-hdk84bdtis0&txt=abc123
```

**Comment by milanmeu** [comment] 2021-04-18 14:41
I'll help you here but please use the [community forum](https://community.home-assistant.io/) or the [Home Assistant Discord](https://www.home-assistant.io/join-chat) for support 😃.
Feel free to ask for more info or close the issue if the problem is resolved.

**Comment by frenck** [comment] 2021-04-19 11:43
Hi there @sevorl!

As suggested above, this is more of a support question with either DuckDNS (or their documentation) or maybe our community can help.

Closing this issue from our end. Nevertheless, thanks for taking the time to provide feedback 👍 

../Frenck 🚂

**Closed as completed by frenck** 2021-04-19 11:43 UTC
Labels: integration: html5
