### ISSUE TITLE
Setup wizard errors

### ISSUE THREAD

**Issue by Gr0p3r** [home-assistant/home-assistant.github.io#23406] opened 2022-07-15 15:14 UTC
### Feedback

I do not have Home Assistant Cloud, so I want to use it with my external IP. The documentation says this is possible. 
When going though the setup wizard, after adding Home Connect integration
- it prompts for credentials. 
- I add my credentials from the developer app
- It redirects to https://api.home-connect.com/security/oauth/authorize?response_type=code&client_id=[CLIENTID]&redirect_uri=**https://my.home-assistant.io/redirect/oauth**&state=[Code]
- This errors, of course
> {
>   "error": "unauthorized_client",
>   "error_description": "client or redirection URI not authorized",
>   "state": "Code"
> }
- I have then added the correct external URI to the address line, which will take me to the login page.
- I log in with my Home Connect credentials and then it allows me to Authorize 
- I am redirected back to home assistant
- the integration setup wizard resumes "Loading next steps for Home Connect", but just pops up a with "Error" and an OK button. 

So, it may be two things, fix the setup wizard to allow for the input of the external IP / domain name of the Home Assistant instance to be passed to the API URL. And then fix whatever nondescript error is coming up with the return. 

Cheers.

### URL

https://www.home-assistant.io/integrations/home_connect/

### Version

2022.7.5

### Additional information

I have a loom recording of it if it helps. but I didnt want to add it here as it contains some PII.

**Comment by DavidMStraub** [comment] 2022-07-15 18:29
Hi, it looks like you didn't follow the documentation step by step. Did you register the app in the Home Connect developer portal?

**Comment by Gr0p3r** [comment] 2022-07-16 00:31
Sure did.
________________________________

I am fundraising for the Cancer Coucil with the Shitbox Rally. Click here to get more information about the Rally or below donate.

DEAN ELLIOTT - 
DIRECTOR
08 9756 7273
***@***.***
www.elliotts.tech
Dunsborough - Map
Busselton - Map
ConfigurationSoftware
​SupportHardware
​RepairsHelpdesk
Onsite
​SupportRemote
​Support24H
​Support
Maintenance
Consultant
​Services
Managed
​Services
This email is for the use of the intended recipient only and may contain confidential information.  Any unauthorised use of the contents is expressly prohibited.  If you receive this email in error, please contact us, and delete all copies of the email.

**Comment by IncByteLC** [comment] 2022-07-17 03:38
Same issue there. Don't understand why https://my.home-assistant.io/redirect/oauth is here if I am using own domain

**Comment by frenck** [comment] 2022-07-17 12:00
> Don't understand why [my.home-assistant.io/redirect/oauth](https://my.home-assistant.io/redirect/oauth) is here if I am using own domain

Because you have My Home Assistant (`my`) enabled (possibly via `default_config`).

**Comment by frenck** [comment] 2022-07-17 12:23
I have two Home Connect capable appliances (but not using them with Home Assistant yet). Thus this was an excellent case to test the manual.

The instructions worked fine, are correct and up to date:

<img width="262" alt="image" src="https://user-images.githubusercontent.com/195327/179397980-cd11bb06-e0b3-456a-9ee7-2e877354a0b9.png">

For completeness, this is the application I created in the Home Connect developer portal:

![CleanShot 2022-07-17 at 14 17 27](https://user-images.githubusercontent.com/195327/179397943-2e6c699f-74ae-44ff-8d99-1889d7fdf2e1.png)

I have been able to reproduce `"error_description": "client or redirection URI not authorized",`, this happens when the application isn't configured correctly @ the Home Connect developers portal (incorrect "Redirect URI"; make sure it is exactly as described in the Home Assistant documentation).

Closing the documentation feedback issue on this end, as the existing documentation is correct.

../Frenck

**Closed as not planned by frenck** 2022-07-17 12:23 UTC
Labels: integration: home_connect

**Comment by Gr0p3r** [comment] 2022-07-18 01:32
> 

This was the answer to my question. When the "default_config" was removed from my configuration.yaml file, it all worked as expected. Maybe you should add a note to the article to mention that "if you are not using home assistant cloud, then remove the default_config or check that it is not there, or the redirection will fail"

**Comment by frenck** [comment] 2022-07-18 06:49
@Gr0p3r that is already in the documentation.

Please note, this is not related too or requires Home Assistant Cloud at all. This is open and freely available for everyone.
