### ISSUE TITLE
Purple Air instructions not working

### ISSUE THREAD

**Issue by csadams** [home-assistant/home-assistant.github.io#30289] opened 2023-12-11 23:16 UTC
### Feedback

Looks like the Purple Air integration is not working via the instructions provided... it returns an error about the API requiring payment, even though it comes with 1M "points".  

In more detail... 
I'm just setting up my first Home Assistant here on a Raspberry Pi, and trying to integrate with Purple Air.  I have my own sensor (which I would prefer to connect to directly), but if I understand correctly, the integration reaches out to Purple Air's cloud service and finds nearby sensors.  Anyway, I followed the instructions, got a Purple Air API Key (Read), and am showing 1M "points" in the developer interface.  I entered my API key into Home Assistant, and submitted my location with the default 5km search radius.  It responds with red text saying "Unexpected Error", and then in my logs I see the following: 

> Logger: homeassistant.components.purpleair
Source: components/purpleair/config_flow.py:176
Integration: PurpleAir (documentation, issues)
First occurred: 15:04:11 (1 occurrences)
Last logged: 15:04:11
PurpleAir error while getting nearby sensors: Error while querying https://api.purpleair.com/v1/sensors?fields=name,latitude,longitude&nwlat=37.90903677476684&nwlng=-122.34139332334166&selat=37.819204725233156&selng=-122.22760532108677: Payment is required to make this api call.

It appears to indicated that payment is required, when I believe there are 1M credits in my Purple Air API account.  Did something change?  If so, please update the instructions (or at least insert a warning), so folks like me don't waste time trying to get this to work.  Thanks! 

### URL

https://www.home-assistant.io/integrations/purpleair/

### Version

2023.12.1

**Comment by bachya** [comment] 2023-12-18 02:46
Duplicate of https://github.com/home-assistant/core/issues/93428.

**Closed as completed by bachya** 2023-12-18 02:46 UTC
Labels: integration: purpleair
