### ISSUE TITLE
Plugwise stretch v2

### ISSUE THREAD

**Issue by Frans1949** [home-assistant/home-assistant.github.io#23019] opened 2022-06-06 14:49 UTC
### Feedback

I get the message " can't connect" after a while
Password is correct.
Is there a solution for a not.experient HA user?

### URL

https://www.home-assistant.io/integrations/plugwise/

### Version

2022.6.2

**Comment by bouwew** [comment] 2022-06-06 15:00
Hi @Frans1949 I will try to help you with this problem.

But first, please close this issue, it's in the wrong place :)
And create a new issue here: https://github.com/home-assistant/core/issues

**Closed as completed** 2022-06-06 15:30 UTC
Labels: integration: plugwise

**Comment by bouwew** [comment] 2022-06-07 14:09
@Frans1949 the issue is no longer present?
I did not see a new issue appear in the HA Core issue list?

**Comment by Frans1949** [comment] 2022-06-07 15:23
I (tried?) To make a New ticket, but perhaps something went wrong

Op di 7 jun. 2022 16:09 schreef Bouwe Westerdijk ***@***.***>:
