### ISSUE TITLE
PostNL integration not working

### ISSUE THREAD

**Issue by Skottelbraai** [home-assistant/home-assistant.github.io#11359] opened 2019-12-04 09:55 UTC
Hello,
sinds the last update the PostNL integration to Hassio is not working anymore.

Here is the log file.

`
Logboekdetails ( ERROR )
Wed Dec 04 2019 10:44:00 GMT+0100 (CET)

Can't connect to the PostNL webservice
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/postnl_api/postnl_api.py", line 179, in _request_login
    data = response.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/postnl/sensor.py", line 46, in setup_platform
    api = PostNL_API(username, password)
  File "/usr/local/lib/python3.7/site-packages/postnl_api/postnl_api.py", line 57, in __init__
    self._request_login()
  File "/usr/local/lib/python3.7/site-packages/postnl_api/postnl_api.py", line 182, in _request_login
    raise (UnauthorizedException())
postnl_api.postnl_api.UnauthorizedException 

`

**Comment by frenck** [comment] 2019-12-04 10:43
Duplicate of home-assistant/home-assistant#29002

There is also an alert active for this integration:

<https://alerts.home-assistant.io/#postnl.markdown>

**Closed as completed by frenck** 2019-12-04 10:43 UTC
