### ISSUE TITLE
Not getting data from sensor

### ISSUE THREAD

**Issue by florisre** [home-assistant/home-assistant.github.io#19304] opened 2021-09-11 22:57 UTC
### Feedback

I set the sensor up as described in the documentation. I am running the hass-image on a Raspberry Pi, according to this documentation it should work. I have entered the correct MAC address. The sensors show up on my panel and are even forwarded to HomeKit, but they don't read any data. Also, the Bluetooth-icon in my device's display does not ever light up.

[This](https://www.banggood.com/3PCS-XIAOMI-Mijia-BT-Bluetooth-Thermometer-2-Wireless-Smart-Electric-Digital-Hygrometer-Thermometer-Work-with-Mijia-APP-p-1595118.html) is the device I own. It is different to the one linked in this article, but I was assuming that due to similar model names etc. it should work anyway.

### URL

https://www.home-assistant.io/integrations/mitemp_bt/

### Version

2021.9.5

**Comment by ludeeus** [comment] 2021-09-12 06:24
Duplicate of https://github.com/home-assistant/core/issues/46803 (Which is opened in the correct place)

**Closed as completed by ludeeus** 2021-09-12 06:24 UTC
Labels: integration: mitemp_bt
