### ISSUE TITLE
UniFi update Protect 2.0.0-beta.7 crash the integration

### ISSUE THREAD

**Issue by stivenpl79** [home-assistant/home-assistant.github.io#22744] opened 2022-05-13 23:44 UTC
### Feedback

This update Protect 2.0.0-beta.7 crash the integration :(
Probably this happen because UniFi add the "package detection"
This is nightmare for me :(
Can You update the integration ?
PLEASE HELP !

Adam Bujak

### URL

https://www.home-assistant.io/integrations/unifiprotect/

### Version

2022.5.4

**Comment by AngellusMortis** [comment] 2022-05-13 23:48
Wrong repo (should be on [core repo](https://github.com/home-assistant/core)), duplicate of https://github.com/home-assistant/core/issues/71841 and invalid. [As stated in the documentation](https://www.home-assistant.io/integrations/unifiprotect#software-support), 2.0.0-beta7 is not supported.

> Since UniFi Protect has its own release cycle, you should only upgrade UniFi Protect after the next Home Assistant release comes out to ensure the new version is fully supported.

You should only _not_ use UniFi Protect Early Access channels unless you are using HA Dev branch and you should _not_ update UniFi Protect unless HA has updated first with support. Otherwise, you may be left with a broke integration.

**Comment by stivenpl79** [comment] 2022-05-13 23:49
Logger: homeassistant.config_entries
Source: components/unifiprotect/data.py:94 
First occurred: 00:43:20 (1 occurrences) 
Last logged: 00:43:20

Error setting up entry UDM-Pro for unifiprotect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/unifiprotect/__init__.py", line 81, in async_setup_entry
    await data_service.async_setup()
  File "/usr/src/homeassistant/homeassistant/components/unifiprotect/data.py", line 74, in async_setup
    await self.async_refresh()
  File "/usr/src/homeassistant/homeassistant/components/unifiprotect/data.py", line 94, in async_refresh
    updates = await self.api.update(force=force)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/api.py", line 507, in update
    self._bootstrap = await self.get_bootstrap()
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/api.py", line 676, in get_bootstrap
    return Bootstrap.from_unifi_dict(**data, api=self)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 111, in from_unifi_dict
    data = cls.unifi_dict_to_dict(data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/bootstrap.py", line 152, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 343, in unifi_dict_to_dict
    data[key] = cls._clean_protect_obj_dict(data[key], unifi_dicts[key], api)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 288, in _clean_protect_obj_dict
    items[key] = cls._clean_protect_obj(value, klass, api)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 272, in _clean_protect_obj
    return klass.unifi_dict_to_dict(data=data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/devices.py", line 699, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 617, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 333, in unifi_dict_to_dict
    data[key] = cls._clean_protect_obj(data[key], unifi_objs[key], api)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 272, in _clean_protect_obj
    return klass.unifi_dict_to_dict(data=data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 326, in unifi_dict_to_dict
    data[key] = convert_unifi_data(data[key], cls.__fields__[key])
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/utils.py", line 160, in convert_unifi_data
    value = [convert_unifi_data(v, field) for v in value]
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/utils.py", line 160, in <listcomp>
    value = [convert_unifi_data(v, field) for v in value]
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/utils.py", line 176, in convert_unifi_data
    value = field.type_(value)
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'package' is not a valid SmartDetectObjectType

**Comment by stivenpl79** [comment] 2022-05-14 00:49
thanks ! :)

**Closed as completed** 2022-05-14 01:02 UTC
Labels: integration: unifiprotect

**Comment by AngellusMortis** [comment] 2022-05-14 01:12
Added a section to the docs about how to downgrade. https://www.home-assistant.io/integrations/unifiprotect/#downgrading-unifi-protect

**Comment by stivenpl79** [comment] 2022-05-14 07:30
Doesn't work for me.
When i put a ssh and install 2.0.0 bet 5 a get a information:

"E: Version '2.0.0-beta.5' for 'unifi-protect' was not found"

I uninstall protect application on my UDM PRO, disable Early Access and i install old version 1.21.6
And i Home Assistant when i remove my integration and install i have the same error"
"ValueError: 'package' is not a valid SmartDetectObjectType"

**Comment by briis** [comment] 2022-05-14 08:30
Replace the `-` with a `~`. So that the version is `2.0.0~beta.5`

Then it will work.
