### ISSUE TITLE
2 processors required with Virtualbox. Default 1 won't boot

### ISSUE THREAD

**Issue by rakoivun** [home-assistant/home-assistant.github.io#24260] opened 2022-09-27 16:28 UTC
### Feedback

Processor needs to be set to 2 in Virtualbox. If 1 the image won't boot.

See also
https://community.home-assistant.io/t/virtualbox-haos-ova-8-4-vdi-wont-boot/447485

Seen on haos_ova-9.0

### URL

https://www.home-assistant.io/installation/windows/

### Version

2022.9.7

**Comment by frenck** [comment] 2022-09-27 17:11
Sound more like a bug? Have you reported it at the operating system issue tracker?

**Comment by rakoivun** [comment] 2022-09-27 19:10
I thought it was just a documentation issue rather than bug. I will check if I find right place to report it.
Now reported.

**Comment by frenck** [comment] 2022-09-28 06:07
Alright! Going to close this issue on this end in the mean time, until it confirmed this is either bug or intended functionality.

../Frenck

**Closed as not planned by frenck** 2022-09-28 06:07 UTC
Labels: installation
