### ISSUE TITLE
No integration page for 'Home Energy Management'

### ISSUE THREAD

**Issue by DCSBL** [home-assistant/home-assistant.github.io#19367] opened 2021-09-17 09:28 UTC
### Feedback

Users [can't find](https://community.home-assistant.io/t/energy-dashboard-not-showing-up/327340) that `default_config:` of `energy:` needs to be added to configuration.yaml. There is no technical documentation/integration page available for the Home Energy Management.

I can't think of other information to add to an integration page other than 'how to enable' as most information is available at https://www.home-assistant.io/docs/energy/. But there is not a single bit of technical information on that page so I think it will be out of place. As alternative we maybe add it to the FAQ?

### URL

https://www.home-assistant.io/docs/energy/

### Version

2021.9.6

**Comment by ludeeus** [comment] 2021-09-17 09:32
Duplicate of https://github.com/home-assistant/home-assistant.io/issues/18905

**Closed as completed by ludeeus** 2021-09-17 09:32 UTC
