### ISSUE TITLE
Tuya re-authentication issue after 2024.2 update

### ISSUE THREAD

**Issue by tonyviljoen** [home-assistant/home-assistant.github.io#31300] opened 2024-02-08 04:24 UTC
### Feedback

Once updated to 2024.2 core system, required to re-authenticate Tuya. Once the code is inserted the next step to scan QR code does not show the QR code, rather an error message that the hex color code does not exist. 

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2024.2.0

**Comment by frenck** [comment] 2024-02-08 07:51
This is a duplicate of https://github.com/home-assistant/frontend/issues/19722

It seems to be caused by custom themes. Please temporarily switch the default Home Assistant theme to re-authenticate.

../Frenck

**Closed as not planned by frenck** 2024-02-08 07:51 UTC
Labels: integration: tuya
