### ISSUE TITLE
Record service is not supported

### ISSUE THREAD

**Issue by horvathgergo** [home-assistant/home-assistant.github.io#22397] opened 2022-04-15 10:15 UTC
### Feedback

As the integration is set up as an MJPEG camera it does not support record service (service: camera.record), thus we are not able to start and download the recording directly to HA local folder

### URL

https://www.home-assistant.io/integrations/android_ip_webcam/

### Version

2022.4.3

**Comment by frenck** [comment] 2022-04-16 07:25
That is correct. I'm not really sure what the reason for this feedback is?

../Frenck

**Comment by horvathgergo** [comment] 2022-04-16 07:47
Sorry. I thought it’s a bug that you are not aware of or an unintentional limit on the android ip webcam integration features.

**Comment by frenck** [comment] 2022-04-16 08:03
Its not a bug, not all features are supported by all entities. E.g., not all light bulbs support colors either :)

**Comment by horvathgergo** [comment] 2022-04-16 08:23
I see your point. My initial thought about this issue was that it (perhaps) can be feasible by some kind of conversion (mjpeg to mp4, h264), but maybe you are right and it is impossible like in your bulb example

**Comment by frenck** [comment] 2022-05-16 14:49
Closing this, as it's not an issue but part of the fundamental workings of Home Assistant.

**Closed as completed by frenck** 2022-05-16 14:49 UTC
Labels: integration: android_ip_webcam
