### ISSUE TITLE
Coinbase has new api key types

### ISSUE THREAD

**Issue by Fotali** [home-assistant/home-assistant.github.io#32889] opened 2024-05-22 16:03 UTC
### Feedback

This wonderful little integration has stopped working.  Coinbase has transitioned to a new api key type.  (Not sure if that is the reason)

### URL

https://www.home-assistant.io/integrations/coinbase/

### Version

2024.5.4

**Comment by TomBrien** [comment] 2024-05-22 16:25
Hi, this is a duplicate of home-assistant/core#116282. There is a fix in home-assistant/core#116345 which migrates to the new API format and is waiting for review.

**Closed as completed by TomBrien** 2024-05-22 16:25 UTC
Labels: integration: coinbase

**Comment by Fotali** [comment] 2024-05-23 01:20
Thanks for your hard work on this.   This is why HA is so good!
