### ISSUE TITLE
Nest does not retry when unavailable in some conditions

### ISSUE THREAD

**Issue by ctenersight** [home-assistant/home-assistant.github.io#27125] opened 2023-04-24 18:54 UTC
### Feedback

Based on this issue: https://github.com/home-assistant/core/issues/90166

I have a feeling this is more common than it seems and people are manually just reloading the integration.

Short of handling this automatically, please include the instructions to setup the script automation.

1. Create your API token
2. Add commands for cli or steps for Postman to query: `http://<homeassistant url>/api/config/config_entries/entry`
3. Search for Nest in the output and grab the entry_id
4. Update the following, replace `<token>` with above API token, replace `<nest_entry_id>` with above entry_id and add to the configuration.yaml: 
```
shell_command:
  nest_reload: "/usr/bin/curl -X 'POST' -H 'authorization: Bearer <token>' http://localhost:8123/api/config/config_entries/entry/<nest_entry_id>/reload"
```
6. Restart Home Assistant
7. In Home Assistant UI goto Settings, Devices and Services
8. Go to Entities
9. Type Climate in the search and copy the Entity ID's
10. In Home Assistant UI goto Settings, Automations, Scripts and Add Script
11. Click the 3 dots in the top right and select Edit in YAML
12. In the following YAML replace the `<Entity ID>` with the above and add additional rows if you have more than one. Then paste it into the window. 
```
alias: Nest Reload
sequence:
  - wait_for_trigger:
      - platform: state
        entity_id:
          - <Entity Id>
        to: unavailable
        for:
          hours: 0
          minutes: 2
          seconds: 0
  - service: script.nest_reload
    data: {}
mode: single
icon: mdi:google
```
14. Click save script

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2023.4.6

**Comment by allenporter** [comment] 2023-04-24 19:23
Hi,
Can we restate the issue we are trying to solve here? I asked for clarification in the other issue as well and then they ended up closing it.

In general a power outage shouldn't require reinstalling anything, yes. I don't know what would be specific to nest here either. In general, nest should follow home assistants best practices for failure recovery and if there is a gap we can fix it.

**Comment by allenporter** [comment] 2023-04-24 19:25
I think what you're saying is you home assistant to retry failed integrations indefinitely if they can't be set up properly initially?

**Comment by Tonguc-Endem** [comment] 2023-06-05 14:56
In my case, it takes a while before my network becomes operational after an power outage.  I also have to turn on the internet/network devices in a specific order.  first I have to turn on my Cable modem. Then 60 seconds later, when the modem becomes connected to the service, I turn on the router. then, when the internet becomes operational 30 seconds after the router is turned on, I turn on the ethernet switch and the two PoE access points and also HA is powered.  I do these with timers so that it is not a big deal. 

However, during a short outage Home Assistant keeps running since it has a Waveshare Raspberry Pi UPS HAT and it gracefully shutsd down the HA Pi4 when it needs to.

Additionaly all my wifi devices such as nest thermostat, nest doorbell, nest hub max etc become powered before my network becomes operational, which takes about 90~seconds.

After a not-so-short outage, only my spotify integration and nest integration requires reload.

**Comment by allenporter** [comment] 2023-06-05 14:59
Is nest your only cloud device? 

This seems like a board problem for any cloud service where your network is not up before home assistant starts since nest is using the default retry behavior here for initializing a cloud service.

I'm not deflecting, but making sure we understand the problem and the right level of solutions. (E.g. can propose a new retry behavior for all cloud services)

**Comment by Tonguc-Endem** [comment] 2023-06-05 15:03
Yes, you're right.  but it is not.  All the rest of the cloud integrations always work without a problem.
I have:
- August
- Google Assistant SDK
- Google Assistant
- HACS
- Meteorologisk institutt (Met.no)

**Comment by allenporter** [comment] 2023-06-05 15:33
Ok so some of those are polling integrations and this is a push integration. The integration polls once at start to setup the subscription, then it is pushed information form there. If it can't setup the subscription then home assistant won't ask it to retry.

Thanks that's helpful to better understand the problem.

**Comment by Tonguc-Endem** [comment] 2023-06-05 18:24
That's exactly what I thought was going on.  Either internet or dns or ssl is not completely working before nest/spotify tries to do something at start and it does not try again.

**Comment by allenporter** [comment] 2023-06-05 19:07
I was just asking around and folks said it should retry setup forever. Can you tell me what the error is in the logs?

**Comment by allenporter** [comment] 2023-06-06 01:14
I see in the other bug the exception was:
```
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0xffff68b80fa0>: Failed to establish a new connection: [Errno -3] Try again
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url: /oauth2/v4/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff68b80fa0>: Failed to establish a new connection: [Errno -3] Try again')) 
```

Is that also what you see? In this example, its not actually catching and throwing the correct error, so that could explain it.

**Comment by allenporter** [comment] 2023-06-06 01:27
When I try to reproduce this with `tcpkill` I get a different error message and it retries fine, not "Retrying in background":
```
Logger: homeassistant.config_entries
Source: config_entries.py:429
First occurred: 6:25:41 PM (1 occurrences)
Last logged: 6:25:41 PM

Config entry 'Woodgreen' for nest integration not ready yet: Device manager error: Error connecting to API: [Errno 104] Connection reset by peer; Retrying in background
```

So it would be really helpful to have the exact error message seen...

**Comment by Tonguc-Endem** [comment] 2023-06-07 09:32
I'll post the log output here when I can recreate to problem.  I will have to shutdown HA and cut the power to the whole house and wait some time to make sure the problem would occur.  Maybe it has something to do with the internet provider or the building cable repeater too I don't know but I'm sure that it always happens after a not-so-short power outage and doesn't always happen if I cut the power myself or reboot the HA.

**Comment by Tonguc-Endem** [comment] 2023-06-07 09:34
Also I have to disable the above API method.  I'm not even sure if that works yet too.

**Comment by Tonguc-Endem** [comment] 2023-06-09 11:29
ok, I was able to re-create the problem.
I turned off HA and kept it off for about 15 minutes.
Again, Spotify and Nest needs reloading. Everything else loaded fine.

<img src="https://github.com/home-assistant/home-assistant.io/assets/24412484/d30504a4-9fa1-42c9-b640-db0367c46912" width="400"  />

Here is the log for Nest:
```
2023-06-07 22:24:58.997 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Türksan for nest
File "/usr/src/homeassistant/homeassistant/components/nest/__init__.py", line 213, in async_setup_entry
File "/usr/local/lib/python3.10/site-packages/google_nest_sdm/google_nest_subscriber.py", line 415, in start_async
File "/usr/local/lib/python3.10/site-packages/google_nest_sdm/google_nest_subscriber.py", line 260, in async_new_subscriber
File "/usr/local/lib/python3.10/site-packages/google_nest_sdm/google_nest_subscriber.py", line 283, in _new_subscriber
File "/usr/local/lib/python3.10/site-packages/google_nest_sdm/google_nest_subscriber.py", line 271, in _refresh_creds
```

And here is the log for Spotify if you're interested.
```
2023-06-07 22:25:15.851 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry ToR for spotify
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/me/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7b3a3be0>: Failed to establish a new connection: [Errno -3] Try again'))
File "/usr/src/homeassistant/homeassistant/components/spotify/__init__.py", line 85, in async_setup_entry
current_user = await hass.async_add_executor_job(spotify.me)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/me/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7b3a3be0>: Failed to establish a new connection: [Errno -3] Try again'))
2023-06-07 22:25:15.890 ERROR (SyncWorker_4) [custom_components.spotcast.helpers] spotify integration not found
```

**Comment by Tonguc-Endem** [comment] 2023-06-09 11:37
I will keep it in this state for a while in case if you'll have a request.

**Comment by allenporter** [comment] 2023-06-09 12:53
The logs for nest look truncated. Can you include a few more lines that include the exception that is raised?

Otherwise this is exactly what we need...

**Comment by Tonguc-Endem** [comment] 2023-06-09 16:08
that's the whole thing actually.
there is also some stuff about zigpy but that shows up there because search finds 'nest' in Zo'***neSt***'atus.Alarm_1
```
2023-06-07 22:24:58.997 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Türksan for nest
File "/usr/src/homeassistant/homeassistant/components/nest/__init__.py", line 213, in async_setup_entry
File "/usr/local/lib/python3.10/site-packages/google_nest_sdm/google_nest_subscriber.py", line 415, in start_async
File "/usr/local/lib/python3.10/site-packages/google_nest_sdm/google_nest_subscriber.py", line 260, in async_new_subscriber
File "/usr/local/lib/python3.10/site-packages/google_nest_sdm/google_nest_subscriber.py", line 283, in _new_subscriber
File "/usr/local/lib/python3.10/site-packages/google_nest_sdm/google_nest_subscriber.py", line 271, in _refresh_creds
2023-06-07 22:26:46.202 DEBUG (MainThread) [zigpy.zcl] [0x9B09:1:0x0500] Decoded ZCL frame: IasZone:status_change_notification(zone_status=<ZoneStatus.Alarm_1: 1>, extended_status=<bitmap8.0: 0>, zone_id=0, delay=0)
2023-06-07 22:26:46.203 DEBUG (MainThread) [zigpy.zcl] [0x9B09:1:0x0500] Received command 0x00 (TSN 243): status_change_notification(zone_status=<ZoneStatus.Alarm_1: 1>, extended_status=<bitmap8.0: 0>, zone_id=0, delay=0)
2023-06-07 22:31:15.322 DEBUG (MainThread) [zigpy.zcl] [0x9B09:1:0x0500] Decoded ZCL frame: IasZone:status_change_notification(zone_status=<ZoneStatus.0: 0>, extended_status=<bitmap8.0: 0>, zone_id=0, delay=0)
```

**Comment by Tonguc-Endem** [comment] 2023-06-09 17:29
@ctenersight, I think there might be a problem with your script.
don't you want to name your script `script.nest_reload` and call the shell command with `service:shell_command.nest_reload` as I showed below?
It seems like your code calls itself.

```
alias: Nest Reload
sequence:
  - wait_for_trigger:
      - platform: state
        entity_id:
          - <Entity Id>
        to: unavailable
        for:
          hours: 0
          minutes: 2
          seconds: 0
  - service: shell_command.nest_reload
    data: {}
mode: single
icon: mdi:google
```

By the way the script does not trigger since it does not actually change to unavailable. it is always unavailable (from the start/boot) so there is no change in entitiy state and thus no trigger.

**Comment by Tonguc-Endem** [comment] 2023-06-09 20:46
ok I found a working solution for the above API method to trigger the shell_command to reload of the Nest integration if it is unavailable at boot time.  The problem is regular entity state based trigger does not work since there is no state change because it just starts as 'unavailable' so I'm using  the homeassistant platform with start event.

here is the working code for an automation.

Create the shell_command as described at top and use this automation.
I also created the same automation for Spotify and that is working fine too now.


```
alias: Reload Integration (Nest)
trigger:
  - platform: homeassistant
    event: start
condition:
  - condition: template
    value_template: >-
      {% if states.camera.apartment_door is defined and states.climate.fancoil
      is defined %}
        {{states.climate.fancoil.state=="unavailable" and states.camera.apartment_door.state=="unavailable"}}
      {%- endif -%}
action:
  - service: shell_command.nest_reload
    data: {}
mode: single

```

**Comment by ctenersight** [comment] 2023-06-09 21:06
@Tonguc-Endem I just tested this out but it fails trying to save with the following error:

Message malformed: extra keys not allowed @ data['trigger']

**Comment by Tonguc-Endem** [comment] 2023-06-09 23:43
@ctenersight could you post your code plesae?

**Comment by ctenersight** [comment] 2023-06-10 02:20
@Tonguc-Endem 

```
alias: Reload Integration Nest
trigger:
  - platform: homeassistant
    event: start
condition:
  - condition: template
    value_template: >-
      {% if states.camera.front_door is defined and states.climate.hallway
      is defined %}
        {{states.climate.hallway.state=="unavailable" and states.camera.front_door.state=="unavailable"}}
      {%- endif -%}
action:
  - service: shell_command.nest_reload
    data: {}
mode: single

**Comment by allenporter** [comment] 2023-06-10 02:40
If you are using search I assume that only finds log lines with the error in the name. The stack trace may not have the word nest on every line. Please give me the full stack trace and we can solve this issue for good instead of talking about hacky scripts:)

**Comment by ctenersight** [comment] 2023-06-10 02:44
@allenporter next time it fails I'll grab the log output for you. Do I need to change logging levels or will it always output the stack trace?

**Comment by allenporter** [comment] 2023-06-10 05:07
It should be there always

**Comment by Tonguc-Endem** [comment] 2023-06-10 10:50
@ctenersight `extra keys not allowed` is usually about how the template part in yaml was written, it is probably an extra charatcter or space or something.  trying it in developer tools -> template editor should show you the source of the problem.

@allenporter, you're right sorry. Proper log is below:

About the hacky script, please understand that this issue started happening right after when google migrated away from the out-of-band OAuth authentication flow around october 2022.  Before that, a similar problem was solved again previously when this problem occured again before this last issue as well.  This is the first time I found a working hacky script that can fix all these kinds of problems which applies not only to nest but to other integrations as well.  I ofcourse want the problem to be properly solved and when it's solved I'll disable the reload-automation.  But I'll keep it around to use with spotify and for the next time when this problem arises again ;-)

Also I'm not sure if this is related but I'm using Nginx Proxy Manager with DuckDNS fyi.
Also, I just turned on HA without waiting after shutdown and was able to recreate to problem.  However the problem always happens after HA shutsdown.  Apparently due to my UPS I was not experiencing this problem with every power outage.

here is the new log:
```
Logger: homeassistant.config_entries
Source: components/nest/__init__.py:213
First occurred: 1:34:36 PM (1 occurrences)
Last logged: 1:34:36 PM

Error setting up entry Türksan for nest
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f5c65a860>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url: /oauth2/v4/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5c65a860>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/google/auth/transport/requests.py", line 193, in __call__
    response = self.session.request(
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url: /oauth2/v4/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5c65a860>: Failed to establish a new connection: [Errno -3] Try again'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/nest/__init__.py", line 213, in async_setup_entry
    await subscriber.start_async()
  File "/usr/local/lib/python3.10/site-packages/google_nest_sdm/google_nest_subscriber.py", line 415, in start_async
    await self._subscriber_factory.async_new_subscriber(
  File "/usr/local/lib/python3.10/site-packages/google_nest_sdm/google_nest_subscriber.py", line 260, in async_new_subscriber
    return await loop.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/google_nest_sdm/google_nest_subscriber.py", line 283, in _new_subscriber
    creds = self._refresh_creds(creds)
  File "/usr/local/lib/python3.10/site-packages/google_nest_sdm/google_nest_subscriber.py", line 271, in _refresh_creds
    creds.refresh(Request())
  File "/usr/local/lib/python3.10/site-packages/google/oauth2/credentials.py", line 335, in refresh
    ) = reauth.refresh_grant(
  File "/usr/local/lib/python3.10/site-packages/google/oauth2/reauth.py", line 324, in refresh_grant
    response_status_ok, response_data, retryable_error = _client._token_endpoint_request_no_throw(
  File "/usr/local/lib/python3.10/site-packages/google/oauth2/_client.py", line 213, in _token_endpoint_request_no_throw
    request_succeeded, response_data, retryable_error = _perform_request()
  File "/usr/local/lib/python3.10/site-packages/google/oauth2/_client.py", line 189, in _perform_request
    response = request(
  File "/usr/local/lib/python3.10/site-packages/google/auth/transport/requests.py", line 199, in __call__
    six.raise_from(new_exc, caught_exc)
  File "<string>", line 3, in raise_from
google.auth.exceptions.TransportError: HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url: /oauth2/v4/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5c65a860>: Failed to establish a new connection: [Errno -3] Try again'))

```

**Comment by Tonguc-Endem** [comment] 2023-06-10 11:48
@ctenersight, I pasted your code into an empty automation and it saved without a problem.  very interesting...
I'm trying to find the solution when I experienced a similar problem about a year ago.

**Comment by allenporter** [comment] 2023-06-10 15:27
I didn't realize this issue was filed in the documentation component. I am closing this issue and moving it back to the core component issue: https://github.com/home-assistant/core/issues/90166

**Closed as completed** 2023-06-20 14:37 UTC
Labels: integration: nest
