### ISSUE TITLE
Wave Enhance support

### ISSUE THREAD

**Issue by mnmac2000** [home-assistant/home-assistant.github.io#35343] opened 2024-10-23 01:20 UTC
### Feedback

Hello,

The integration works great.  Is there a timeline to add support for the new Wave Enhance?

### URL

https://www.home-assistant.io/integrations/airthings_ble/

### Version

2024.10.3

**Comment by LaStrada** [comment] 2024-10-23 10:29
Hi! I have something that works locally, but need a few bug fixes, som for example auto discovery. Will close this, since this is a feature request and not a bug report.

Edit: will try to be done within a month

**Comment by LaStrada** [comment] 2024-10-23 10:30
@home-assistant close

**Closed as completed by LaStrada** 2024-10-23 10:30 UTC
Labels: integration: airthings_ble
