### ISSUE TITLE
Cannot enter separate morning and evening damping factors.

### ISSUE THREAD

**Issue by alexanderhoet** [home-assistant/home-assistant.github.io#26170] opened 2023-02-08 18:13 UTC
### Feedback

According to the documentation is should be possible to enter separate damping factors for the morning and evening.
It is not possible to enter this in the configuration field, whenever I try to enter two values, separated by a comma, it formats the value as a decimal, or just deletes the second value.

It would be nice to be able to use this feature as I have shadow on my panels in the evening, but not in the morning.

### URL

https://www.home-assistant.io/integrations/forecast_solar/

### Version

2023.2.3

**Comment by klaasnicolaas** [comment] 2023-02-08 18:16
Duplicate of https://github.com/home-assistant/core/issues/86885

**Closed as not planned by klaasnicolaas** 2023-02-08 18:16 UTC
Labels: integration: forecast_solar
