### ISSUE TITLE
Not vorking media player CMUS & MPD

### ISSUE THREAD

**Issue by fuzzznet** [home-assistant/home-assistant.github.io#22303] opened 2022-04-08 12:00 UTC
### Feedback

Home Assistant 2022.4.1 CORE | Ubuntu 22.04 5.15.0-25-generic | Python 3.10.4

Hey!
After installing Home Assistant, I can’t start MPD media player and CMUS =(
Errors below:
---------------MPD---------------
Logger: homeassistant.components.media_player
Source: components/mpd/media_player.py:141
mpd: Error on device update!

Traceback (most recent call last): File “/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py”, line 431, in _async_add_entity await entity.async_device_update(warning=False) File “/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py”, line 735, in async_device_update await task File “/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/mpd/media_player.py”, line 184, in async_update await self._connect() File “/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/mpd/media_player.py”, line 141, in _connect await self._client.connect(self.server, self.port) File “/srv/homeassistant/lib/python3.10/site-packages/mpd/asyncio.py”, line 195, in connect r, w = await asyncio.open_connection(host, port, loop=loop) File “/usr/lib/python3.10/asyncio/streams.py”, line 47, in open_connection transport, _ = await loop.create_connection( TypeError: BaseEventLoop.create_connection() got an unexpected keyword argument ‘loop’

-----------CMUS------------

Logger: homeassistant.components.media_player
Source: components/cmus/media_player.py:101
Error while setting up cmus platform for media_player

Traceback (most recent call last): File “/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py”, line 249, in _async_setup_platform await asyncio.shield(task) File “/usr/lib/python3.10/concurrent/futures/thread.py”, line 58, in run result = self.fn(*self.args, **self.kwargs) File “/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/cmus/media_player.py”, line 78, in setup_platform cmus_remote.connect() File “/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/cmus/media_player.py”, line 101, in connect self.cmus = remote.PyCmus( File “/srv/homeassistant/lib/python3.10/site-packages/pycmus/remote.py”, line 78, in init raise exceptions.ConfigurationError( pycmus.exceptions.ConfigurationError: A configuration error occured Details: Unable to connect to server 192.168.1.97

### URL

https://www.home-assistant.io/integrations/cmus/

### Version

2022.4.1

**Comment by frenck** [comment] 2022-04-08 14:34
duplicate of #22304

**Closed as completed by frenck** 2022-04-08 14:34 UTC
Labels: integration: cmus
