### ISSUE TITLE
Flashing with Etcher results in faulty DNS behavior. 

### ISSUE THREAD

**Issue by DamianosS** [home-assistant/home-assistant.github.io#28706] opened 2023-08-28 06:56 UTC
### Feedback

Several users encountered DNS related problems after incomplete  Balena Etcher flashing. 
When using USBimager as an alternative we didn't have problems so far.

Maybe this is worthwhile to be mentioned in the dcoumentation.

You can find documentation and comments regarding that issue in the community forum:
[[Flashing hard drive get stuck at 31% (balena fetcher)](https://community.home-assistant.io/t/flashing-hard-drive-get-stuck-at-31-balena-fetcher/604336)](https://community.home-assistant.io/t/flashing-hard-drive-get-stuck-at-31-balena-fetcher/604336)](https://community.home-assistant.io/t/flashing-hard-drive-get-stuck-at-31-balena-fetcher/604336/44)

### URL

https://www.home-assistant.io/installation/generic-x86-64/

### Version

2023.8.4

**Comment by DamianosS** [comment] 2023-11-02 15:52
The issue still persists regarding the documentation, suggesting the use of Balena Etcher. 
Since the described way lead to errors and questionable behaviour, the documentation should be updated.
I'm more than happy to support to this, just tell me what to do.

**Comment by k8gg** [comment] 2023-11-02 22:48
Not stalled.

**Comment by seelem02** [comment] 2023-11-19 20:04
I had this exact issue.  Flashing got to 32% for me, but as HAOS appeared to boot fine, it looked like the flashing completed, and perhaps it was just a graphics issue that meant the screen wasn't updating.  In fact it absolutely didn't complete.  The most noticeable issue was DNS not working properly, but adding DNS servers didn't fix it.
The problem appears to be with Balena Etcher.  I tried multiple Live OS's, and various methods.  In the end, following this guide actually worked:

https://community.home-assistant.io/t/how-to-install-home-assistant-on-generic-x86-64-using-live-os/567210

Note that this guide seems to install a different (older) version of Balena Etcher, and despite a number of errors during install, it works fine and writes the image to the disk without any errors.

Definitely worth mentioning it in the guide that if you do not see Balena Etcher flash to 100% and verify, then it likely hasn't worked, even though the OS may boot and look ok.  I suspect there are quite a few people out there with slightly knackered installs due to this one.

**Comment by agners** [comment] 2023-11-24 16:14
@DamianosS I was able to reproduce the problem and this is really very curious :sweat_smile: 

So I think for one, it just seems that balenaEtcher is not a good fit for Ubuntu 22.04, at least when using the Live version. It requires libfuse2, and then crashes as it seems :see_no_evil: 

The outcome of the whole situation is really interesting, it seems that balenaEtcher corrupted the CoreDNS binary inside the DNS plug-in on Home Assistant, which lead to those DNS issues people have reported :exploding_head: .

In any case, It think the better approach here is to use the built-in "Disks" utility of Ubuntu. The main reason the guide is using balenaEtcher is since it is available on all platform (in case people flash it from a host using USB-to-S-ATA adapter) and it supports verify (however, that is moot point since it crashes :see_no_evil: ). So this means we have to split the guides in two separate flows.

USBimager does look interesting. What don't like too much is that it doesn't support AppImage and uses x11 by default on Linux.

**Comment by DamianosS** [comment] 2023-11-25 22:33
@agners, I see your point. However, since the documentation suggests Ubuntu Live as the jump-off point, and Balena Etcher gives userd a hard time, shouldn’t it suggest the USBimager alternative?

**Comment by agners** [comment] 2023-11-28 15:54
@DamianosS USBImager would probably work too, but Ubuntu has a built-in tool called Disks which even can handle xz images directly. Initially we did not use that tool because it adds another flow to document. But given the problems, I think this is the best option as it doesn't require installing anything additionally.

@c0ffeeca7 created a PR adjusting the documentation in #29997.

**Comment by DamianosS** [comment] 2023-11-28 17:25
Agree. If there’s a build-in tool, so the user wouldn’t need to download anything, it’s of course the preferable way! Thanks a lot, @agners!

**Comment by c0ffeeca7** [comment] 2023-11-28 17:51
Resolved by #29997

**Closed as completed by c0ffeeca7** 2023-11-28 17:51 UTC
Labels: installation, balena
