### ISSUE TITLE
EcoVacs  t50pro is not working

### ISSUE THREAD

**Issue by kmsg0000** [home-assistant/home-assistant.github.io#35272] opened 2024-10-18 00:43 UTC
### Feedback

Cleaning and other operation buttons do not work I'm attaching the file
[config_entry-ecovacs-01JAE9PZ13J0N3PQXZBXRQ4DBC1.json](https://github.com/user-attachments/files/17426123/config_entry-ecovacs-01JAE9PZ13J0N3PQXZBXRQ4DBC1.json)

### URL

https://www.home-assistant.io/integrations/ecovacs/

### Version

2024.10.2

**Comment by mib1185** [comment] 2024-10-18 06:51
- duplicate of your own report #35266

**Closed as not planned by mib1185** 2024-10-18 06:51 UTC
Labels: integration: ecovacs
