### ISSUE TITLE
Apple asking for verification every 30 minutes

### ISSUE THREAD

**Issue by ifuchs** [home-assistant/home-assistant.github.io#28029] opened 2023-07-02 01:24 UTC
### Feedback

Apple is sending a 6 digit number to icloud connected devices to verify the Home Assistant login very 30 minutes. Is there a way to stop this (other than uninstalling the integration).

### URL

https://www.home-assistant.io/integrations/icloud/

### Version

2023.6.3

**Comment by frenck** [comment] 2023-07-03 12:21
Closing as a duplicate of https://github.com/home-assistant/core/issues/46308

**Closed as not planned by frenck** 2023-07-03 12:21 UTC
Labels: integration: icloud
