### ISSUE TITLE
not able to sign up new account on Veritone.

### ISSUE THREAD

**Issue by linshuwen5716** [home-assistant/home-assistant.github.io#30753] opened 2024-01-10 01:00 UTC
### Feedback

not able to sign up new account on Veritone. It seems that there is no such option in their website for personal usage anymore.

### URL

https://www.home-assistant.io/integrations/facebox/

### Version

2024.1.2

**Comment by klaasnicolaas** [comment] 2024-01-10 01:42
Duplicate of #30737

**Closed as not planned by klaasnicolaas** 2024-01-10 01:42 UTC
Labels: integration: facebox
