### ISSUE TITLE
DC Solar Systems

### ISSUE THREAD

**Issue by andy5211d** [home-assistant/home-assistant.github.io#19330] opened 2021-09-13 13:54 UTC
### Feedback

Just a few points about the Energy pages.  I notice that there is often a reference to energy monitors which are purely AC measuring devices such as Shelly EM or CT Clamp Sensor, and will not work on DC solar systems.   The older solar systems may have purely DC solar power generation, which feeds the batteries and the AC inverter all at DC, 12V or 24V.  Thus measuring the energy cannot be undertaken by current clamps or similar devices.  Measuring the power into a battery will only be a DC measurement unless the 'battery' has its own built in electronics and is thus not really a 'battery', in the traditional sense.  

Would be good if HA accepted power into and out of a battery as a + or - value as most DC current measuring devices will report power this way (+/- amps).  I convert this current from the Victron battery monitor to an instantaneous power value by multiplication with the current battery voltage which will vary significantly dependent upon charge level.   

### URL

https://www.home-assistant.io/docs/energy/solar-panels/

### Version

2021.9.5

**Comment by ludeeus** [comment] 2021-09-13 15:17
Duplicate of https://github.com/home-assistant/core/issues/55974

**Closed as completed by ludeeus** 2021-09-13 15:17 UTC

**Comment by andy5211d** [comment] 2021-09-13 21:46
OK, yes I agree its a duplicate.  I was concerned that people may think they can monitor DC Power/Energy using current clamps  Don't get me wrong the new Energy monitoring is fantastic, a great start.  Now I need to sort out how to make the energy flow diagram work....
