### ISSUE TITLE
Credit generation tool missing contributors #4703

### ISSUE THREAD

**Issue by hoangcv18** [home-assistant/home-assistant.github.io#7644] opened 2018-11-26 07:59 UTC
The tool that generates the credits page doesn't seem to be including all contributors properly. For example, I contributed for the first time in the 0.61.0 release, but still have not been included in the list after several regenerations of the page.

I am unsure if others are missing as well.

**Comment by fabaff** [comment] 2018-11-26 10:30
Duplicate of #4703

**Closed as completed by fabaff** 2018-11-26 10:30 UTC
