### ISSUE TITLE
Supported Tarriffs

### ISSUE THREAD

**Issue by tre4b** [home-assistant/home-assistant.github.io#25283] opened 2022-12-14 11:58 UTC
### Feedback

The text for configuring a Utility Meter Helper:  says : "A list of tariffs, leave empty if only a single tariff is needed."

I need multiple tarriffs but cannot figure out what values to put in here to make it acknowledge tariffs.  I have tried many, to me logical, options. More information is needed here as without this being entered you can only support a single tarriff.   I then tried to creat it with nothing in this field (i.e. a single tarriff).   The idea was to then modify the code by hand.

I could not find the code to edit it and the helper itself would not allow me to change most of the information here.   Currently I have not been able to setup this meter to have multiple tariffs.   I can do it using manual methods I believe, however I felt feeding back here was a good thing to do to try and improve the experience for users.

### URL

/config/helpers

### Version

Home Assistant 2022.12.5 Supervisor 2022.11.2 Operating System 9.4 Frontend 20221213.0 - latest

**Comment by lyricnz** [comment] 2022-12-15 21:40
May be duplicate of https://github.com/home-assistant/frontend/issues/14703

**Comment by frenck** [comment] 2022-12-16 08:28
As per above, there is an frontend issue open for this. Please follow the above-listed issue on the progress of it.

Thanks! 👍 

../Frenck

**Closed as not planned by frenck** 2022-12-16 08:28 UTC
