### ISSUE TITLE
//Number

### ISSUE THREAD

**Issue by VdR1960** [home-assistant/home-assistant.github.io#22650] opened 2022-05-06 15:11 UTC
### Feedback

Can't make this work. Need '# Example configuration.yaml entry'. Cannot configure in same way as //Input_number. Log error tells me I need a 'platform' ???

### URL

https://www.home-assistant.io/integrations/number/

### Version

2022.5.1

**Comment by Shulyaka** [comment] 2022-05-07 07:00
Duplicate of #22593

**Closed as completed** 2022-05-16 13:06 UTC
Labels: integration: number
