### ISSUE TITLE
Unstrusted information meaningless

### ISSUE THREAD

**Issue by whocarezpt** [home-assistant/home-assistant.github.io#21958] opened 2022-03-10 16:16 UTC
### Feedback

This information is meaningless unless some more detail is added:

[](https://www.home-assistant.io/more-info/unhealthy/untrusted#the-solution)The issue

Home Assistant detected untrusted code. It looks like someone/something injected not signed images or code into your Home Assistant system.
The solution

Please make sure your network is not affected by an intruder. We recommend reinstalling your installation and make sure only authorized persons have access to your instance.

### URL

https://www.home-assistant.io/more-info/unhealthy/untrusted/

### Version

2022.3.3

**Comment by frenck** [comment] 2022-03-10 17:42
Hi there @whocarezpt 👋 

Thanks for the feedback, but what do you suggest? As, to me, it sounds pretty clear.

../Frenck

**Comment by whocarezpt** [comment] 2022-03-10 18:21
Hi @frenck 
In this case was a false alarm, after rebooting message disapeared.

I suggested showing message from log witt erro.

Thanks

**Comment by frenck** [comment] 2022-03-10 18:24
> I suggested showing message from log witt error.

The only way to get to this page, is via the error. So, what would adding the error to the page add?

../Frenck

**Comment by nicolas-guichard** [comment] 2022-03-10 20:54
I just ran into that too: an “untrusted code” error that disappeared with a reboot and I guess a supervisor update.
From what I understand that check was disabled in the latest update with home-assistant/supervisor#3504 because it is currently broken. The help page should have a note about that.

Even then you get an error like “system unhealthy ([show details](https://www.home-assistant.io/more-info/unhealthy/untrusted/))” and clicking “show details” redirects to that web page that doesn't actually give any details but is more of a documentation for the error.
What I would have expected instead is something like “image checksum mismatched, expected ... got ...”, or even better a list of files that differ from what's expected. If at all possible, I'd like a way to know what untrusted code ran on my system!
If there is no way to actually have more details at the moment, then the help page should probably tell that.

Cheers

**Comment by frenck** [comment] 2022-03-11 09:59
> The help page should have a note about that.

Documentation does not incorporate bugs... bugs happen and are not predictable...
If we knew which bugs to expect, we could fix them 🤷 

I'm totally clueless on what you expect to happen or change to our existing documentation.

**Comment by nicolas-guichard** [comment] 2022-03-11 15:06
> Documentation does not incorporate bugs... bugs happen and are not predictable...
> If we knew which bugs to expect, we could fix them :shrug:

IIUC that issue is known and predictable and will affect everyone running supervisor 2022.02.0 (when CAS was introduced) to 2022.03.2. The workaround is even labeled as a “breaking change” in the 2022.03.3 release notes ⇒ it should be documented.
Right now people get directed to a “your server has been hacked, you should reinstall” page for no good reason.

If I didn't correctly understand the issue whocarezpt and I faced, and it actually happens in rare edge cases only, then yeah it doesn't need to be mentioned.

> I'm totally clueless on what you expect to happen or change to our existing documentation.

1. (at least) An explanation of what the health check checks for (container image signatures?), that it depends on an external service (CodeNotary CAS), and what false positives/negatives it might have.
2. (extra) Guidance on how to check what untrusted content is on the server.
3. (disputed) Acknowledging the current issue, it's a security false alarm (adding eg. “Note: diagnostic unreliable between 2022.02.0 and 2022.03.2 and disabled in 2022.03.3. Don't actually lose 1 hour trying to understand how an intruder might have accessed your server and reinstalling everything and instead just update the supervisor.”).

What I actually expected “show details” to do initially was to display a popup of some sort telling me what is wrong on my specific setup, instead of redirecting to home-assistant.io. Currently it's more of a “what does this mean?” than a “show details”.
Admittedly this is not an issue with the documentation on home-assistant.io anymore, it turns more into a feature request for the web UI.

**Comment by frenck** [comment] 2022-03-12 10:55
> IIUC that issue is known and predictable and will affect everyone running supervisor 2022.02.0 (when CAS was introduced) to 2022.03.2. The workaround is even labeled as a “breaking change” in the 2022.03.3 release notes ⇒ it should be documented.

You understood wrongly.

> (at least) An explanation of what the health check checks for (container image signatures?), that it depends on an external service (CodeNotary CAS), and what false positives/negatives it might have.

It does not depend on the failure of the third-party service, that is what is understood wrongly and why I do not agree. As said before, we experience a bug as well (besides the outage). It should not have resulted in this state of unsupported. Lessons are learned, bugs are being fixed to provide it getting in this state incorrectly for the future.

> Right now people get directed to a “your server has been hacked, you should reinstall” page for no good reason.

Yeah, that sucked. But again, that should not have happened and was not the design/functionality as intended (but bugged).

> What I actually expected “show details” to do initially was to display a popup of some sort telling me what is wrong on my specific setup, instead of redirecting to home-assistant.io. Currently it's more of a “what does this mean?” than a “show details”.

There is nothing more specific. We choose to document these things centrally for those cases.

> Admittedly this is not an issue with the documentation on home-assistant.io anymore, it turns more into a feature request for the web UI.

Please use our community forums for requesting new features.

I'll go ahead and close this documentation feedback, as all of this is caused / based on a bug that should not have occurred in the first place.

Thanks for being willing to provide feedback 👍 

../Frenck

**Closed as completed by frenck** 2022-03-12 10:55 UTC
Labels: more-info

**Comment by nicolas-guichard** [comment] 2022-03-12 14:02
> (at least) An explanation of what the health check checks for (container image signatures?), that it depends on an external service (CodeNotary CAS), and what false positives/negatives it might have.

Even outside the recent breakage, this still applies. This bit of documentation should explain or link to a documentation explaining what is checked for and how.
I mean something like “Since 2021.5, HA checks the integrity of container images using CodeNotary services.”.

> that should not have happened and was not the design/functionality as intended

Is there a place where the intended design is documented? Linking to that would be great too.
