### ISSUE TITLE
Install Home Assistant Core: sqlalchemy missing?

### ISSUE THREAD

**Issue by TheDeadEndLink** [home-assistant/home-assistant.github.io#23755] opened 2022-08-13 14:32 UTC
### Feedback

I followed the Core installation guide and hass failed as the last step with a missing module.

Is it possible that 
pip install sqlalchemy fnvhash
is missing in this step-by-step instruction?

This thread mentioned that line (in another context, but it helped me in my clean installation too)
https://community.home-assistant.io/t/2022-8-0-completely-breaks-home-assistant/446984/14

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2022.8.4

**Comment by klaasnicolaas** [comment] 2022-08-13 21:56
Duplicate of #23741

**Closed as completed by klaasnicolaas** 2022-08-13 21:56 UTC
Labels: installation
