### ISSUE TITLE
Problem update supervisor 2024.11.3

### ISSUE THREAD

**Issue by derBremser** [home-assistant/home-assistant.github.io#35702] opened 2024-11-11 13:34 UTC
### Feedback

The system is not able to update the system. Is there any solution?
Thanks.

### URL

https://www.home-assistant.io/more-info/unhealthy/supervisor/

### Version

2024.11.3

### Additional information

that's the message:
Die Aktion update/install konnte nicht ausgeführt werden. Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=2024.11.3&fromImage=ghcr.io%2Fhome-assistant%2Faarch64-hassio-supervisor&platform=linux%2Farm64: Internal Server Error ("toomanyrequests: retry-after: 392.109µs, allowed: 44000/minute")

**Comment by Imnotcreativesoicantthinkofaname** [comment] 2024-11-11 13:45
Exactly the same Issue here. 
2024.11.2 -> 2024.11.3
manual updating using the command line with su update got me the same error.
Die Aktion update/install konnte nicht ausgeführt werden. Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")

Claude says i need to chill a day after discussing and sharing some other errors lol: (translated from German)
Since the error continues to occur despite a longer waiting time and we have already tried several things:

A 404 means ‘not found’
A 500 with ‘toomanyrequests’ is a server error
Switching between these errors indicates a problem with the repository

Honest recommendation:
Just wait until tomorrow. This looks very much like a temporary problem on the Home Assistant/GitHub Container Registry side. If a repository server has problems, there is little we can do on the client side.
If you absolutely have to do something NOW, the only other option would be a complete re-setup of the VM - but that would be a lot more work than waiting until tomorrow.

**Comment by Imnotcreativesoicantthinkofaname** [comment] 2024-11-11 15:26
![grafik](https://github.com/user-attachments/assets/e2884989-cf70-4d43-a99f-b5eca0cbf172)

Jetzt ist die Meldung weg und es wird keine neue Version mehr angeboten

**Comment by klaasnicolaas** [comment] 2024-11-11 16:07
Duplicate of: https://github.com/home-assistant/supervisor/issues/5405

**Closed as not planned by klaasnicolaas** 2024-11-11 16:07 UTC
Labels: more-info
