### ISSUE TITLE
No energy data on the demo.

### ISSUE THREAD

**Issue by Roeland54** [home-assistant/home-assistant.github.io#22893] opened 2022-05-26 06:45 UTC
### Feedback

The energy dashboard on demo.home-assistant.io is not showing any data.

### URL

https://demo.home-assistant.io/#/energy

**Comment by frenck** [comment] 2022-05-30 10:47
duplicate of https://github.com/home-assistant/frontend/issues/12500

**Closed as completed by frenck** 2022-05-30 10:47 UTC
