### ISSUE TITLE
Error Login

### ISSUE THREAD

**Issue by iEddie-cmd** [home-assistant/home-assistant.github.io#29742] opened 2023-11-07 10:59 UTC
### Feedback

Cant Login anymore. get Ungültige Authentifizierung

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2023.11.1

**Comment by muppet3000** [comment] 2023-11-07 21:09
Wrong repo - this is the documentation repo.

However, this is a duplicate of https://github.com/home-assistant/core/issues/100874.
I recommend reading this comment: https://github.com/home-assistant/core/issues/100874#issuecomment-1789626484 for the most recent update.

This comment provides a really comprehensive list of alternatives as well: https://github.com/home-assistant/core/issues/100874#issuecomment-1792347970

**Comment by muppet3000** [comment] 2023-11-07 21:09
@home-assistant close

**Closed as completed by muppet3000** 2023-11-07 21:09 UTC
Labels: integration: growatt_server
