### ISSUE TITLE
New integration is missing thermostats

### ISSUE THREAD

**Issue by BobLoblaw06** [home-assistant/home-assistant.github.io#18789] opened 2021-08-06 04:21 UTC
### Feedback

I updated to HA Core and that must have updated to the new HW TCC integration. My house has 5 thermostats and only one of them is showing up under the new integration. I disabled\removed\reinstalled the integration with no success. I reverted back to a snapshot using the old yaml configuration and it is working again.

### URL

https://www.home-assistant.io/integrations/honeywell/

### Version

2021.8.1

**Comment by spraguej248** [comment] 2021-08-08 03:11
Same problem for me.  I have three thermostats.  Since the last HA update it pulls in the configuration into the GUI installation section and only setup one thermostat.  I tried adding adding more with the GUI integration, deleting the integration and adding it manually.  Nothing I do will pull up all three thermostats.  Had to revert back to the last HA 2021.7.

**Comment by rdfurman** [comment] 2021-08-08 03:34
Duplicate of https://github.com/home-assistant/core/issues/53981

**Comment by frenck** [comment] 2021-08-09 12:12
Closing as duplicate (also, this report is reported as documentation feedback).

**Closed as completed by frenck** 2021-08-09 12:12 UTC
Labels: integration: honeywell
