### ISSUE TITLE
Tuya intergation not full support Smart Socket

### ISSUE THREAD

**Issue by KoryIII** [home-assistant/home-assistant.github.io#19988] opened 2021-10-26 14:19 UTC
### Feedback

The integration does not fully support outlet control.
You can turn on / off the light, but you cannot turn it on / off.
Consumption cannot be viewed.

Thanks!

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.10.6

### Additional information

Product Name: Smart Socket
Product Category: dj

[
  {
    "code": "switch_led",
    "value": false
  },
  {
    "code": "bright_value",
    "value": 180
  },
  {
    "code": "work_mode",
    "value": "colour"
  },
  {
    "code": "colour_data",
    "value": {
      "h": 0,
      "s": 255,
      "v": 255
    }
  },
  {
    "code": "scene_data",
    "value": {
      "h": 0,
      "s": 0,
      "v": 0
    }
  },
  {
    "code": "flash_scene_1",
    "value": {
      "bright": 255,
      "frequency": 80,
      "hsv": [
        {
          "h": 120,
          "s": 255,
          "v": 255
        }
      ],
      "temperature": 255
    }
  },
  {
    "code": "flash_scene_2",
    "value": {
      "bright": 255,
      "frequency": 128,
      "hsv": [
        {
          "h": 0,
          "s": 255,
          "v": 255
        },
        {
          "h": 120,
          "s": 255,
          "v": 255
        },
        {
          "h": 240,
          "s": 255,
          "v": 255
        },
        {
          "h": 0,
          "s": 0,
          "v": 0
        },
        {
          "h": 0,
          "s": 0,
          "v": 0
        },
        {
          "h": 0,
          "s": 0,
          "v": 0
        }
      ],
      "temperature": 255
    }
  },
  {
    "code": "flash_scene_3",
    "value": {
      "bright": 255,
      "frequency": 80,
      "hsv": [
        {
          "h": 0,
          "s": 255,
          "v": 255
        }
      ],
      "temperature": 255
    }
  },
  {
    "code": "flash_scene_4",
    "value": {
      "bright": 255,
      "frequency": 5,
      "hsv": [
        {
          "h": 0,
          "s": 255,
          "v": 255
        },
        {
          "h": 120,
          "s": 255,
          "v": 255
        },
        {
          "h": 60,
          "s": 255,
          "v": 255
        },
        {
          "h": 300,
          "s": 255,
          "v": 255
        },
        {
          "h": 240,
          "s": 255,
          "v": 255
        },
        {
          "h": 0,
          "s": 0,
          "v": 0
        }
      ],
      "temperature": 255
    }
  },
  {
    "code": "switch",
    "value": false
  },
  {
    "code": "countdown_1",
    "value": 0
  }
]

**Comment by frenck** [comment] 2021-10-26 14:33
This has been fixed in dev and will be part of Home Assistant 2021.11

Additionally, please note you have submitted documentation feedback (not a bug report).

**Closed as completed by frenck** 2021-10-26 14:33 UTC
Labels: integration: tuya
