### ISSUE TITLE
Reolink IP NVR/camera - character % not allowed

### ISSUE THREAD

**Issue by JJANOUSEK1** [home-assistant/home-assistant.github.io#34277] opened 2024-08-13 06:32 UTC
### Feedback

Hello, 
after update to HA 2024.8.1 I have this error issue - Authentication expired for Reolink WiFI.......
In my password has charcter  **%** but now is not allowed - WHY, before no problem.? This is messaage - Password contains incompatible special character, only these characters are allowed: a-z, A-Z, 0-9 or @$*~_-+=!?.,:;'()[] - i don´t want to change password.
tks

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

2024.8.1

**Comment by starkillerOG** [comment] 2024-08-13 08:30
Duplicate of https://github.com/home-assistant/home-assistant.io/issues/34199 and https://github.com/home-assistant/core/issues/123302 and a few others

See my explination here: https://github.com/home-assistant/core/issues/123302#issuecomment-2274337355

Sorry for the inconveniance of having to make a new user/change the password.

**Closed as completed by starkillerOG** 2024-08-13 08:30 UTC
Labels: integration: reolink
