### ISSUE TITLE
Integration currently not possible to set up

### ISSUE THREAD

**Issue by guniv** [home-assistant/home-assistant.github.io#22232] opened 2022-04-02 19:28 UTC
### Feedback

This page needs to be updated ASAP to reflect the fact that this integration can not be set up. See [this issue](https://github.com/home-assistant/core/issues/67662).

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2022.3.8

**Comment by allenporter** [comment] 2022-04-02 19:44
Duplicate of https://github.com/home-assistant/home-assistant.io/issues/22141

Would appreciate someone sending a PR

**Closed as completed** 2022-04-02 19:44 UTC
Labels: integration: nest
