### ISSUE TITLE
Phillips TV integration stops contacting to the tv

### ISSUE THREAD

**Issue by laithalsunni** [home-assistant/home-assistant.github.io#19462] opened 2021-09-24 18:41 UTC
### Feedback

After initial connection to the TV there integration will lose connection. The only way to restore the connection is to cut the power to the TV and restart. After that there a Gratian will connect to the TV and then lose connection within seconds. I have tried several versions of the firmware from different countries and all of them behave the same. this is an example of one of the errors I get one trying to control the TV.
````
Logger: homeassistant.components.websocket_api.http.connection
Source: components/philips_js/light.py:378 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 2:17:28 PM (1 occurrences) 
Last logged: 2:17:28 PM

[544424936256] All connection attempts failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 61, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 281, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 234, in handle_async_request
    response = await connection.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 136, in handle_async_request
    self.socket = await self._open_socket(timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 163, in _open_socket
    return await self._backend.open_tcp_stream(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/auto.py", line 44, in open_tcp_stream
    return await self.backend.open_tcp_stream(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 154, in open_tcp_stream
    stream = await TLSStream.wrap(
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/haphilipsjs/__init__.py", line 526, in postReq
    resp = await self.session.post(self._url(path, protocol), json=data, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1825, in post
    return await self.request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1494, in request
    response = await self.send(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1586, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1616, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1655, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1699, in _send_single_request
    ) = await transport.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 276, in handle_async_request
    (
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 78, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 471, in async_handle_light_off_service
    await light.async_turn_off(**filter_turn_off_params(light, params))
  File "/usr/src/homeassistant/homeassistant/components/philips_js/light.py", line 378, in async_turn_off
    if await self._tv.setAmbilightMode("internal") is False:
  File "/usr/local/lib/python3.9/site-packages/haphilipsjs/__init__.py", line 991, in setAmbilightMode
    if await self.postReq("ambilight/mode", data) is None:
  File "/usr/local/lib/python3.9/site-packages/haphilipsjs/__init__.py", line 540, in postReq
    raise ConnectionFailure(err) from err
haphilipsjs.ConnectionFailure: All connection attempts failed
````

### URL

https://www.home-assistant.io/integrations/philips_js/

### Version

2021.9.7

## System Health

version | core-2021.9.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Asia/Riyadh

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4657
Installed Version | 1.15.2
Stage | running
Available Repositories | 948
Installed Repositories | 55

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.4
-- | --
update_channel | stable
supervisor_version | supervisor-2021.09.0
docker_version | 20.10.7
disk_total | 116.9 GB
disk_used | 15.3 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), AdGuard Home (4.1.9), DOODS (2), File editor (5.3.3), Home Assistant Google Drive Backup (0.105.2), Mosquitto broker (6.0.1), RPC Shutdown (2.2), Tor (3.0.5), VLC (0.1.2), WireGuard (0.5.1), MariaDB (2.4.0), Nginx Proxy Manager (0.11.0), ESPHome (2021.9.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 24
views | 5
mode | storage

</details>

**Comment by elupus** [comment] 2021-09-24 22:25
Duplicate of: https://github.com/home-assistant/core/issues/49801 

Annoyingly. I have no idea how to solve this. The TV crashes for unknown reasons.

**Closed as completed by elupus** 2021-09-24 22:25 UTC
Labels: integration: philips_js
