### ISSUE TITLE
missing server (https://server.growatt.com/)

### ISSUE THREAD

**Issue by rogeliomartin** [home-assistant/home-assistant.github.io#31129] opened 2024-01-30 04:02 UTC
### Feedback

Hi! if you please could add the server (https://server.growatt.com/) to the list it would greatly appreciated!

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2024.1.4

### Additional information

Hi! if you please could add the server (https://server.growatt.com/) to the list it would greatly appreciated!

**Comment by klaasnicolaas** [comment] 2024-01-30 09:43
Duplicate of #31090

Always check existing issues before creating a new one. There has been a lot of talk about growatt lately, but this is not the right repository for that.

./Klaas

**Closed as not planned by klaasnicolaas** 2024-01-30 09:43 UTC
Labels: integration: growatt_server
