### ISSUE TITLE
Case sensitive default parameter values are being rendered in lowercase, even if written as uppercase

### ISSUE THREAD

**Issue by kpine** [home-assistant/home-assistant.github.io#14085] opened 2020-07-26 05:38 UTC
## The problem
The [mqtt binary_sensor](https://www.home-assistant.io/integrations/binary_sensor.mqtt/#payload_off) docs show that the default values for optional parameters `payload_on` and `payload_off` are the strings `on` and `off`, when in fact the values are [case sensitive](https://github.com/home-assistant/core/blob/34d01d5e4777e5394c6af91c5eadf99d823ba554/homeassistant/components/mqtt/binary_sensor.py#L47-L48) and are really `ON` and `OFF`. 

![image](https://user-images.githubusercontent.com/791794/88472289-002cbd80-cec6-11ea-9849-32f499d39fe4.png)

The actual text in the source document is written as ["OFF"](https://github.com/home-assistant/home-assistant.io/blame/134b651464537763d4de95ff896010e5ba3c4442/source/_integrations/binary_sensor.mqtt.markdown#L134) and "ON", but whatever is rendering the text in the browser is converting it to lowercase. The uppercase value is in the HTML source, but it looks like there's some CSS styling that makes it lowercase.

```html
<span class="config-vars-required">(<span class="false">Optional</span>, default: OFF)</span>
```
```css
div.config-vars .config-vars-required {
    color: #8792a2;
    font-size: 13px;
    text-transform: lowercase;
}
```

So the bug here is that the doc styling is changing the default value of parameters, and in this case the values are case-sensitive, which is misleading. This styling might be a problem for other documentation as well. Behavior is the same in Chrome and Firefox.

For this sensor, the output of the `value_template` must **exactly** match `ON` and `OFF` (it uses a simple string [comparison](https://github.com/home-assistant/core/blob/34d01d5e4777e5394c6af91c5eadf99d823ba554/homeassistant/components/mqtt/binary_sensor.py#L202)) otherwise the state of sensor will not be correct (e.g. a template the renders as `on` does not function correctly). The docs showing them lowercase, while an example showing uppercase is confusing.

**Comment by frenck** [comment] 2020-07-26 13:54
Duplicate of #14040

**Closed as completed by frenck** 2020-07-26 13:54 UTC
