### ISSUE TITLE
Proximity units

### ISSUE THREAD

**Issue by niknik98** [home-assistant/home-assistant.github.io#31659] opened 2024-02-28 10:24 UTC
### Feedback

It is probably worth mentioning in the documentation what the actual proximity units are. In the original (soon to be depreciated) Proximity integration the units were Metric = Kilometres and Imperial = Miles  but in the new / current integration the units appear to be Metric = Meters and I'm assuming Imperial = Feet (TBC). This caught me out as I set my automations to 4 assuming it was kilometres not meters. Please feel free to correct me if I have this wrong.

### URL

https://www.home-assistant.io/integrations/proximity/

### Version

2024.2.4

**Comment by mib1185** [comment] 2024-02-29 18:45
- duplicate of #31312

**Closed as completed by mib1185** 2024-02-29 18:45 UTC
Labels: integration: proximity
