### ISSUE TITLE
Ungesundes System – Supervisor-Update fehlgeschlagen

### ISSUE THREAD

**Issue by TwardyBobek** [home-assistant/home-assistant.github.io#35695] opened 2024-11-11 09:11 UTC
### Feedback

![2024-11-11 100925](https://github.com/user-attachments/assets/c51e29ed-5d24-4c32-afbd-095b295cbb95)

### URL

https://www.home-assistant.io/more-info/unhealthy/supervisor/

### Version

2024.11.1

**Comment by TwardyBobek** [comment] 2024-11-11 09:22
Die Aktion update/install konnte nicht ausgeführt werden. Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")

**Comment by pd5wl** [comment] 2024-11-11 10:25
Same problem here:

> Logger: homeassistant.components.websocket_api.http.connection

> Bron: components/websocket_api/commands.py:245
> integratie: Home Assistant WebSocket API (documentatie, problemen)
> Eerst voorgekomen: 11:16:49 (1 gebeurtenissen)
> Laatst gelogd: 11:16:49

> 
> [140138223810544] Unexpected exception
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 262, in async_install
>     await self.coordinator.supervisor_client.supervisor.update()
>   File "/usr/local/lib/python3.12/site-packages/aiohasupervisor/supervisor.py", line 43, in update
>     await self._client.post(
>   File "/usr/local/lib/python3.12/site-packages/aiohasupervisor/client.py", line 173, in post
>     return await self._request(
>            ^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/aiohasupervisor/client.py", line 122, in _request
>     raise exc_type(result.message, result.job_id)
> aiohasupervisor.exceptions.SupervisorBadRequestError: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
>     response = await hass.services.async_call(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
>     response_data = await coro
>                     ^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
>     return await target(service_call)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
>     single_response = await _handle_entity_call(
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
>     result = await task
>              ^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
>     await entity.async_install_with_progress(version, backup)
>   File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 502, in async_install_with_progress
>     await self.async_install(version, backup)
>   File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 264, in async_install
>     raise HomeAssistantError(
> homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3")
> 

Home Assistant

Core 2024.11.0
Supervisor 2024.11.2
Operating System 13.2
Frontend 20241106.0

Running HaOS in a VM. 

Update from console gives:

> Error: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2024.11.3: 500 Server > Error for http+docker://localhost/v1.47/images/create?tag=2024.11.3&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("toomanyrequests: retry-after: 1.145839ms, allowed: 44000/minute")

**Comment by geertvanzoest** [comment] 2024-11-11 12:07
Related / duplicate of:
https://github.com/home-assistant/supervisor/issues/5405

**Closed as not planned** 2024-11-11 12:59 UTC
Labels: more-info
