### ISSUE TITLE
unknown error occurred when adding a car to RDW integration

### ISSUE THREAD

**Issue by 1969selwyn** [home-assistant/home-assistant.github.io#21217] opened 2022-01-16 21:41 UTC
### Feedback

Hello, I like your RDW integration. Thank you for your effort and support.
I've succesfully added my car but adding an oldtimer the following error popped up: Unknown error occurred.
The numberplate at hand is AM-50-01 or AM5001 although the number plate is known on ovi.rdw.nl.
Running HA on pi4, latest version: OS7.1, core-2021.12.9
Screenshots have been added under additional information.
Thank you for your support!

### URL

https://www.home-assistant.io/integrations/rdw/

### Version

2021.12.9

### Additional information

screenshots:
**multiple succesfull addings:**
![2022-01-16 RDW integratie gelukt](https://user-images.githubusercontent.com/73650623/149679029-e1e53803-c86a-4bb8-af78-6aef8c0f617c.jpg)
**failed adding:** 
![2022-01-16 223236 RDW AM5001](https://user-images.githubusercontent.com/73650623/149679116-2d4bcddc-53af-499c-9a47-098e839bde99.jpg)
![2022-01-16 223207 RDW AM5001 #2](https://user-images.githubusercontent.com/73650623/149679119-0b664e43-c1c3-4e20-b9ba-431d687d7a5b.jpg)
**ovi.rdw.nl screenshot:** 
![2022-01-16 RDW check AM5001](https://user-images.githubusercontent.com/73650623/149679152-80cab35b-e9aa-46bf-8d60-829c73753f95.jpg)

**Comment by frenck** [comment] 2022-01-17 10:39
This has been fixed in the current development branch and pending release for Home Assistant 2022.2.

It is caused by missing APK information (which is expected in this case).

**Closed as completed by frenck** 2022-01-17 10:39 UTC
Labels: integration: rdw
