### ISSUE TITLE
Instructions Do Not Work

### ISSUE THREAD

**Issue by BLGGREGG** [home-assistant/home-assistant.github.io#22473] opened 2022-04-22 16:58 UTC
### Feedback

I tried following the instructions on adding Insteon to HA. The Insteon hub will not connect. I got the IP address, user name and password from the bottom of the 2245-222 hub. I only get "Failed to Connect" when trying to add the Insteon Integration. Any suggestions?

### URL

https://www.home-assistant.io/integrations/insteon/

### Version

2022.4.6

**Comment by klaasnicolaas** [comment] 2022-04-22 18:11
Duplicate of #22460?

**Comment by teharris1** [comment] 2022-04-22 19:35
Hello @BLGGREGG did you try to use your browser to enter the username and password into the Hub?  Try pointing your browser to http://ip-address:25105. This should give you a login prompt. Enter the credentials you have from the bottom of the Hub and see if that allows you to log in. If it does not then the issue is still the username and password.

**Comment by soloyolk** [comment] 2022-04-23 15:03
I just got the same issue.  Going to the ip and port directly via web browser worked fine with the credentials, but it seems to give "Failed to connect" when trying to add Insteon Hub Version 2 to HA.

**Comment by soloyolk** [comment] 2022-04-23 15:03
I just got the same issue.  Going to the ip and port directly via web browser worked fine with the credentials, but it seems to give "Failed to connect" when trying to add Insteon Hub Version 2 to HA.

**Comment by klaasnicolaas** [comment] 2022-04-23 15:28
Closing it because duplicate of #22460

**Closed as completed by klaasnicolaas** 2022-04-23 15:28 UTC
Labels: integration: insteon

**Comment by BLGGREGG** [comment] 2022-04-23 15:53
I followed those instructions in number 22460 and I got no results. Was unable to login to the hub. I even did a factory reset even though they said everywhere not to do that to see if the password and username that was on the bottom of the hub would become available to log into. It did not.

Gregg Campbell from his IPhone
Expect typos
________________________________

**Comment by BLGGREGG** [comment] 2022-04-23 16:56
I tried your suggestion with no success. Is it possible that, even after a factory reset, the Insteon hub will have a different username/password than what is printed on the bottom of the device?

Gregg
