### ISSUE TITLE
Energy lack for configuration 

### ISSUE THREAD

**Issue by tyjtyj** [home-assistant/home-assistant.github.io#18906] opened 2021-08-12 13:24 UTC
### Feedback

It should have basic configuration examples 

Configuration
This integration is by default enabled, unless you've disabled or removed the default_config: line from your configuration. If that is the case, the following example shows you how to enable this integration manually:

# Example configuration.yaml entry
energy:

### URL

https://www.home-assistant.io/docs/energy/

### Version

2021.8.6

**Comment by klaasnicolaas** [comment] 2021-08-12 14:36
Duplicate of #18905

**Closed as completed by klaasnicolaas** 2021-08-12 14:36 UTC
Labels: duplicate
