### ISSUE TITLE
Xiaomi BLE 

### ISSUE THREAD

**Issue by titusdam** [home-assistant/home-assistant.github.io#23698] opened 2022-08-08 02:24 UTC
### Feedback

The integration immediately recognized all my Xiaomi thermometers.  However, it asks me for a bindkey.  But it's impossible for me to know which thermometer it is because I can't see the mac address or anything else.  How can I do?

### URL

https://www.home-assistant.io/integrations/xiaomi_ble/

### Version

2022.8.2

**Comment by Jc2k** [comment] 2022-08-08 05:49
Hi! Sorry about that. Right now I don't even have a single device with encryption so haven't encountered this myself.

I'll be sorting out the device "title" to be consistent and have the Mac in it in a future release. This will help people that already know the MAC of their device.

For devices that support it i also plan to try and port the bindkey generation from the web based tool to HA. This will get the device into HA without having to know the MAC.

Some devices have an "identify" routine (on my plant sensors it flashes an LED). If yours does and we can find it, that's another option).

In the meantime I don't have a good answer. Trying all the bind keys until one works or taking the battery out of them all and adding them back one at a time are all I can think of.

We are already working on showing the MAC, I'm hoping it will be in the September release. I'm going to close this as a dupe of #76163.

**Closed as not planned** 2022-08-08 05:49 UTC
Labels: integration: xiaomi_ble
