### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by thiagoufg** [home-assistant/home-assistant.github.io#16587] opened 2021-02-15 12:10 UTC
**Feedback**

On the page "This entity does not have a unique ID?" (https://www.home-assistant.io/faq/unique_id) there's a broken link if you click on "In case you want to read more about unique IDs, head over to this developer documentation page" (https://www.home-assistant.io/docs/entity_registry_index/).

**URL**

https://www.home-assistant.io/faq/unique_id/

**Version**

2021.2.3

**Comment by frenck** [comment] 2021-02-15 12:12
Thanks for reporting @thiagoufg!

However, it is a duplicate of #16564, so closing this one 👍

**Closed as completed by frenck** 2021-02-15 12:12 UTC
Labels: faq
