### ISSUE TITLE
Multiple ChromeCast's not possible

### ISSUE THREAD

**Issue by Construct-Ent** [home-assistant/home-assistant.github.io#30016] opened 2023-11-27 03:15 UTC
### Feedback

as the title says, i have 3 chrome casts in the house, and i have this configured but the remote seems to latch onto whatever one of the chromcasts shows up first, and all 3 remotes i have added to HA control that one, not the others. they were all added with just the one active and with the code form that device. and i just had to redo all this and still nothing. it's not very useful to only get one and not the others. 

### URL

https://www.home-assistant.io/integrations/androidtv_remote/

### Version

2023.11.3

**Comment by tronikos** [comment] 2023-11-27 05:16
Multiple Chromecast devices are possible. I believe this is a duplicate of https://github.com/home-assistant/core/issues/97978

**Comment by tronikos** [comment] 2023-11-27 05:16
@home-assistant close

**Closed as completed by tronikos** 2023-11-27 05:16 UTC
Labels: integration: androidtv_remote
