### ISSUE TITLE
BGE integration non-functional

### ISSUE THREAD

**Issue by 7uAip6** [home-assistant/home-assistant.github.io#30291] opened 2023-12-12 02:30 UTC
### Feedback

Baltimore Gas & Electric integration with Opower provides no data.

### URL

https://www.home-assistant.io/integrations/opower/

### Version

2023.12.1

**Comment by tronikos** [comment] 2023-12-12 08:42
Duplicate of https://github.com/home-assistant/home-assistant.io/issues/29674

**Comment by tronikos** [comment] 2023-12-12 08:42
@home-assistant close

**Closed as completed by tronikos** 2023-12-12 08:42 UTC
Labels: integration: opower

**Comment by tronikos** [comment] 2023-12-12 08:43
I meant to say duplicate of https://github.com/home-assistant/core/issues/105381
