### ISSUE TITLE
Etcher won't run in Ubuntu

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#24346] opened 2022-10-02 20:35 UTC
### Feedback

I had this problem and it seems a few others too, so it would be great to have the install instructions edited to help new users like myself.  I can't work out how to edit the page so I'll leave it to someone with more skills.

When booting from a Ubuntu usb drive, Balana Etcher won't run due to a missing libfuse2 library

Thanks to reddit user Vortec4800

https://old.reddit.com/r/homeassistant/comments/x4ezhy/balana_etcher_wont_run_on_ububtu_usb_boot/

we need to run these commands in a Ubuntu terminal to run Etcher

```
sudo add-apt-repository universe

sudo apt install libfuse2
```

Install proceeds fine otherwise.

Could this be added to the install guide?  It would have saved me hours of frustration, and it seems  I'm not alone.

https://old.reddit.com/r/homeassistant/comments/xtik7d/unable_to_install_via_ubuntu/

### URL

https://www.home-assistant.io/installation/generic-x86-64/

### Version

2022.9.7

**Comment by ikifar2012** [comment] 2022-10-11 00:14
Duplicate of #24351

**Comment by frenck** [comment] 2022-10-11 07:20
Closing as duplicate

**Closed as not planned** 2022-10-11 07:20 UTC
Labels: installation
