### ISSUE TITLE
What is XZ compression?

### ISSUE THREAD

**Issue by colohan** [home-assistant/home-assistant.github.io#17445] opened 2021-04-13 16:29 UTC
### Feedback

The instructions link to virtual machine images which are compressed with a utility called "xz".  But if I follow the instructions.... VMWare doesn't recognize files with the "xz" extension.  Some Googling reveals that this is a compression scheme which has no native support in Windows, and may possibly be supported by some third-party utilities which I'm reluctant to install.

Suggestions:  either don't compress these VM images (probably not practical), or provide instructions on how to uncompress them?  (I've never enountered xz, but I discovered that a "unxz" utility is provided in Cygwin, for example.)

### URL

https://www.home-assistant.io/installation/windows/

### Version

2021.4.4

**Comment by frenck** [comment] 2021-04-14 21:25
Duplicate of #17416

**Closed as completed by frenck** 2021-04-14 21:25 UTC
Labels: installation

**Comment by frenck** [comment] 2021-04-15 19:35
Discussed this with the team, and we agree. While .xz is a widely used format, it isn't that well known to the public and not natively supported on all platforms.

We are changing the way we distribute the images soon, using well-known methods.

For reference: <https://github.com/home-assistant/operating-system/pull/1327>

Thanks for your feedback 👍

**Comment by colohan** [comment] 2021-04-15 19:40
Awesome, thank you!  (FWIW, I made it work for me by using the Cygwin64
tools, but I was surprised that the documentation didn't cover this part
better.  Switching to zip would solve the problem too.  ;-) )
