### ISSUE TITLE
No data updated

### ISSUE THREAD

**Issue by Enzisblog** [home-assistant/home-assistant.github.io#19264] opened 2021-09-08 14:21 UTC
### Feedback

No data from:
- Hospitalized in the world
- Current positive in the world
- Hospitalized in Italy
- Current positive in Italy
 

### URL

https://www.home-assistant.io/integrations/coronavirus

**Comment by ludeeus** [comment] 2021-09-08 15:10
Duplicate of https://github.com/home-assistant/core/issues/54167

**Closed as completed by ludeeus** 2021-09-08 15:10 UTC
Labels: integration: coronavirus
