### ISSUE TITLE
Ring Integration stopped working

### ISSUE THREAD

**Issue by JLCode-tech** [home-assistant/home-assistant.github.io#11692] opened 2020-01-09 22:17 UTC
Current Ring integration was working for last 2 weeks. Current error message:

Invalid config
The following components and platforms could not be set up:

ring
ring.binary_sensor
ring.sensor
ring.camera
Please check your config.

Config except (working previous weeks):
ring:
  username: xxxx@xxxx.net
  password: xxxxxx

binary_sensor:
  - platform: ring

camera:
  - platform: ring

sensor:
  - platform: ring

Log Traceback:
2020-01-10 09:15:07 ERROR (MainThread) [homeassistant.setup] Error during setup of component ring
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 176, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/ring/__init__.py", line 55, in setup
    ring = Ring(username=username, password=password, cache_file=cache)
  File "/usr/local/lib/python3.7/site-packages/ring_doorbell/__init__.py", line 62, in __init__
    self._process_cached_session()
  File "/usr/local/lib/python3.7/site-packages/ring_doorbell/__init__.py", line 91, in _process_cached_session
    req = self.query(url, raw=True)
  File "/usr/local/lib/python3.7/site-packages/ring_doorbell/__init__.py", line 198, in query
    'Bearer {}'.format(self._get_oauth_token())
  File "/usr/local/lib/python3.7/site-packages/ring_doorbell/__init__.py", line 111, in _get_oauth_token
    self.auth = oauth.refresh_tokens()
  File "/usr/local/lib/python3.7/site-packages/ring_doorbell/auth.py", line 59, in refresh_tokens
    token = self._oauth.refresh_token(OAuth.ENDPOINT)
  File "/usr/local/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 446, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.

**Comment by arsaboo** [comment] 2020-01-09 22:32
Duplicate of https://github.com/home-assistant/home-assistant/issues/30626

**Closed as completed by arsaboo** 2020-01-09 22:32 UTC
