### ISSUE TITLE
Legrand home+control config - Redirect URL

### ISSUE THREAD

**Issue by erbagiovanni** [home-assistant/home-assistant.github.io#17395] opened 2021-04-10 17:18 UTC
### Feedback

Hi, from my side it's really not clear how should I fill "redirect URL" during custom app creation on legrand developer site. Is it possible to advice on this? Thanks

### URL

https://www.home-assistant.io/integrations/home_plus_control/

### Version

2021.4.3

**Comment by frenck** [comment] 2021-04-10 17:19
Duplicate of #17337

**Closed as completed by frenck** 2021-04-10 17:19 UTC
