### ISSUE TITLE
Problem with the integration PVPC

### ISSUE THREAD

**Issue by kilem86** [home-assistant/home-assistant.github.io#27391] opened 2023-05-13 18:09 UTC
### Feedback

Este error se originó a partir de una integración personalizada.

Logger: homeassistant.config_entries
Source: custom_components/pvpc_hourly_pricing/__init__.py:102
Integration: Spain electricity hourly pricing (PVPC)
First occurred: 20:05:33 (1 occurrences)
Last logged: 20:05:33

Error setting up entry PVPC for pvpc_hourly_pricing
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/pvpc_hourly_pricing/__init__.py", line 102, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

### URL

https://www.home-assistant.io/integrations/pvpc_hourly_pricing/

### Version

2023.5.2

### Additional information

Este error se originó a partir de una integración personalizada.
Logger: homeassistant.config_entries
Source: custom_components/pvpc_hourly_pricing/__init__.py:102
Integration: Spain electricity hourly pricing (PVPC)
First occurred: 20:05:33 (1 occurrences)
Last logged: 20:05:33

Error setting up entry PVPC for pvpc_hourly_pricing
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/pvpc_hourly_pricing/__init__.py", line 102, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by azogue** [comment] 2023-05-21 10:48
Hi @kilem86,

It seems you are using a 'custom' version of the component. This problem does not affect the pvpc_hourly_pricing integration of HA, so I'm closing this issue (which is also a duplicate of #27276 and #26322)

[See here for more details](https://github.com/home-assistant/core/issues/91205#issuecomment-1502853102)

**Closed as not planned** 2023-05-21 10:48 UTC
Labels: integration: pvpc_hourly_pricing
