### ISSUE TITLE
HAOS11 Arm based board breaking change for network names

### ISSUE THREAD

**Issue by Yorkie71** [home-assistant/home-assistant.github.io#29388] opened 2023-10-17 07:47 UTC
### Feedback

I missed the breaking change in HAOS 11 where the network names on Arm boards have changed and wondered why my system monitor was coming back with "unknown" status.
![image](https://github.com/home-assistant/home-assistant.io/assets/9529010/dd3c5880-3492-42d7-9b55-214158129fbb)

A quick search [found the details](https://github.com/home-assistant/operating-system/releases#:~:text=Latest-,Home%20Assistant%20OS%2011.0,-is%20built%20from) and a change of the config sorted the issue.
![image](https://github.com/home-assistant/home-assistant.io/assets/9529010/14bc2fbc-ce6b-41d0-a24e-117e81189f31)
Not sure if it's worth an update of this page.

### URL

https://www.home-assistant.io/integrations/systemmonitor/

### Version

2023.10.3

**Comment by frenck** [comment] 2024-10-19 13:20
Backwards incompatible changes are part of our release notes; we currently have no plans to maintain a duplicate of them on each integration page, as all other documentation in Home Assistant always reflects the latest stable version.

Nevertheless, thanks for your suggestion 👍 

../Frenck

**Closed as not planned by frenck** 2024-10-19 13:20 UTC
Labels: integration: systemmonitor
