### ISSUE TITLE
Doesn't work no more

### ISSUE THREAD

**Issue by Bart-van-Gorp** [home-assistant/home-assistant.github.io#23771] opened 2022-08-15 08:41 UTC
### Feedback

Dear,

The ISS map marker stoped working like two weeks ago. I've tried to reinstall the integration, but it hasn't solved the issue. I've tried to add it to the map again, but this still didn't solve the issue. There are no errors in my logs.

Is this a known issue?

Yours sincerely,

Bart

### URL

https://www.home-assistant.io/integrations/iss/

### Version

2022.8.4

**Comment by DurgNomis-drol** [comment] 2022-08-15 09:00
Can you check if got disabled under the integration settings by accident? If I remember right, you need to enable it, as it is not enabled by default

**Comment by Bart-van-Gorp** [comment] 2022-08-15 13:21
Hi @DurgNomis-drol DurgNomis-drol, thank you for your answer. The strange thing is, is that I can't find the entity, even when I look at hidden, or entity's that are not enabled. This used to work for a few weeks. I've clicked on every button in the integration. binary_sensor.iss seems not to exist no more, while the entity is installed on one of my smaller maps. I've also applied show on map.

**Comment by DurgNomis-drol** [comment] 2022-08-15 15:30
See the other issue #76615 that is open, the API does not work anymore, and therefore it doesn't create an entity

**Comment by frenck** [comment] 2022-08-15 17:59
Closing as a duplicate of <https://github.com/home-assistant/core/issues/76615>

Please note, that this issue tracker is not for reporting issues with integrations.

../Frenck

**Closed as not planned by frenck** 2022-08-15 17:59 UTC
Labels: integration: iss
