### ISSUE TITLE
dependency python-eq3bt==0.1.6 missing

### ISSUE THREAD

**Issue by gdampf** [home-assistant/home-assistant.github.io#3968] opened 2017-11-12 17:08 UTC
I tried to get my eq3 BlueTooth Valve running with Hass.io 0.57.2 on a raspberry pi zero w. It has the same BLE-Chip as Raspi3.
After installing the add on for BCM43xx and adding in configuration.yaml this segment

`climate:`
`- platform: eq3btsmart`
`     devices:`
`      room1:`
`        mac: '00:1a:22:xx:xx:xx'`

I got this error:

`2017-11-12 17:49:41 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package python-eq3bt==0.1.6: Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-l98hosbf/bluepy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-00axz_60-record/install-record.txt --single-version-externally-managed --prefix  --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-l98hosbf/bluepy/
2017-11-12 17:49:41 ERROR (MainThread) [homeassistant.setup] Not initializing climate.eq3btsmart because could not install dependency python-eq3bt==0.1.6
2017-11-12 17:49:41 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform climate.eq3btsmart: Could not install all requirements.`

Looks like, that there is a missing dependency and I am not familiar enough with that docker construction, to solve it by myself.
Could somebody fix the dependency and/or tell me, how to do it by myself, please?

BR
Guido

**Comment by MartinHjelmare** [comment] 2017-11-12 18:20
Wrong repo and duplicate of https://github.com/home-assistant/home-assistant/issues/10421.

**Closed by MartinHjelmare** 2017-11-12 18:20 UTC
