### ISSUE TITLE
Honeywell Total Connect Comfort (US) Not Retrieving All Devices

### ISSUE THREAD

**Issue by TheJessle** [home-assistant/home-assistant.github.io#19064] opened 2021-08-23 20:06 UTC
### Feedback

My Honeywell TCC US account has three thermostats that are controllable in the online portal and via the Honeywell TCC android phone app. 

What I've done for troubleshooting:

- Since it allows for more than one integration, I attempted that with no affect.
- An additional admin account was created, and this was used to grant the integration access... there was no change.
- I attempted to use the configuration.yaml with no change.

My HA is hosted on a VirtualBox and I'm running the most current version of HA. 

### URL

https://www.home-assistant.io/integrations/honeywell/

### Version

2021.8.8

**Comment by rdfurman** [comment] 2021-08-23 20:20
Duplicate of https://github.com/home-assistant/core/issues/53981.

**Closed as completed** 2021-08-24 07:05 UTC
Labels: integration: honeywell
