### ISSUE TITLE
Error 400: invalid_request due to Google Auth policy change

### ISSUE THREAD

**Issue by andorardo** [home-assistant/home-assistant.github.io#21873] opened 2022-03-02 21:30 UTC
### Feedback

In the "Configure OAuth Consent screen" section, the documentation item 6 suggests adding a Test User. But such an option no longer exists in the Google flow. (There is no mention of a "Test User" anywhere in creating the app.)

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2022.3.0

**Comment by andorardo** [comment] 2022-03-02 21:43
By the way, I followed the instructions to a T, and get an `Error 400: invalid_request` at the end.

I made sure to select Desktop rather than Web app, and it still gives that error. The only deviation I had from the instructions was that I was not able to add a Test user, since that option is gone. Could that be the reason?

**Comment by allenporter** [comment] 2022-03-03 03:15
Hi,

I just went through the oauth consent steps and I see the test user steps and references test steps in the instructions:

<img width="828" alt="Screen Shot 2022-03-02 at 7 06 11 PM" src="https://user-images.githubusercontent.com/6026418/156488963-a9ffd91f-b8a8-4a9d-b292-7d68256f4400.png">
<img width="898" alt="Screen Shot 2022-03-02 at 7 06 21 PM" src="https://user-images.githubusercontent.com/6026418/156488977-b95bd37d-787a-4597-9772-6986def96dc7.png">
<img width="878" alt="Screen Shot 2022-03-02 at 7 06 42 PM" src="https://user-images.githubusercontent.com/6026418/156488985-fcf27cfd-0d34-4efe-b8df-84fa3921cd7c.png">

Once I completed, you can change the status from `Testing` to `Production` or back. The `Test users` option  still shows up when in `Testing`

<img width="920" alt="Screen Shot 2022-03-02 at 7 08 49 PM" src="https://user-images.githubusercontent.com/6026418/156489041-d54ebeef-2df1-4e9b-be4a-999db220ff4b.png">
<img width="994" alt="Screen Shot 2022-03-02 at 7 09 21 PM" src="https://user-images.githubusercontent.com/6026418/156489047-b7eb009d-5063-4197-afe5-9d26d5239da8.png">
<img width="993" alt="Screen Shot 2022-03-02 at 7 09 27 PM" src="https://user-images.githubusercontent.com/6026418/156489051-79a2741f-d470-4069-8a19-1a3f2bd540a7.png">

I am not seeing what you are seeing, so either you have a different view or a step got lost somewhere? 

Regarding your `invalid_request` error, I need more information about the details of the error if you have them since there are a couple variations.

Lastly I can offer https://www.home-assistant.io/integrations/nest/#troubleshooting if you have not seen that, though not sure it covers your specific problem.

**Comment by andorardo** [comment] 2022-03-03 03:39
Wow, this is what I saw:

![](https://lh3.googleusercontent.com/pw/AM-JKLV8Ubv4qb4XeEONhRCoYOfXPkhOK6QNEYPKIGMW42C75XlfLHZ1-ff9zspLolDDRADkHkBCCd-MxD5uqJri5hC1-P1ZShc-y0Akr316VAJVeq66pp_A__T9h24Wv4eNYlUv9Hasb90qet-npKQIYuQzuBp9vI1W3EfkPTaQUQeCWtUsJ_D9Uhfx9IQkWKskYsciM8Selzqu9E8i9NvtjxfITRpW9nI167t-ZyZN4s_tJRYorzo77uvI1jh-cH_k2Oo7ATVOYu_RnLXJqLDlw7O0LYEBwCuyVIdPSUcTB86Az8QcbCa2XrE3nAqShv6i0OEHjotHMKYutNscT6oG_Jmzdnm7vppC7D9oQc2V-B4wxKcDxv2SISuXb0Bk5wZEHNFRaIK4-QFgvEixLtbZ3dQ8Ugq7aBrJg8q6_Rd9gmyY_JuVwF5bcxFpRmNNIJQYAN9CEeoiB3MnwR6TgC_szfp4j91rAF_e078lSYUY-0DJx3Sn2Y4fKoTTFPiVRRAIhVoJ0vvQ7AOw-QcOYyZ8dbfXeQMCvkQETqNE7zl86KkP3cX3GIeNda1msUr_24-G-QM2N26OlzGmzBZ4bneDqd2xch4Y4kUe2wkjd9vHys8K7IH9rF_uffvBaArQXz3f6xak9BhXm8MfRxvRLP4GpzB79q1TnPG5V228k-45bgKQBHsAr8wVnDx_llWg2cEXrQ=w1206-h702-no?authuser=0)

Inspired by your final image, I clicked "BACK TO TESTING", and now the "Optional info" is replaced with "Testing users". There I was able to add a testing user. So I had to switch to Testing mode to be able to add the testing users, before returning to Prod mode. (NOTE: There's no way to *delete* the consent screen, only edit it, and I didn't realize I had to switch modes before editing.)

The second error is that even after fixing the above testing user and hitting prod, I'm seeing

![](https://lh3.googleusercontent.com/pw/AM-JKLVf5fqLX29_RDaXNettMlNKnyER376ISjPqVZ_Jjkh1l01S_qkUhmYpI2hsbuRvcM8Nv0SoEjoiTotig6BkIXKBNUSssFLYYjmrVGP3tVHv8pqIFCeGwgkNntwxZ4xns_ODaI29QZHcDYah_J4OuiZ7xtwD2PyLfKbqxOxubIi6qtpciqK2WM018ma3yUKUuOB8gVdcz03K--qZ6xuxrOdVchWFRyKq6MOtad-bMLpQSnlmIq8BV0UG5zZ9vGJFo6XVGCzCj6oho6mBX8QD8FcBocNJKiLyto4yDvgShzMRv6GzPexGtITEEvNBEejKZEg75kE0HAZYGtODqejP31_UFUvPmkltNonmyG63Bikj-hEGf3pMgLdqvNbMs6BuowE_zYz3YJNnnSh82h2s3NaMe4EyLWPQuAYsHxrz1RoSKctXzmKzyZZYMvLcOX7W-n1qRXVa-aAuMGjgVz690yNaKQrYyPQsl0-A_oIR7gaR82x19oZly2DeC-bfx72UpwNLz5NHeilfjicDTjwvt2nzNaxjFygSZWMXEvPJMABZbez9cYEQ9i4ZA08BGFOgb_QZ-ZLtUzWfyHO6kheZywgeWMw6T-mhTGu5SFA2EZ38lrz8OlRZ_pdOrKtUSieUaWIDNrmqPjCqcegYRYtr9pt6itTN6Y58Vy9y5GrHx5hLhAYmm48X2jCEb7xQ3KxDrQ=w830-h1146-no?authuser=0)

The Troubleshooting page has lots of useful error cases, but not this one in particular.

Is it possible to know what Google is complaining about with regard to "doesn't comply with Google's OAuth 2.0 policy for keeping apps secure" ?

**Comment by allenporter** [comment] 2022-03-03 03:45
To answer your specific question I think the documentation here is relevant:
https://developers.google.com/identity/protocols/oauth2/production-readiness/policy-compliance#separate-projects-testing-production

However, i've personally never seen this happen. It implies that one of the steps may be out of whack? I'd recommend watching the video, as it shows you how to get this setup within ~18 minutes or so.

**Comment by andorardo** [comment] 2022-03-03 03:56
For good measure, I just did everything from scratch. That is to say, I created a brand new project, enabled the apis, added the oauth consent, added the credentials, added the device project_id. All for a completely new cloud project, and I'm still seeing the same 400 error.

I just watched the video and did the whole thing AGAIN, and the same error. The only difference is I put my ids in a secrets file, but surely that's not the reason.

I have several (real) cloud projects, and I have two Nest thermostats in two separate homes. Could either of those be messing with this particular project?

**Comment by andorardo** [comment] 2022-03-03 03:58
And the authentication page I'm seeing is slightly different to the one in the video: [authorize your account](https://lh3.googleusercontent.com/pw/AM-JKLWuwUCFheKcAcV-XX1Eq9BtYzT6DWDMgOCCZvSUGfcp0D1H3mllY08OWRQ_Gh8gvt3ibbS4IAFOAOJNCWQdJkJVeDuWVtLL4QajG7d5lzs6lEQQKEit0JIZi9bn-8_cMEca1QiV43V5HNzDJgU97aeDsN-okRLOepTuGfzBBrrqYVp5dQ0-GTN17vpm2I8490bo1aDwAhsR4F_7xrdtKwFJibTlwQt4guaNmTowwOBq6L9V9ao5gNCvKJzZI8cWgS3AGMq5ss36hIuUq2LEo4Sv47RqCFlKIiWR4-y404aUADe1iau53MrsPLI4aO-v2SqelTRNNT7i_585RFdgapP0eqncCM2HvMobRGyE9boKueMFxcjfgyb5lBRsKkkL-M8997CbanfSzd9s6PtlcG3lQhF5BZbbV0fBXOWHrpGM_oWMom2k-wtGR2sZHQGdCCd19b6htOzugr2hCqVCVPevNbdLMiCDv8wBGa9UZkG1O3lyKRPKXD_VCu2sdqgobmC7puad4_Tsa4fq1nvPvEXQAaUuvdq0hp5UfhnUa97xX1LVgZJCF5zUkSjKqtp5LYSR7i9osR8l1JxIk7MGaZH3_KevIWiBkryx9BY9nee0j-x75_nlBb8BfM3hqxhndkQYFTlm5FM-LWVZybDQ-tfIL9OBMa5I1g_0pais7o6XoxhRJxB0aeTXCw-rh_lW5w=w1380-h1572-no?authuser=0)

**Comment by zer010gic** [comment] 2022-03-03 04:00
I am also having the same issue trying to configure the Nest Integration with the same kind of error.  I have went through the setup twice now.

**Comment by zer010gic** [comment] 2022-03-03 04:00
Here is the error I am getting as well.

<img width="465" alt="Screen Shot 2022-03-02 at 10 50 31 PM" src="https://user-images.githubusercontent.com/73259984/156493773-0737bf38-cbd5-489f-9b02-7aa2f8cff728.png">

**Comment by zer010gic** [comment] 2022-03-03 04:02
FYI I used my actual google account and not a test account.

**Comment by zer010gic** [comment] 2022-03-03 04:07
SO I got it to work.  I had to put the app back in Testing, Authorize it, get the token etc, and then set it to published.

**Comment by andorardo** [comment] 2022-03-03 04:31
That worked for me too. Bravo Corey, thanks for figuring it out!

**Comment by allenporter** [comment] 2022-03-03 04:34
Just a warning, this likely will mean that your credentials will expire in 7 days. I think we need to figure out the actual problem that you're hitting when in Production.

**Comment by andorardo** [comment] 2022-03-03 04:53
Thanks for the heads up! How can we debug this further? 

Could there be a way in which our defaults are different and leading to a different result?

**Comment by allenporter** [comment] 2022-03-03 05:26
Hi, I just created a new totally new device access project and totally new cloud project and just completed setup. I was not able to reproduce this issue.

Are you setting extra options in the oauth consent flow? e.g. a logo or something? I'm out of ideas but i would look out for any extra steps in the oauth consent flow. That was also where you said the test users option was not an option.. however it was there.. so i don't follow what the problem was, but it must have been in a slightly different order. Maybe something that was missing that didn't seem like a big deal actually has some other side effects like requiring validation from Google.

**Comment by andorardo** [comment] 2022-03-03 05:54
Initially I reused my existing HA project, because I didn't realize the
process was so brittle.

Since then I have completed two more projects from scratch, literally
following the text in one case and the video in the other. I skipped no
items.

Apparently I'm not the only one seeing this error. :-)

Like I said, all I can think of is that I have some sort of global setting
somewhere from my many other projects that is affecting these projects.

Rather than a recipe that relies on defaults, is there a way to convey what
the settings should end up being? If there were a non-UI way to compare the
config that would be helpful.

Is there no way to find out what the true source of this error is? The
Google error is so cryptic as to be very nearly useless.

**Comment by allenporter** [comment] 2022-03-03 06:24
I appreciate that view, but I don't have that information.  The current steps have been developed over the last year and a half and improved over 30+ documentation changes based on new feedback where people get stuck.  This is a new state I've never seen before after helping 50 to 100 users of the thousands of users who have set this up, in conversations like this.

May I suggest following the pure Google developer docs and try out their curl commands? It's straight from Google documentation can take home assistant out of the picture.

So sure, probably some global setting that you have. Nest.com account? Gsuite account? Not sure...

**Comment by zer010gic** [comment] 2022-03-03 13:26
Not sure if it helps but I migrated from Hubitat where i had this setup and did not have this issue.  They use a very similar process.  I had already deleted all of the Hubitat related elements from google and the smart device section before starting the workflow for Home Assistant.

**Comment by andorardo** [comment] 2022-03-03 13:31
And just to add another datum: I used to have this working with HA over the
web app, using the same user and Cloud account. Unfortunately I scrubbed
all that in an effort to remove anything that might be interfering with the
current setup.

**Comment by allenporter** [comment] 2022-03-03 15:21
Still trying to think outside of the box on ideas here...
- OAuth Consent screen is usually a place where issues crop up -- e.g. extra data
- A mismatch between the Device Access Console OAuth client id and the Google Cloud console oauth client id. (e.g. every time you create a new oauth client id, it needs to be refreshed in the device access console) however it sounds like that isn't the case here if you're recreating it every time.
- Another consideration could be multiple accounts involved (e.g. signed into one account in google cloud console and different account in device access project)
- Here are the docs from Google: https://developers.google.com/nest/device-access/get-started for setting this up with Web Server creds -- perhaps if that still doesn't work it confirms that its a global issue, regardless of auth type.

I'm happy to try to diagnose w/ you on the home assistant discord, or go into a screen sharing session or something to compare the final states of oauth consent screens

**Comment by M1K3SD1** [comment] 2022-03-04 03:13
Just got the same thing. Set it to testing and it worked immediately. 
I want to add that I too had a very old HA project that I have removed before starting this. Not sure if it's related.

**Comment by zer010gic** [comment] 2022-03-04 20:23
I saw an interesting suggestion to do this workflow while connected over a nabu casa https connection into the HA instance since it will then source it from a https source.  I am going to try that later.

**Comment by M1K3SD1** [comment] 2022-03-04 21:11
@zer010gic I tried that, didn't work for me.

**Comment by zer010gic** [comment] 2022-03-04 21:14
@M1K3SD1 Correct same here.  It did not work for me either.

**Comment by allenporter** [comment] 2022-03-04 21:33
I realize this issue is a documentation component issue, so we should not be using it to track issues in home assistant core. 

In https://github.com/home-assistant/core/issues/67662 someone found that this is due to a global oauth policy change https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html#dates-oob -- we'll follow up on that home assistant issue.

**Comment by allenporter** [comment] 2022-03-05 04:19
I am closing this since the original test users issue was clarified, moving to the core issue.

**Closed as completed by allenporter** 2022-03-05 04:19 UTC
Labels: integration: nest
