### ISSUE TITLE
GUI created automations are written to automations.yaml

### ISSUE THREAD

**Issue by jonwaland** [home-assistant/home-assistant.github.io#16624] opened 2021-02-17 06:20 UTC
**Feedback**

see https://github.com/home-assistant/home-assistant.io/issues/16623 - same issue.

**URL**

https://www.home-assistant.io/docs/automation/editor/

**Version**

2021.2.3

**Comment by frenck** [comment] 2021-02-17 08:14
From the other issue:

> **Feedback**
> 
> Automations created by blueprints are written to automations.yaml - which may be an issue if you are not including it in your configuration, and only include automations in a subdirectory....
> 
> Should have some form of warning...
> 
> **URL**
> 
> [home-assistant.io/docs/automation/using_blueprints](https://www.home-assistant.io/docs/automation/using_blueprints/)
> 
> **Version**
> 
> 2021.2.3
> 
> see [community.home-assistant.io/t/automation-created-using-a-blueprint-not-showing-up-in-ui-after-creating/256753/13](https://community.home-assistant.io/t/automation-created-using-a-blueprint-not-showing-up-in-ui-after-creating/256753/13)

**Comment by jonwaland** [comment] 2021-03-08 01:01
I think I've done it all correctly...

**Comment by frenck** [comment] 2021-03-08 16:41
Closing as a duplicate of #16623

**Closed as completed by frenck** 2021-03-08 16:41 UTC
Labels: automation
