### ISSUE TITLE
Some sensors and automations having trouble with values from MQTT sensors (but Riemann sums work fine)

### ISSUE THREAD

**Issue by DDvO** [home-assistant/home-assistant.github.io#30992] opened 2024-01-22 15:49 UTC
### Feedback

When trying to use a sensor this defined in the `mqtt:` section of `configuration.yaml`
(that is, not, e.g., by a Shelly integration or normal user-defined one),
I get an error claiming that the sensor was not found, though the right name was given and the sensor is available.

### URL

https://www.home-assistant.io/integrations/sensor.mqtt/

### Additional information

I did not find anywhere on the `homeassistant.local` pages which version is currently running,
yet it is the latest one available (I got an update yesterday).

**Comment by jbouwh** [comment] 2024-01-22 17:06
Can you share more details. E.g. the sensor config that is not working.

**Comment by DDvO** [comment] 2024-01-22 20:10
Good that you asked for more detail.
It turns out that I was confused: MQTT sensors do work fine with Riemann sums, 
but for whatever weird reason, I cannot use them in some other sensors and automations.

Here is more detail.
```
mqtt:
  sensor:
    - name: pv1_power_mqtt
      unique_id: "pv1 power production" # is not automatically shown as friendly_name
      # a pity that friendly_name is not supported here
      state_topic: "pv1/status/switch:0"
      value_template: "{{ value_json['apower'] }}"
      unit_of_measurement: W
      device_class: power
      state_class: measurement

sensor:
  - platform: template
    sensors:

      power_production:
        friendly_name: "Power Production at micro inverter"
        device_class: power
        unit_of_measurement: 'W'
        value_template: >-
          {{ states('sensor.pv1_power_mqtt')|float(0) }}.  # this works fine
      #  {{ states('sensor.shelly1pm_power')|float(0) }}
      # using MQTT instead because Shelly Plus 1PM integration only reports changes of at least 5%

      power_consumption:
        friendly_name: "Power Consumption"
        device_class: power
        unit_of_measurement: 'W'
        value_template: >-
          {{ states('sensor.power_balance'   )|float +
             states('sensor.power_production')|float }}
          # using sensor.pv1_power_mqtt fails here

  - name: energy_production_sum
    source: sensor.power_production
    platform: integration
    unit_prefix: k
    round: 3
    method: left   
     
  - name: power_production_sum_Shelly
    source: sensor.shelly1pm_power
    platform: integration
    unit_time: s
    round: 2
    method: left

  - name: power_production_sum_MQTT
    source: sensor.pv1_power_mqtt.   # this works fine
    platform: integration
    unit_time: s
    round: 2
    method: left    
  
automation:

  - id: power_data_to_file
    initial_state: true
    trigger:
      - platform: time_pattern
        seconds: "/1"
    action:
      - variables: # https://www.home-assistant.io/docs/scripts/#variables
          time: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
          prod: "{{ states('sensor.power_production')|float }}"
          # using sensor.pv1_power_mqtt fails here
          # unavailable values intentionally lead to missing output line
      - service: notify.power_data
        data_template:
          message: "{{time}},{{
                      '%5.1f' % (prod) if prod != 0 else '    0' }}"

```

It turns out that all three integrations, which are equivalent, work fine.

Yet when for instance replacing in the (simplified) automation above
`sensor.power_production` by `sensor.pv1_power_mqtt`, I get errors like:
```
2024-01-22 20:30:06.188 ERROR (MainThread) [homeassistant.components.automation.automation_2] 
Error while executing automation automation.automation_2: ValueError: Template error: float got invalid input 'unknown' 
when rendering template '{{ states('sensor.power_production'         )|float }}' but no default was specified
```

And when  for instance replacing in the ` power_consumption:` sensor above
`sensor.power_production` by `sensor.pv1_power_mqtt`, I get the following trace:
```
2024-01-22 21:07:26.976 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ min([states('sensor.power_consumption')|float,
        states('sensor.pv1_power_mqtt' )|float]) }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1925, in forgiving_float_filter
    return float(value)
           ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unknown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 568, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2231, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1928, in forgiving_float_filter
    raise_no_default("float", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1626, in raise_no_default
    raise ValueError(
ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ min([states('sensor.power_consumption')|float,
        states('sensor.pv1_power_mqtt' )|float]) }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 694, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 570, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ min([states('sensor.power_consumption')|float,
        states('sensor.pv1_power_mqtt' )|float]) }}' but no default was specified
2024-01-22 21:07:26.979 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ min([states('sensor.power_consumption')|float,
        states('sensor.pv1_power_mqtt' )|float]) }}' but no default was specified') while processing template 'Template<template=({{ min([states('sensor.power_consumption')|float,
        states('sensor.pv1_power_mqtt' )|float]) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.power_own_use'
```

**Comment by jbouwh** [comment] 2024-01-22 21:46
It seems your MQTT sensor has not a valid value. In that case the state is `unknown`, you template assumes the value is a float though. The MQTT integration does not generate entities that are not supported by other integrations.
You template sensor config seems to cause the error you see in the logs.
As it seems this is not issue with Home Assistant I will close this issue.
This is not the place to ask for support on how to use automations and templates. Please use the Home Assistant Community for that.

**Closed as not planned by jbouwh** 2024-01-22 21:46 UTC
Labels: integration: mqtt, needs-more-information

**Comment by DDvO** [comment] 2024-01-23 21:22
Ah, now I understand: the problem is not that the MQTT-based sensor is not found/recognized, 
but in case its value is not a number, it cannot be used in arithmetic expressions, which makes sense.
So now I use `is_number()` to check for this case (and do special handling where needed)
and use `| float(0)` where it makes sense to gloss over an unknown value when summing up.

> As it seems this is not issue with Home Assistant

There are still some HA issues here.
* Not good that HA spits out tracebacks in part of the situations where an unknown value is attempted to get used for calculations. This is needless clutter and confusing and wrongly confirmed my impression that there must be an HA bug here.
* All the error output shown above does not report in which (config) file and which line where the problem was found.
This needlessly hinders usability (user-side debugging).
* Good that integrations (Riemann sums) apparently can cope with unknown values, doing an implicit ` | float(0)`.
This should be documented in https://www.home-assistant.io/integrations/integration/ 
* Also more generally, the HA handling of unknown values is tricky and should be documented more prominently.

**Comment by DDvO** [comment] 2024-01-23 21:30
And one more related issue here:
* For the sensors provided by the Hoymiles integration, it took me quite a lot of trial and error find out that HA apparently does not understand that for instance `states('sensor.hm_power')` is a number, so I had to append `| float`.

**Comment by jbouwh** [comment] 2024-01-23 22:15
> Ah, now I understand: the problem is not that the MQTT-based sensor is not found/recognized, but in case its value is not a number, it cannot be used in arithmetic expressions, which makes sense. So now I use `is_number()` to check for this case (and do special handling where needed) and use `| float(0)` where it makes sense to gloss over an unknown value when summing up.
> 
> > As it seems this is not issue with Home Assistant
> 
> There are still some HA issues here.
> 
>     * Not good that HA spits out tracebacks in part of the situations where an unknown value is attempted to get used for calculations. This is needless clutter and confusing and wrongly confirmed my impression that there must be an HA bug here.
> 
>     * All the error output shown above does not report in which (config) file and which line where the problem was found.
>       This needlessly hinders usability (user-side debugging).
> 
>     * Good that integrations (Riemann sums) apparently can cope with unknown values, doing an implicit ` | float(0)`.
>       This should be documented in https://www.home-assistant.io/integrations/integration/
> 
>     * Also more generally, the HA handling of unknown values is tricky and should be documented more prominently.

The tracebacks should help users to see what is happening. MQTT entities and templates are highly modable. Not all fail cases can be handled friendly. The stack traces will help users and developers to determine the root case.
You can open an issue for specific cases where a stacktrace is not warranted and logging should be improved, or when the documentation is not correct.

HA checks config against a schema, but it your case there is no syntax error, it is a runtime error, hence the stack trace, because the config is failing against the schema.

An entity (e.g. a sensor) should be assigned a state. Till that is happened the state will be `unknown`.

**Comment by DDvO** [comment] 2024-01-24 07:50
> The tracebacks should help users to see what is happening. 

Of the error message and related lengthy traceback I quoted above, only the following portions are of help to users:
```
2024-01-22 21:07:26.976 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ min([states('sensor.power_consumption')|float,
        states('sensor.pv1_power_mqtt' )|float]) }}) renders=2>
Traceback (most recent call last):
...
   in forgiving_float_filter   return float(value)
   ValueError: could not convert string to float: 'unknown'
...
  ValueError: Template error: float got invalid input 'unknown' when rendering template '{{   min([states('sensor.power_consumption')|float,
        states('sensor.pv1_power_mqtt' )|float]) }}' but no default was specified
...
  in entity 'sensor.power_own_use'
```
The text quoting the failing expression `min(...)` is given in the traceback tree times.
The rest is HA implementation detail that can only be of interest to developers.
So this certainly deserves cleanup.

>MQTT entities and templates are highly modable. Not all fail cases can be handled friendly. The stack traces will help users and developers to determine the root case.

What also would help is to have two output channels: one with error messages and warnings targeted at users.
and a more detailed one with internal trace output that can be helpful for debugging by developers. 

> You can open an issue for specific cases where a stacktrace is not warranted and logging should be improved, or when the documentation is not correct.

I'll do.

> HA checks config against a schema, but it your case there is no syntax error, it is a runtime error, hence the stack trace, because the config is failing against the schema.

Yeah, for syntax errors it is more easy to give very specific location information,
but also for runtime errors it is possible to give at least the source file name and name of the failing entity.
This is more or less already the case in the traceback I quoted yesterday, but buried in clutter.

> An entity (e.g. a sensor) should be assigned a state. Till that is happened the state will be `unknown`.

Good point, and things like this should be documented better.
I found something regarding state in https://www.home-assistant.io/integrations/template/#configuration-variables :

> state [template](https://www.home-assistant.io/docs/configuration/templating/) Required
> Defines a template to get the state of the sensor. If the sensor is numeric, i.e. it has a state_class or a unit_of_measurement, 
> the state template must render to a number or to none. The state template must not render to a string, including unknown or unavailable.
> An availability template may be defined to suppress rendering of the state template 

while this does not say that anyway the state value defaults to `unknown`.

And for the legacy form of defining sensors the doc just says:
> value_template [template](https://www.home-assistant.io/docs/configuration/templating/) Required
> The sensor is on if the template evaluates as True and off otherwise. The actual appearance in the
> frontend (Open/Closed, Detected/Clear etc) depends on the sensor’s device_class value

which does not describe the treatment of unknown/unavailable values.

**Comment by jbouwh** [comment] 2024-01-24 09:19
> Of the error message and related lengthy traceback I quoted above, only the following portions are of help to users

I should have set `users` and `developers`. But this case is closed as it is about MQTT sensors. Please do not further discuss here. You can use Discord or the HA Community for that.

> What also would help is to have two output channels: one with error messages and warnings targeted at users.
and a more detailed one with internal trace output that can be helpful for debugging by developers.

The UI supports some error handling, sometimes even with translations. For templates this is not supported. Instead there is a helper at the developers tools on your Home Assistant instance, you turn on the developers tools by enabling `advanced settings` in your user settings.

Most of the MQTT errors should be handled and not have a large traceback. If you need more information on what is happening, the debug logging can be turned on. It will help you to see what messages are send and received and what templates did render to. Most users will use MQTT because an other integration or service was supplying the configs. When you want to create your own MQTT entities with templates, this is considered as an advanced user feature. In the UI the error logs have been made more user friendly.

> Yeah, for syntax errors it is more easy to give very specific location information, but also for runtime errors it is possible to give at least the source file name and name of the failing entity. This is more or less already the case in the traceback I quoted yesterday, but buried in clutter.

The reason for the traceback on templates errors is because it can be very hard to track down the cause of the error without it. But true, it might help a lot if there was more info on the failing config. The integration and platform calling templates from config should handle this. In this case that would probably be the template sensor.
