### ISSUE TITLE
RM4C Mini is *NOT* supported!

### ISSUE THREAD

**Issue by kevinkey619** [home-assistant/home-assistant.github.io#23366] opened 2022-07-12 04:23 UTC
### Feedback

Please do not list the RM4C Mini as being supported. I wasted money on buying a RM4C Mini and integration keeps telling me that it's "not supported".

### URL

https://www.home-assistant.io/integrations/broadlink/

### Version

2022.7.3

**Comment by elupus** [comment] 2022-07-12 10:41
Duplicate of: https://github.com/home-assistant/core/issues/75038

**Closed as not planned by elupus** 2022-07-12 10:41 UTC
Labels: integration: broadlink
