### ISSUE TITLE
Unable to pull multiple entities - only 1 entity is pulled

### ISSUE THREAD

**Issue by amritgary** [home-assistant/home-assistant.github.io#19128] opened 2021-08-29 16:31 UTC
### Feedback

There are two entities, but it's only pulling the first one..
The 'somecomfort --devices' command works well and pulls multiple devices, but the integration itself is limiting the pull to the first entity only

### URL

https://www.home-assistant.io/integrations/honeywell/

### Version

2021.8.8

**Comment by rdfurman** [comment] 2021-08-29 16:33
Duplicate of https://github.com/home-assistant/core/issues/53981.

**Comment by frenck** [comment] 2021-09-22 14:04
Closing this as a duplicate

**Closed as completed by frenck** 2021-09-22 14:04 UTC
Labels: integration: honeywell
