### ISSUE TITLE
Clarify documentation for Integration->System Monitor: network_in/out vs. throughput_network_in/out

### ISSUE THREAD

**Issue by i-C-o-d-e-r** [home-assistant/home-assistant.github.io#17196] opened 2021-03-30 21:25 UTC
### Feedback

It is not clear what the difference is between network_in and throughput_network_in and network_out and throughput_network_out.

### URL

https://www.home-assistant.io/integrations/systemmonitor/

### Version

2021.3.4

If someone would explain this to me, I could try to add the explaination to the documentation.

**Comment by frenck** [comment] 2021-05-09 22:53
One is totals, the other is the current rate of data going through... hence "throughput".

Closing this, as I'm going to assume this is caused by a small language barrier.

../Frenck

**Closed as completed by frenck** 2021-05-09 22:53 UTC
Labels: integration: systemmonitor

**Comment by i-C-o-d-e-r** [comment] 2021-05-10 07:02
Thanks for the explaination. I think I got it now. :-)

While I admit that my confusion can be caused by the language barrier, still network_in and network_out should have been named total_network_in and total_network_out then. As this would be an annoying breaking change, the documentation should be more clear about this.

Anyway, thank you very much!
