### ISSUE TITLE
Can't find documentation regarding Proximity 'Tolerance distance'.

### ISSUE THREAD

**Issue by zirdum** [home-assistant/home-assistant.github.io#31662] opened 2024-02-28 17:25 UTC
### Feedback

Smarthomejunkie lists this setting as:
`...you can enter a tolerance distance here. The tolerance is used to calculate the direction of travel in meters (m) to filter out small GPS coordinate changes. It’s only considered for the calculation of the direction, so if your movement distance (the distance between two gps measurements) is lower than the tolerance, it will be ignored. I will set it to 10 for this example.`

It should be referenced somewhere on Home Assistant's site however. It's also unclear if the units are always in meters for this, or if they follow what's set for the proximity sensors?

### URL

https://www.home-assistant.io/integrations/proximity/

### Version

2024.2.5

**Comment by mib1185** [comment] 2024-02-29 18:45
- duplicate of #31312

**Closed as completed by mib1185** 2024-02-29 18:45 UTC
Labels: integration: proximity
