### ISSUE TITLE
Facebox seems to have been discontinued by its parent company

### ISSUE THREAD

**Issue by thefunkygibbon** [home-assistant/home-assistant.github.io#30737] opened 2024-01-09 10:43 UTC
### Feedback

It is no longer possible to acquire the required API key to get this working as Veritone the parent company has stopped allowing access to the developer portal, at least for new accounts (unsure if existing users are still able to)

This should be at least mentioned in the documentation as it can save a lot of time trying to work out how to access the developer page for people wanting to use this., 

### URL

https://www.home-assistant.io/integrations/facebox/

### Version

2024.1.2

**Comment by klaasnicolaas** [comment] 2024-01-10 01:42
There are plans to remove the integration: https://github.com/home-assistant/home-assistant.io/pull/30621

./Klaas

**Comment by reedy** [comment] 2024-01-14 16:42
Also a dupe of #29265

**Comment by frenck** [comment] 2024-01-15 08:34
The integration has been removed for 2024.2

**Closed as completed by frenck** 2024-01-15 08:34 UTC
Labels: integration: facebox
