### ISSUE TITLE
Documentation change

### ISSUE THREAD

**Issue by jackb007** [home-assistant/home-assistant.github.io#28631] opened 2023-08-19 00:59 UTC
### Feedback

I think it would be helpful to mention Home Assistant needs restarting completely after any changes to alerts or to the alarm control panel for the changes to take effect. It even needs restarting for an alert or alarm entity to be created. This is in contrast to automations, for which a reload of the automations yaml file is enough for changes to take effect or for a new automation to be created. I spent a full day trying to figure this out. In my opinion, this information should be at the top of the page.

### URL

https://www.home-assistant.io/integrations/alert/

### Version

2023.8.3

**Comment by klaasnicolaas** [comment] 2023-08-19 10:27
Duplicate of #28630 (except you named another integration)

**Closed as not planned by klaasnicolaas** 2023-08-19 10:27 UTC
Labels: integration: alert
