### ISSUE TITLE
I'm using EcoVacst50pro This product is registered as an account with the home assistant, but it does not work The Clean Start button is not activated and the map is not checked

### ISSUE THREAD

**Issue by kmsg0000** [home-assistant/home-assistant.github.io#35260] opened 2024-10-16 22:45 UTC
### Feedback

I'm using EcoVacst50pro This product is registered as an account with the home assistant, but it does not work The Clean Start button is not activated and the map is not checked

### URL

https://www.home-assistant.io/integrations/ecovacs/

### Version

2024.10.2

### Additional information

I'm using EcoVacst50pro This product is registered as an account with the home assistant, but it does not work The Clean Start button is not activated and the map is not checked

**Comment by mib1185** [comment] 2024-10-18 06:51
- duplicate of your own report #35266

**Closed as not planned by mib1185** 2024-10-18 06:51 UTC
Labels: integration: ecovacs
