### ISSUE TITLE
App don't work

### ISSUE THREAD

**Issue by Oscarbin001** [home-assistant/home-assistant.github.io#29155] opened 2023-10-04 15:16 UTC
### Feedback

There is no URL https://server.growatt.com/ among the possible choices

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2023.9.3

**Comment by Oscarbin001** [comment] 2023-10-04 15:17
Thanks but  @muppet3000 have a login problem

**Comment by muppet3000** [comment] 2023-10-04 16:14
Closing as duplicate of [#100874](https://github.com/home-assistant/core/issues/100874)

**Comment by muppet3000** [comment] 2023-10-04 16:14
@home-assistant close

**Closed as completed by muppet3000** 2023-10-04 16:14 UTC
Labels: integration: growatt_server

**Comment by Oscarbin001** [comment] 2023-10-06 06:29
![image](https://github.com/home-assistant/home-assistant.io/assets/146742260/351585fa-0cd6-4509-83c3-646a19fb7545)


Excuse me for delay time of responce; I Try all but the error is the same; Can you help me? I  Try all described in #100874
Thanks in advance

**Comment by muppet3000** [comment] 2023-10-06 06:30
Please see the final comment in #100874
