### ISSUE TITLE
New lovelace thermostat card doesn't let you change the title. 

### ISSUE THREAD

**Issue by jpcaldwell30** [home-assistant/home-assistant.github.io#7179] opened 2018-10-27 21:37 UTC
New (v8.1) Lovelace thermostat card doesn't let you change the title. It says "Upstairs" by default with no way to change it.

**Comment by fabaff** [comment] 2018-10-28 15:05
Duplicate of https://github.com/home-assistant/home-assistant/issues/17880

**Closed as completed by fabaff** 2018-10-28 15:05 UTC
