### ISSUE TITLE
Mention required energy integration

### ISSUE THREAD

**Issue by pbavinck** [home-assistant/home-assistant.github.io#19311] opened 2021-09-12 09:12 UTC
### Feedback

Looking at the forum, I am nt the only one who spend more than an hour figuring out that in order to be able to use the energy integration and dashboard, it necessary to add the following line to your configuration:

```
energy:
```

Please add this necessary step to the documentation.

### URL

https://www.home-assistant.io/docs/energy/

### Version

2021.9.5

**Comment by ludeeus** [comment] 2021-09-12 09:13
Duplicate of https://github.com/home-assistant/home-assistant.io/issues/18905

**Closed as completed by ludeeus** 2021-09-12 09:13 UTC
