### ISSUE TITLE
HA Core 2022.6.7 Breaks this Integration

### ISSUE THREAD

**Issue by Hamish1066** [home-assistant/home-assistant.github.io#23219] opened 2022-06-27 16:30 UTC
### Feedback

When I installed HA Core 2022.6.7, I was no longer able to control my alarm system with HA, though I was still able to see the status and receive notifications when the alarm was armed/disarmed. 

### URL

https://www.home-assistant.io/integrations/envisalink/

### Version

2022.6.7

**Comment by ufodone** [comment] 2022-06-27 17:17
This is likely the same issue others have been experiencing (https://github.com/home-assistant/core/issues/73869 and https://github.com/home-assistant/core/issues/73941). 

People have been having success increasing the timeout as a workaround.  A fix for the underlying issue will be included in a future HA release.

**Comment by Hamish1066** [comment] 2022-06-27 18:26
Thank you - that fixed the issue for me.

**Closed as completed** 2022-06-27 18:27 UTC
Labels: integration: envisalink

**Comment by undert03** [comment] 2022-06-28 11:19
Confirming on 2022.6.7 timeout of 20 worked for me

**Comment by jgray-proaudio** [comment] 2022-07-04 16:38
Switching to a timeout of 15 seconds is working for me.

**Comment by jd3073** [comment] 2022-08-02 12:59
If all my alarm binary_sensors. show => This entity ('binary_sensor.door') does not have a unique ID, therefore its settings cannot be managed from the UI_**  including alarm_control_panel entity, along with:
  Logger: pyenvisalink.envisalink_base_client
  Source: /usr/local/lib/python3.10/site-packages/pyenvisalink/envisalink_base_client.py:77
  The server closed the connection. Reconnecting...
even though timeout is set to 20, is this a connection issue or something else?  A little lost....appreciate any help.

Version | core-2022.7.7
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.10.5
Operating System Family | Linux
Operating System Version | 5.15.32-v8

HA System Health shows Envisalink connected 1.79 sec.

**Comment by ufodone** [comment] 2022-08-07 19:46
That first error is likely “normal” because the envisalink integration is a bit dated and still uses configuration.yml for its setup.

Regarding the timeout error, does your setup generally work or does it regularly not function correctly?  I’ve found the EVL devices to be a little finicky about network traffic and can sometimes become unresponsive for up to ~30 seconds.  I’ve also seen these types of timeouts when HA starts up - I suspect related to the overall system being a bit overloaded when HA starts up.  If you see that timeout during HA startup but your system works properly after that then you could try increasing the timeout more to make the error go away.  If it continually spits out that timeout error then there is likely something else going on.

**Comment by jd3073** [comment] 2022-08-08 14:55
@ufodone - thank you for responding.  The alarm sensors are circle line thru it in entities, so not really available with error being no unique ID. 
I’ve upped timeout all the way to 100 and no change. 
In other thread’s I’ve seen some suggest user/user for username & pw, but that didn’t work either. I’m using web login credentials.  Could that be the problem?
I can ping my EVL but can only login via web UI, not direct IP address with or without port.

**Comment by ufodone** [comment] 2022-08-09 19:40
@jd3073 When you say “web UI”, are you referring to your login for the EyezOn website or for the web UI when connecting directly to the EVL? The latter is what you should be using.

It’s also worth noting that you can only have a single connection to the EVL on port 4025 so a disconnection that you’re seeing could be caused by something else on your network already being connected to it (e.g. another instance of Home Assistant).

You might also try turning debug logging on for the envisalink integration and the underlying pyenvisalink library.  Something like the following in your configuration.yml:

```
default: info
  logs:
    home assistant.components.envisalink: debug
    pyenvisalink: debug
```

Please note that your configured username and password may show up in the logs so be careful if you post a by logs here.

**Comment by jd3073** [comment] 2022-08-10 00:04
@ufodone  - Thank you.
By web UI, I meant logging into the EyezOn website.  I am unable to log into web UI.   When attempting to web UI connect directly to the EVL I get an immediate error screen (_This site can’t be reached The connection was reset_) regardless of which browser I try.  I can ping the local EVL IP address (0% packet loss) but cannot get it's page.  Sounds like I need to figure that out first as per your guidance, something else might already be preventing HA from connecting.

I tried turning on debug logging, but can't restart due to this new error in Configuration.YAML:

- _The system cannot restart because the configuration is not valid: Integration error: home - Integration 'home' not found. Integration error: pyenvisalink - Integration 'pyenvisalink' not found. Integration error: default - Integration 'default' not found. Integration error: logs - Integration 'logs' not found._

I installed pyenvisalnk, but will google what else I'm missing that's preventing logging.

ufodone - Thanks again for your help. I'll keep fiddling until I get this figured out.

**Comment by klaasnicolaas** [comment] 2022-08-10 00:23
Folks the issue is already closed and this repository is not the place for integration issues. The issue tracker here is used for documentation feedback, please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by jd3073** [comment] 2022-08-10 01:40
thanks Klaas, will do. over & out.
