### ISSUE TITLE
Integration not working anymore

### ISSUE THREAD

**Issue by sbesteman** [home-assistant/home-assistant.github.io#19325] opened 2021-09-13 10:02 UTC
### Feedback

Logger: homeassistant.components.sensor
Source: components/growatt_server/sensor.py:870
Integration: Sensor (documentation, issues)
First occurred: 11:49:09 AM (1 occurrences)
Last logged: 11:49:09 AM

Error while setting up growatt_server platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/src/homeassistant/homeassistant/components/growatt_server/sensor.py", line 885, in async_setup_entry
    devices, plant_id = await hass.async_add_executor_job(get_device_list, api, config)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/growatt_server/sensor.py", line 870, in get_device_list
    devices = api.device_list(plant_id)
  File "/usr/local/lib/python3.9/site-packages/growattServer/__init__.py", line 440, in device_list
    return self.plant_info(plant_id)['deviceList']
  File "/usr/local/lib/python3.9/site-packages/growattServer/__init__.py", line 453, in plant_info
    data = json.loads(response.content.decode('utf-8'))
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 19)

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2021.9.5

### Additional information

Logger: homeassistant.components.sensor
Source: components/growatt_server/sensor.py:870
Integration: Sensor (documentation, issues)
First occurred: 11:49:09 AM (1 occurrences)
Last logged: 11:49:09 AM

Error while setting up growatt_server platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/src/homeassistant/homeassistant/components/growatt_server/sensor.py", line 885, in async_setup_entry
    devices, plant_id = await hass.async_add_executor_job(get_device_list, api, config)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/growatt_server/sensor.py", line 870, in get_device_list
    devices = api.device_list(plant_id)
  File "/usr/local/lib/python3.9/site-packages/growattServer/__init__.py", line 440, in device_list
    return self.plant_info(plant_id)['deviceList']
  File "/usr/local/lib/python3.9/site-packages/growattServer/__init__.py", line 453, in plant_info
    data = json.loads(response.content.decode('utf-8'))
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 19)

**Comment by muppet3000** [comment] 2021-09-13 10:03
Duplicate of: https://github.com/home-assistant/core/issues/56044

**Closed as completed** 2021-09-13 11:45 UTC
Labels: integration: growatt_server
