### ISSUE TITLE
Mullvad VPN - Setup Doesn't Work

### ISSUE THREAD

**Issue by bbalz** [home-assistant/home-assistant.github.io#17004] opened 2021-03-14 16:57 UTC
### Feedback

The setup for the Mullvad Add-in does not work.

I add it in the integrations area with the "+"

It prompts to 'Set up the Mullvad VPN Integration?" and I click 'Submit' 

It then shows a spinning wheel. 

Once that is done after a second or two, it says 'Created configuration for Mullvad VPN' and I click 'Finish' and then it shows in my integrations tab.  However I can't configure anything like adding an account number.

### URL

https://www.home-assistant.io/integrations/mullvad/

### Version

2021.3.4

This is what it shows me after adding the integration:
![image](https://user-images.githubusercontent.com/47855770/111076865-3aca8100-84bc-11eb-9742-50c5365a0115.png)

![image](https://user-images.githubusercontent.com/47855770/111076871-3d2cdb00-84bc-11eb-8291-b24b3e0e5a0a.png)

![image](https://user-images.githubusercontent.com/47855770/111076874-40c06200-84bc-11eb-9a4f-67f9bb921d64.png)

![image](https://user-images.githubusercontent.com/47855770/111076889-4ddd5100-84bc-11eb-8809-19c8bcb7eb0f.png)

![image](https://user-images.githubusercontent.com/47855770/111076892-5170d800-84bc-11eb-9069-f7039c6807db.png)

It does add the entity to my HA instance: 
![image](https://user-images.githubusercontent.com/47855770/111076959-93018300-84bc-11eb-9905-9e4ecd114b6a.png)

![image](https://user-images.githubusercontent.com/47855770/111076961-95fc7380-84bc-11eb-9e85-7892587f5775.png)

Looking at the documentation I'm not sure if I'm missing something or if I should've been prompted to add an account number?  My end goal would be to utilizing Mullvad for my entire network since Ad-Guard is setup and all traffic goes through my Home Assistant device, it would be great to utilize my VPN for the whole network as well.

Thanks for any assistance.

**Comment by frenck** [comment] 2021-03-15 15:26
![image](https://user-images.githubusercontent.com/195327/111178174-2dd88b00-85ab-11eb-95f8-84bf7efad972.png)


☝️ That shows it is working. Your account number has nothing to do with this integration. It gives information on the connection, not your account.

**Comment by frenck** [comment] 2021-03-15 15:27
Closing as this is not a bug.

**Closed as completed by frenck** 2021-03-15 15:27 UTC
Labels: integration: mullvad
