### ISSUE TITLE
SQLAlchemy needed for Core installation

### ISSUE THREAD

**Issue by DavePfz** [home-assistant/home-assistant.github.io#23768] opened 2022-08-14 21:42 UTC
### Feedback

I followed the instructions for the Core installation and it would not run. The logs were empty, but when I tired to auto start, I got messages that the SQLAlchemy module was not found. 

Was this missed during the install process?

### URL

https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-core

### Version

2022.8.3

### Additional information

I tried installing manually, but am not sure I did the right thing. I still got errors from the autos tart process but they were different. My Raspbian environment is bullseye.

**Comment by klaasnicolaas** [comment] 2022-08-15 06:17
Duplicate of #23741

**Closed as completed** 2022-08-15 06:17 UTC
Labels: installation
