### ISSUE TITLE
coinbase api key

### ISSUE THREAD

**Issue by Fotali** [home-assistant/home-assistant.github.io#32897] opened 2024-05-22 20:29 UTC
### Feedback

I guess I cannot say for sure if it does not work.  Seems coinbase api keys take 48 hours to become valid.  Post back here after I check it.

### URL

https://www.home-assistant.io/integrations/coinbase/

### Version

2024.5.4

**Comment by TomBrien** [comment] 2024-05-22 20:39
Hi, this is a duplicate of home-assistant/core#116282. There is a fix in home-assistant/core#116345 which migrates to the new API format and is waiting for review.

**Closed as completed** 2024-05-22 20:39 UTC
Labels: integration: coinbase
