### ISSUE TITLE
Error after Google shows success!

### ISSUE THREAD

**Issue by kevinflynn1967** [home-assistant/home-assistant.github.io#24934] opened 2022-11-14 01:40 UTC
### Feedback

I have tried this twice and have followed the documentation to the letter entering everything through Manual Mode. When I get to the final step of linking to my Google Cloud, I get "Success!" from Google but when I got back to HA it just states "Error". Any thought on what is going on? Was there a release that changed the App type? 

14. Set the Application type to TV and Limited Input and give this credential set a name (like “Home Assistant Credentials”) then click Create.

### URL

https://www.home-assistant.io/integrations/google/

**Comment by allenporter** [comment] 2022-11-14 02:01
@kevinflynn1967 you didn't say which version but I am assuming this was from 2022.11.1 or 2022.11.2 and it needs a patch upcoming in 2022.11.3

**Comment by kevinflynn1967** [comment] 2022-11-14 13:33
@allenporter Hi Allen, thank you for getting back to me so quickly. I am extremely new to HA and trying my best to read before even asking any questions. I am on version 2022.11.2 

Have a great day

**Comment by allenporter** [comment] 2022-11-14 15:12
Duplicate of https://github.com/home-assistant/core/issues/82065

**Closed as completed by allenporter** 2022-11-14 15:12 UTC
Labels: integration: google
